import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
const api=await import('../src/trello.js').catch(()=>({}));
const creds=()=>({apiKey:'ab12cd34ef56ab12cd34ef56ab12cd34',token:'to12ken34to12ken34to12ken34to12ken34to12ken34to12ken34to12ken',board:'https://trello.com/b/abc12345/demo-board'});
test('Trello connection saves credentials and board, backs up changes and hides secrets',async()=>{
  assert.equal(typeof api.configureTrello,'function');
  const file=path.join(await mkdtemp(path.join(tmpdir(),'muse-trello-')),'trello.json');
  const verified={username:'demo-user',boardName:'Demo board',boardUrl:'https://trello.com/b/abc12345/demo-board',listCount:3};
  const result=await api.configureTrello(file,{...creds(),...verified});
  assert.equal(result.configured,true);assert.equal(result.boardName,'Demo board');assert.equal(result.listCount,3);
  assert.doesNotMatch(JSON.stringify(result),/ab12cd34|to12ken/);
  const saved=JSON.parse(await readFile(file,'utf8'));
  assert.equal(saved.board,'abc12345');assert.equal(saved.boardName,'Demo board');assert.equal(saved.apiKey,creds().apiKey);
  assert.deepEqual(JSON.parse(await readFile(path.join(path.dirname(file),'trello.backup.json'),'utf8')),saved);
  assert.equal(api.trelloStatus(saved).configured,true);
  assert.equal(api.trelloStatus(null).configured,false);
  await api.configureTrello(file,{...creds(),boardName:'Second',boardUrl:'https://trello.com/b/abc12345/x',listCount:1,username:'u'});
  assert.equal(JSON.parse(await readFile(path.join(path.dirname(file),'trello.backup.json'),'utf8')).boardName,'Second');
  const cleared=await api.configureTrello(file,null);
  assert.equal(cleared.configured,false);assert.equal(await api.readTrelloSettings(file),null);
});
test('Trello rejects invalid credentials and board links without writing',async()=>{
  assert.equal(typeof api.configureTrello,'function');
  const file=path.join(await mkdtemp(path.join(tmpdir(),'muse-trello-invalid-')),'trello.json');
  const original=JSON.stringify({apiKey:'k'.repeat(32),token:'t'.repeat(64),board:'abc12345'});
  await writeFile(file,original);
  for(const apiKey of ['','short','has space','bad\nkey'])await assert.rejects(api.configureTrello(file,{...creds(),apiKey}));
  for(const token of ['','short','has space'])await assert.rejects(api.configureTrello(file,{...creds(),token}));
  for(const board of ['','not a link','https://trello.com/c/abc12345/card','https://example.com/b/abc12345'])await assert.rejects(api.configureTrello(file,{...creds(),board}));
  assert.equal(await readFile(file,'utf8'),original);
  await writeFile(file,'');
  await assert.rejects(api.configureTrello(file,creds()),/unreadable/i);
  assert.equal(await readFile(file,'utf8'),'');
  await assert.rejects(api.configureTrello(file,null),/unreadable/i);
});
test('Trello parses board links and bare IDs',()=>{
  assert.equal(typeof api.boardIdFromLink,'function');
  assert.equal(api.boardIdFromLink('https://trello.com/b/abc12345/demo-board'),'abc12345');
  assert.equal(api.boardIdFromLink('https://trello.com/b/abc12345/'),'abc12345');
  assert.equal(api.boardIdFromLink('abc12345'),'abc12345');
  assert.equal(api.boardIdFromLink('5f6a7b8c9d0e1f2a3b4c5d6e'),'5f6a7b8c9d0e1f2a3b4c5d6e');
  for(const board of ['','  ','https://trello.com/c/abc12345/card','https://example.com/b/abc12345','not a link','toolongboardid123'])assert.throws(()=>api.boardIdFromLink(board));
});
test('Trello verifies member, board and lists before connecting, redacting secrets',async()=>{
  assert.equal(typeof api.checkTrello,'function');
  const requests=[];
  const fetch=async url=>{requests.push(url);
    if(url.includes('/members/me'))return new Response(JSON.stringify({username:'demo-user'}));
    if(url.includes('/lists'))return new Response(JSON.stringify([{name:'Todo'},{name:'Doing'},{name:'Done'}]));
    return new Response(JSON.stringify({name:'Demo board',url:'https://trello.com/b/abc12345/demo-board'}));};
  const result=await api.checkTrello(creds(),fetch);
  assert.equal(result.username,'demo-user');assert.equal(result.boardName,'Demo board');assert.equal(result.listCount,3);
  assert.doesNotMatch(JSON.stringify(result),/ab12cd34|to12ken/);
  assert.equal(requests.length,3);
  assert.ok(requests.every(url=>url.includes('key=ab12cd34') && url.includes('token=to12ken')));
  assert.ok(requests.some(url=>url.includes('/boards/abc12345?')));
  await assert.rejects(api.checkTrello(creds(),async()=>new Response('invalid key ab12cd34',{status:401})),error=>/key or token/i.test(error.message) && !error.message.includes('ab12cd34'));
  await assert.rejects(api.checkTrello(creds(),async()=>{throw new DOMException('timed out','AbortError');}),/timed out/i);
});
