import {waitForCondition} from './electron-ui.js';
import {launchDesktop,clickControl} from './electron-ui.js';
import {createServer} from 'node:http';
import {mkdtemp,mkdir,rmdir,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {tmpdir} from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
const packaged=process.argv.slice(2).find(argument=>!argument.startsWith('--'));
let siteLoads=0;
const server=createServer((req,res)=>{if(req.url==='/')siteLoads++;res.setHeader('Content-Type','text/html');res.end('<!doctype html><title>Annotation fixture</title><style>body{margin:40px;background:#eef2fa;font:22px Arial}section{padding:40px;background:white;color:#184da0;border-radius:16px}button{padding:15px;font:inherit}</style><section id="card"><h1 id="heading">Design heading</h1><button id="action" onclick="window.clicked=true">Improve this button</button><input value="private-value"></section>');});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const url=`http://127.0.0.1:${server.address().port}/`;
const env={...process.env};delete env.ELECTRON_RUN_AS_NODE;env.MUSE_DESKTOP_TEST_USER_DATA=await mkdtemp(path.join(tmpdir(),'mora-notes-'));
await mkdir('artifacts/annotation-proof',{recursive:true});let app;
try{
  app=await launchDesktop(packaged,env);let page=app.context().pages().find(candidate=>candidate.url().endsWith('/index.html'));
  await page.locator('#browser-button').click();await page.locator('#browser-url').fill(url);await page.locator('#browser-url').press('Enter');
  let web;await waitForCondition(page,async()=>!(await window.muse.browserCommand('state')).loading);const deadline=Date.now()+10000;while(!web&&Date.now()<deadline){web=app.context().pages().find(candidate=>candidate.url()===url);if(!web)await page.waitForTimeout(50);}assert.ok(web);await web.locator('#action').waitFor();
  const point=async(x,y)=>{const width=await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(window=>window.webContents.getURL().endsWith('/index.html')).contentView.children.find(view=>view.webContents).getBounds().width),scale=width/await web.evaluate(()=>innerWidth);return {x:x*scale,y:y*scale};};
  async function clickNative(p){await app.evaluate(({BrowserWindow},p)=>{const web=BrowserWindow.getAllWindows().find(window=>window.webContents.getURL().endsWith('/index.html')).contentView.children.find(view=>view.webContents).webContents;for(const type of ['mouseMove','mouseDown','mouseUp'])web.sendInputEvent({type,x:Math.round(p.x),y:Math.round(p.y),button:'left',clickCount:1});},p);}
  async function dragNative(a,b){await app.evaluate(async({BrowserWindow},{a,b})=>{const web=BrowserWindow.getAllWindows().find(window=>window.webContents.getURL().endsWith('/index.html')).contentView.children.find(view=>view.webContents).webContents;const input=(type,p)=>web.sendInputEvent({type,x:Math.round(p.x),y:Math.round(p.y),button:'left',clickCount:1});input('mouseMove',a);input('mouseDown',a);for(let step=1;step<=8;step++){await new Promise(resolve=>setTimeout(resolve,15));input('mouseMove',{x:a.x+(b.x-a.x)*step/8,y:a.y+(b.y-a.y)*step/8});}await new Promise(resolve=>setTimeout(resolve,15));input('mouseUp',b);},{a,b});}
  async function clickTarget(selector){await waitForCondition(page,async()=>(await window.muse.browserCommand('state')).annotating);await page.evaluate(()=>{const {width,height}=document.getElementById('browser-viewport').getBoundingClientRect();window.annotationViewportSizes=[{width,height}];});const rect=await web.locator(selector).evaluate(node=>{const r=node.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height};}),p=await point(rect.x+rect.width/2,rect.y+rect.height/2);await clickNative(p);}
  await page.evaluate(()=>{window.annotationViewportSizes=[];new ResizeObserver(entries=>{const {width,height}=entries[0].contentRect;window.annotationViewportSizes.push({width,height});}).observe(document.getElementById('browser-viewport'));});
  await page.waitForFunction(()=>window.annotationViewportSizes.length);
  async function assertSteadyViewport(label){const sizes=await page.evaluate(()=>window.annotationViewportSizes);assert.equal(new Set(sizes.map(size=>JSON.stringify(size))).size,1,label+' must not resize the preview');}
  async function editor(){const end=Date.now()+10000;while(Date.now()<end){const note=app.context().pages().find(candidate=>candidate.url().endsWith('/annotation-editor.html'));if(note){await note.locator('#note').waitFor();return note;}await page.waitForTimeout(50);}throw Error('Annotation note popup did not open: '+JSON.stringify(await page.evaluate(async()=>({browser:await window.muse.browserCommand('state'),viewportSizes:window.annotationViewportSizes}))));}
  await page.locator('#prompt').fill('Keep my overall request');
  await page.locator('#browser-annotate').click();await clickTarget('#action');let note=await editor();await note.locator('#save').click();await note.locator('#error').filter({hasText:'Write a note'}).waitFor();await note.locator('#note').fill('Use a clearer label');assert.equal(await note.locator('#error').textContent(),'','Editing clears a stale validation error');await note.screenshot({path:'artifacts/annotation-proof/note-popup.png'});
  const blockedWrite=path.join(env.MUSE_DESKTOP_TEST_USER_DATA,'work',createHash('sha256').update('new').digest('hex')+'.backup.json.tmp');await mkdir(blockedWrite);await note.locator('#save').click();await note.locator('#error').filter({hasText:/EISDIR|EPERM|EACCES/}).waitFor();assert.equal(await note.locator('#note').inputValue(),'Use a clearer label','Failed save retains text');await rmdir(blockedWrite);await note.locator('#save').click();
  await page.getByRole('button',{name:'Edit note 1',exact:true}).waitFor();assert.equal(await web.evaluate(()=>!!window.clicked),false,'Selecting must not trigger the page action');
  const noteLayout=await page.locator('.saved-note-edit').evaluate(node=>({position:getComputedStyle(node).position,width:node.getBoundingClientRect().width}));
  assert.equal(noteLayout.position,'static','Saved note text must not inherit the tiny remove-button positioning');assert.ok(noteLayout.width>200,'Saved note text needs readable space');
  await assertSteadyViewport('Selecting and saving the first note');
  assert.match((await page.evaluate(()=>window.muse.getState())).draft.images[0].contextText,/Selection: #action /,'Native selection must capture the intended element');
  assert.equal(await page.locator('#prompt').inputValue(),'Keep my overall request');assert.equal(await web.locator('[data-mora-note-id]').count(),1);assert.equal(await web.evaluate(()=>document.body.textContent.includes('Use a clearer label')),false,'User note must stay outside the web page');
  await clickControl(page,'browser-region');await waitForCondition(page,async()=>(await window.muse.browserCommand('state')).annotating);const a=await point(60,60),b=await point(270,130);await dragNative(a,b);note=await editor();await note.locator('#note').fill('Add more spacing');await note.locator('#note').press('Control+Enter');await page.getByRole('button',{name:'Edit note 2',exact:true}).waitFor();
  await assertSteadyViewport('Selecting and saving additional region notes');
  const region=(await page.evaluate(()=>window.muse.getState())).draft.images[1];assert.equal(region.annotationRef.mode,'region');assert.ok(Math.abs(region.annotationRef.rect.width-210)<4&&Math.abs(region.annotationRef.rect.height-70)<4,'The native drag must capture the selected rectangle');
  assert.equal(await web.locator('[data-mora-note-id]').count(),2);assert.equal(await page.locator('#browser-send-notes').textContent(),'Send notes (2)');
  const steadyViewportSizes=await page.evaluate(()=>window.annotationViewportSizes);
  await writeFile('artifacts/annotation-proof/saved-notes.png',Buffer.from(await app.evaluate(async({BrowserWindow})=>(await BrowserWindow.getAllWindows().find(window=>window.webContents.getURL().endsWith('/index.html')).capturePage()).toPNG().toString('base64')),'base64'));
  await web.screenshot({path:'artifacts/annotation-proof/numbered-markers.png'});
  await page.locator('#browser-annotate').click();await clickTarget('#heading');note=await editor();await note.locator('#note').fill('Cancelled note');await note.locator('#note').press('Escape').catch(error=>{if(!note.isClosed())throw error;});await waitForCondition(page,async()=>!(await window.muse.browserCommand('state')).noteEditing);assert.equal(await page.locator('.saved-annotation').count(),2,'Cancel does not attach a note');
  for(const mode of ['mobile','expanded']){
    if(mode==='mobile'){await page.locator('#browser-mobile').click();await web.waitForFunction(()=>innerWidth===390);}else{await page.locator('#browser-desktop').click();await web.waitForFunction(()=>innerWidth>=1280);await page.locator('#browser-expand').click();}
    await waitForCondition(page,async()=>!(await window.muse.browserCommand('state')).noteEditing);
    await page.evaluate(()=>{const {width,height}=document.getElementById('browser-viewport').getBoundingClientRect();window.annotationViewportSizes=[{width,height}];});
    await page.locator('#browser-annotate').click();await clickTarget('#action');try{note=await editor();}catch(error){throw Error(mode+': '+error.message);}await note.locator('#note').fill('Check '+mode+' selection');await assertSteadyViewport(mode+' annotation popup');await note.locator('#cancel').click();await waitForCondition(page,async()=>!(await window.muse.browserCommand('state')).noteEditing);
    assert.equal(await page.locator('.saved-annotation').count(),2,'Cancelling '+mode+' leaves saved notes intact');
  }
  await page.locator('#browser-expand').click();
  const marker=await web.locator('[data-mora-note-id]').first().evaluate(node=>{const r=node.getBoundingClientRect();return{x:r.x,y:r.y};}),p=await point(marker.x+14,marker.y+14);await clickNative(p);note=await editor();assert.equal(await note.locator('#note').inputValue(),'Use a clearer label');await note.locator('#note').fill('Use a clearer blue label');await note.locator('#save').click();await page.getByRole('button',{name:'Edit note 1',exact:true}).filter({hasText:'blue'}).waitFor();
  await web.locator('#action').evaluate(node=>node.replaceWith(node.cloneNode(true)));await page.waitForTimeout(300);assert.equal(await web.locator('[data-mora-note-id]').first().isVisible(),false,'A marker must not attach to a replacement DOM node');
  await page.locator('#browser-annotate').click();await clickTarget('#heading');note=await editor();await note.locator('#note').fill('Keep this text through page refresh');await web.reload();assert.equal(await note.locator('#note').inputValue(),'Keep this text through page refresh','Automatic page navigation must not discard unsaved note text');await note.locator('#cancel').click();await waitForCondition(page,async()=>!(await window.muse.browserCommand('state')).noteEditing);
  await page.evaluate(()=>window.flushMoraDraft());await app.close();app=await launchDesktop(packaged,env);page=app.context().pages().find(candidate=>candidate.url().endsWith('/index.html'));await page.getByRole('button',{name:'Edit note 2',exact:true}).waitFor();assert.equal(await page.locator('#prompt').inputValue(),'Keep my overall request');
  assert.equal(await page.locator('#browser-panel').isVisible(),false,'Restart keeps sites unopened');const beforeEditLoads=siteLoads;await page.getByRole('button',{name:'Edit note 2',exact:true}).click();note=await editor();assert.equal(await note.locator('#note').inputValue(),'Add more spacing');await note.locator('#delete').click();await page.waitForFunction(()=>document.querySelectorAll('.saved-annotation').length===1);assert.equal(siteLoads,beforeEditLoads,'Editing a frozen note must not load the saved site in a hidden view');
  await page.locator('#browser-button').click();await waitForCondition(page,async()=>!(await window.muse.browserCommand('state')).loading);assert.equal((await page.evaluate(()=>window.muse.getState())).draft.images.length,1);
  const saved=(await page.evaluate(()=>window.muse.getState())).draft.images[0];assert.match(saved.contextText,/user-selected page evidence/);assert.doesNotMatch(saved.contextText,/private-value|onclick|<script/);
  await app.evaluate(({ipcMain})=>{ipcMain.removeHandler('muse:send');ipcMain.handle('muse:send',()=>{throw Error('Simulated send failure');});});
  await page.waitForFunction(()=>!document.querySelector('#browser-send-notes').disabled);await page.locator('#browser-send-notes').click();await page.locator('#error-text').filter({hasText:'Simulated send failure'}).waitFor();assert.equal(await page.locator('.saved-annotation').count(),1,'Failed send retains notes');
  await app.evaluate(({ipcMain})=>{ipcMain.removeHandler('muse:send');ipcMain.handle('muse:send',(_event,payload)=>{globalThis.annotationPayload=payload;return new Promise(resolve=>{globalThis.acceptAnnotationSend=()=>resolve({queued:true});});});});
  await page.locator('#browser-send-notes').click();await page.waitForFunction(()=>document.querySelector('#browser-annotate').disabled);const acceptanceDeadline=Date.now()+5000;while(!await app.evaluate(()=>!!globalThis.acceptAnnotationSend)&&Date.now()<acceptanceDeadline)await page.waitForTimeout(30);assert.equal(await app.evaluate(()=>globalThis.annotationPayload.images.length),1);const late={...saved,note:'Keep this later note',annotationRef:{...saved.annotationRef,id:'later-note'}};
  await app.evaluate(({BrowserWindow},images)=>BrowserWindow.getAllWindows().find(window=>window.webContents.getURL().endsWith('/index.html')).webContents.send('muse:event',{type:'annotation-saved',sessionId:null,images}),[saved,late]);await page.getByRole('button',{name:'Edit note 2',exact:true}).waitFor();await app.evaluate(()=>globalThis.acceptAnnotationSend());await page.waitForFunction(()=>document.querySelectorAll('.saved-annotation').length===1);assert.equal(await page.locator('.saved-note-edit').textContent(),'Note 1: Keep this later note','A note arriving after the sent snapshot must survive acceptance');
  const sent=await app.evaluate(()=>globalThis.annotationPayload);assert.match(sent.text,/Keep my overall request/);assert.match(sent.text,/Note 1 — requested change: Use a clearer blue label/);assert.equal(sent.images.length,1);assert.equal((await page.evaluate(()=>window.muse.getState())).draft.images[0].annotationRef.id,'later-note');
  await app.evaluate(({ipcMain})=>{ipcMain.removeHandler('muse:send');ipcMain.handle('muse:send',()=>({queued:true}));});await page.locator('#browser-send-notes').click();await page.waitForFunction(()=>!document.querySelectorAll('.saved-annotation').length);assert.equal((await page.evaluate(()=>window.muse.getState())).draft.images.length,0);
  await writeFile('artifacts/annotation-proof/result.json',JSON.stringify({version:await app.evaluate(({app})=>app.getVersion()),steadyViewportSizes,nativeElementAndRegion:true,mobileAndExpanded:true,numberedMarkers:true,saveRetry:true,cancel:true,editDelete:true,restart:true,combinedSend:true,failedSendRetention:true,laterNotesPreserved:true,noModelRequests:true,noExecutableBuild:true},null,2));
  console.log('PASS: stable preview through selection/save, native element/region input, mobile/expanded popups, numbered markers, edit/delete, cancellation, failed-save retry, restart without hidden site load, failed-send retention, combined send and delayed acceptance preserving later notes.');
}finally{await app?.close();await new Promise(resolve=>server.close(resolve));}
