import {waitForCondition} from './electron-ui.js';
import {clickControl,launchDesktop} from './electron-ui.js';
import {createServer} from 'node:http';
import {mkdtemp,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
const packaged=process.argv.slice(2).find(argument=>!argument.startsWith('--'));
const realSend=process.argv.includes('--send');
const server=createServer(async(req,res)=>{
  if(req.url==='/slow'||req.url==='/slow-resize')await new Promise(resolve=>setTimeout(resolve,req.url==='/slow-resize'?1600:500));
  res.setHeader('Content-Type','text/html');
  res.end(`<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><script>window.bootWidth=innerWidth</script><title>Design fixture</title><style>body{background:#eef2fa;padding:40px;font:18px Arial}#card{background:white;border-radius:16px;padding:30px;color:#184da0}h1{font-size:30px}a{display:block;margin:20px 0}@media(max-width:600px){#card{color:rgb(0,128,0)}body{padding:12px}}</style><section id="card"><h1>Design heading</h1><a id="link" href="/next">Change this design</a><input value="private-form-value"><button onclick="alert('must not execute')">Action</button><script>window.pageFlag='page-script'</script></section><p>${req.url}</p>`);
});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const url=`http://127.0.0.1:${server.address().port}`;
const env={...process.env};delete env.ELECTRON_RUN_AS_NODE;
env.MUSE_DESKTOP_TEST_USER_DATA=await mkdtemp(path.join(tmpdir(),'muse-browser-profile-'));
const app=await launchDesktop(packaged,env);
try {
  const page=app.context().pages().find(candidate=>candidate.url().endsWith('/index.html'));assert.ok(page,'Mora main window is available');
  await page.locator('#browser-button').waitFor({timeout:10000});
  await page.locator('#browser-button').click();
  assert.equal(await page.locator('#browser-note').count(),0,'The browser footer must not contain an inline note editor');
  await page.locator('#browser-url').fill(url);
  await page.locator('#browser-url').press('Enter');
  let web;
  const deadline=Date.now()+10000;
  while(Date.now()<deadline) {
    web=app.context().pages().find(tab=>tab.url().startsWith(url));
    if(web)break;
    await new Promise(resolve=>setTimeout(resolve,100));
  }
  if(!web) console.log(await page.evaluate(()=>window.muse.browserCommand('state')),await app.evaluate(({webContents})=>webContents.getAllWebContents().map(web=>({id:web.id,url:web.getURL(),type:web.getType()}))),await page.locator('#browser-error').textContent());
  assert.ok(web,'Embedded browser did not navigate');
  await web.locator('#card').waitFor();
  const startup=await web.evaluate(()=>({bootWidth:window.bootWidth,width:innerWidth}));
  assert.ok(startup.bootWidth>=1279,`Desktop layout must apply before page scripts: ${JSON.stringify(startup)}`);
  assert.equal(await page.locator('#browser-resizer').count(),1,'The preview needs a draggable divider');
  const panelWidth=()=>page.locator('#browser-panel').evaluate(e=>e.getBoundingClientRect().width);
  await page.locator('#sidebar-toggle').click();
  const initialWidth=await panelWidth(),divider=await page.locator('#browser-resizer').boundingBox();
  const nativeView=()=>app.evaluate(({BrowserWindow})=>{const window=BrowserWindow.getAllWindows()[0],view=window.contentView.children.find(child=>child.webContents&&child.webContents!==window.webContents);return{visible:view.getVisible(),bounds:view.getBounds()};});
  async function waitNativeVisible(){const end=Date.now()+5000;while(Date.now()<end){if((await nativeView()).visible)return;await new Promise(resolve=>setTimeout(resolve,50));}throw Error('The native preview did not become visible after loading');}
  await page.mouse.move(divider.x+divider.width/2,divider.y+divider.height/2);await page.mouse.down();await page.mouse.move(divider.x-110,divider.y+divider.height/2,{steps:8});assert.equal((await nativeView()).visible,false,'Native preview cannot steal pointer during resize');await page.mouse.up();
  assert.ok(await panelWidth()>initialWidth+90,'Dragging left expands the browser');
  await page.waitForTimeout(120);assert.equal((await nativeView()).visible,true,'Preview returns after resize');
  const viewport=await page.locator('#browser-viewport').boundingBox(),native=(await nativeView()).bounds;assert.ok(Math.abs(viewport.x-native.x)<=1&&Math.abs(viewport.width-native.width)<=1,'Native browser follows the divider');
  await page.evaluate(url=>{window.slowNavigation=window.muse.browserCommand('navigate',{url});},url+'/slow-resize');await waitForCondition(page,async()=>(await window.muse.browserCommand('state')).loading);
  const loadingDivider=await page.locator('#browser-resizer').boundingBox();await page.mouse.move(loadingDivider.x+3,loadingDivider.y+100);await page.mouse.down();await page.mouse.move(loadingDivider.x+70,loadingDivider.y+100,{steps:4});await page.mouse.up();
  assert.equal((await nativeView()).visible,false,'Finishing a resize cannot reveal the oversized loading surface');await page.evaluate(()=>window.slowNavigation);await waitForCondition(page,async()=>!(await window.muse.browserCommand('state')).loading);await waitNativeVisible();assert.equal((await nativeView()).visible,true);
  await page.evaluate(url=>window.muse.browserCommand('navigate',{url}),url);await web.locator('#card').waitFor();
  const savedWidth=await panelWidth();await page.reload();await page.locator('#browser-panel').waitFor();
  assert.ok(Math.abs(await panelWidth()-savedWidth)<2,'Preview width survives reload');assert.equal(await page.locator('.sidebar').isVisible(),false);
  await page.locator('#browser-resizer').focus();await page.keyboard.press('ArrowRight');assert.ok(await panelWidth()<savedWidth,'Arrow keys resize the preview');
  const beforeCancel=await panelWidth(),cancelDivider=await page.locator('#browser-resizer').boundingBox();
  await page.mouse.move(cancelDivider.x+3,cancelDivider.y+100);await page.mouse.down();await page.mouse.move(cancelDivider.x+90,cancelDivider.y+100,{steps:6});await page.keyboard.press('Escape');await page.mouse.up();assert.ok(Math.abs(await panelWidth()-beforeCancel)<2,'Escape cancels a resize');
  await page.locator('#browser-expand').click();assert.equal(await page.locator('#browser-resizer').isVisible(),false);await page.locator('#browser-expand').click();assert.ok(Math.abs(await panelWidth()-beforeCancel)<2,'Back to chat restores the split width');
  await page.locator('#browser-resizer').focus();await page.keyboard.press('End');assert.ok(await page.locator('main').evaluate(e=>e.getBoundingClientRect().width)>=399,'Resizing leaves usable chat space');await page.keyboard.press('Home');assert.equal(await panelWidth(),390);
  await page.keyboard.press('ArrowLeft');await page.screenshot({path:'artifacts/workspace-resized.png'});
  await page.locator('#browser-resizer').dblclick();await page.locator('#sidebar-toggle').click();
  await page.waitForTimeout(150);
  // Device emulation scales the native surface; Playwright locator clicks use
  // unscaled DOM coordinates. Send pointer input at the displayed position.
  async function point(x,y){const width=await app.evaluate(({BrowserWindow})=>{const window=BrowserWindow.getAllWindows()[0];return window.contentView.children.find(child=>child.webContents && child.webContents!==window.webContents).getBounds().width;});const scale=width/await web.evaluate(()=>innerWidth);return{x:x*scale,y:y*scale};}
  async function clickWeb(selector,position={x:5,y:5}){const rect=await web.locator(selector).evaluate(element=>{const r=element.getBoundingClientRect();return{x:r.x,y:r.y};});const p=await point(rect.x+position.x,rect.y+position.y);await app.evaluate(({BrowserWindow},p)=>{const window=BrowserWindow.getAllWindows()[0],web=window.contentView.children.find(child=>child.webContents && child.webContents!==window.webContents).webContents;for(const type of ['mouseMove','mouseDown','mouseUp'])web.sendInputEvent({type,x:Math.round(p.x),y:Math.round(p.y),button:'left',clickCount:1});},p);}
  async function selectedImageSize(){return web.evaluate(()=>{const rect=document.querySelector("[data-muse-annotation]").getBoundingClientRect();return{width:Math.round(rect.width),height:Math.round(rect.height)};});}
  async function assertSelectedImage(expected,label){
    const actual=await page.locator('#attachments img').evaluate(image=>({width:image.naturalWidth,height:image.naturalHeight}));
    assert.ok(Math.abs(actual.width-expected.width)<=3 && Math.abs(actual.height-expected.height)<=3,`${label} must attach only the selected area: expected ${JSON.stringify(expected)}, got ${JSON.stringify(actual)}`);
    const frame=await app.evaluate(({nativeImage},src)=>{
      const image=nativeImage.createFromDataURL(src),size=image.getSize(),pixels=image.toBitmap();let blue=0;
      // Inspect the antialiased selection border, not just the PNG dimensions.
      for(let index=0;index<Math.min(pixels.length,size.width*3*4);index+=4)
        if(pixels[index]>220 && pixels[index+1]>90 && pixels[index+1]<240 && pixels[index+2]<210 && pixels[index]-pixels[index+2]>35)blue++;
      return blue;
    },await page.locator('#attachments img').getAttribute('src'));
    assert.ok(frame>5,`${label} must crop at the marked frame, not a similarly sized empty area`);
  }
  assert.equal(await web.evaluate(()=>typeof window.muse),'undefined');
  assert.equal(await web.evaluate(()=>typeof require),'undefined');
  await page.evaluate(()=>window.muse.browserCommand('annotate',{mode:'element'}));
  await clickWeb('#link');
  await page.locator('#browser-selection').filter({hasText:'#link'}).waitFor();
  assert.equal(web.url(),url+'/','Annotation click must not navigate');
  const desktopCrop=await selectedImageSize();
  await page.locator('#browser-add').click();
  await page.locator('.attachment-context').waitFor();
  assert.match(await page.locator('.attachment-context').textContent(),/#link/);
  assert.match(await page.locator('.attachment-context').textContent(),/User note: \(none\)/);
  assert.equal(await page.locator('#attachments img').count(),1);
  await page.waitForFunction(()=>document.querySelector('#attachments img')?.naturalWidth>0);await assertSelectedImage(desktopCrop,'Desktop element');
  await writeFile('artifacts/browser-selected-element.png',Buffer.from((await page.locator('#attachments img').getAttribute('src')).split(',')[1],'base64'));
  await page.locator('.attachment button[aria-label="Remove image"]').click();
  assert.equal(await page.locator('.attachment-context').count(),0);
  await page.evaluate(()=>window.muse.browserCommand('annotate',{mode:'element'}));
  await clickWeb('#card',{x:8,y:8});
  await page.locator('#browser-selection').filter({hasText:'#card'}).waitFor();
  const hiddenSelection=await app.evaluate(({webContents})=>webContents.getAllWebContents().find(web=>web.getURL().startsWith('http:')).executeJavaScriptInIsolatedWorld(117,[{code:"document.getElementById('card').style.display='none';globalThis.__museAnnotation.read(true)"}]));
  assert.equal(hiddenSelection.selection,null,'Capture refresh must invalidate an element that just became hidden');
  await assert.rejects(page.evaluate(()=>window.muse.browserCommand('capture',{note:''})));
  await web.locator('#card').evaluate(element=>{element.style.display='';});
  await page.evaluate(()=>window.muse.browserCommand('annotate',{mode:'element'}));
  await clickWeb('#card',{x:8,y:8});
  await page.locator('#browser-selection').filter({hasText:'#card'}).waitFor();
  await web.locator('#card h1').evaluate(element=>{element.textContent='Updated heading before capture';});
  await page.locator('#browser-add').click();
  const context=await page.locator('.attachment-context').textContent();
  assert.match(context,/Updated heading before capture/);assert.doesNotMatch(context,/private-form-value|onclick|<script/);
  await page.getByRole('textbox',{name:'Note for selection 1'}).fill('Make this card blue');
  assert.equal(await page.locator('.annotation-source').textContent(),url+'/');
  if(!realSend) await app.evaluate(({ipcMain})=>{
    globalThis.browserSmokePayload=null;
    ipcMain.removeHandler('muse:send');
    ipcMain.handle('muse:send',(_event,payload)=>{globalThis.browserSmokePayload=payload;return{queued:true};});
  });
  const question=realSend ? 'How can we improve this card? This is a browser annotation integration test, no tools or file changes. Reply in one short sentence starting BROWSER_OK and include the heading shown in the selected HTML/image.' : 'How can we improve this card?';
  if(realSend){await page.locator('#connection-badge').filter({hasText:'Connected'}).waitFor();await page.evaluate(()=>window.muse.setOptions({reasoningEffort:'minimal',executionMode:'readonly'}));}
  await page.locator('#prompt').fill(question);
  await page.locator('#send-button').click();
  let sent;
  if(realSend){
    const deadline=Date.now()+120000;let state;
    do{state=await page.evaluate(()=>window.muse.getState());if(!state.busy && state.items.some(item=>item.kind==='agentMessage' && item.text))break;await new Promise(resolve=>setTimeout(resolve,100));}while(Date.now()<deadline);
    assert.equal(state.busy,false);assert.equal(state.error,'');
    assert.match(state.items.filter(item=>item.kind==='agentMessage').map(item=>item.text).join('\n'),/BROWSER_OK/);
    const user=state.items.find(item=>item.kind==='userMessage');sent={text:user.text,images:user.images};
    console.log('PASS real Muse general chat: annotation HTML and PNG accepted, contextual answer returned');
  }else {await page.waitForFunction(()=>document.querySelector('#prompt').value==='');sent=await app.evaluate(()=>globalThis.browserSmokePayload);}
  assert.match(sent.text,/How can we improve this card\?/);assert.match(sent.text,/#card/);assert.match(sent.text,/Updated heading before capture/);
  assert.equal(sent.images[0].mediaType,'image/png');
  assert.match(sent.text,/Selection 1.*Make this card blue/);
  await writeFile('artifacts/browser-annotation-proof.png',Buffer.from(sent.images[0].base64Data,'base64'));
  await page.evaluate(()=>window.muse.browserCommand('annotate',{mode:'region'}));
  const start=await point(42,42),end=await point(250,180);
  await web.mouse.move(start.x,start.y);await web.mouse.down();await web.mouse.move(end.x,end.y);await web.mouse.up();
  await page.locator('#browser-selection').filter({hasText:'Region'}).waitFor();
  const regionCrop=await selectedImageSize();
  await page.locator('#browser-add').click();await page.locator('.attachment-context').waitFor();
  await page.waitForFunction(()=>document.querySelector('#attachments img')?.naturalWidth>0);await assertSelectedImage(regionCrop,'Dragged region');
  await writeFile('artifacts/browser-selected-region.png',Buffer.from((await page.locator('#attachments img').getAttribute('src')).split(',')[1],'base64'));
  await page.locator('.attachment button[aria-label="Remove image"]').click();
  await page.evaluate(()=>window.muse.browserCommand('annotate',{mode:'region'}));
  await web.mouse.move(start.x,start.y);await web.mouse.down();await web.mouse.move(end.x,end.y);await web.mouse.up();
  await page.locator('#browser-selection').filter({hasText:'Region'}).waitFor();
  await web.evaluate(()=>history.pushState({},'','#section'));
  await page.waitForFunction(()=>document.getElementById('browser-add').disabled);
  assert.equal(await web.locator('[data-muse-annotation]').count(),0);
  await page.evaluate(()=>window.muse.browserCommand('annotate',{mode:'element'}));await web.keyboard.press('Escape');
  await page.locator('#browser-selection').filter({hasText:'Point to edit, save notes, then send together.'}).waitFor();
  assert.equal(await page.locator('#browser-cancel').isDisabled(),true);
  await web.evaluate(url=>{const frame=document.createElement('iframe');frame.id='frame';frame.src=url+'/frame';frame.style.cssText='position:fixed;left:40px;top:40px;width:300px;height:260px';document.body.append(frame);},url);
  const child=await web.locator('#frame').contentFrame();await child.locator('#link').waitFor();
  await web.evaluate(()=>{const modal=document.createElement('div');modal.id='modal';modal.textContent='Overlay above iframe';modal.style.cssText='position:fixed;left:50px;top:50px;width:200px;height:80px;z-index:10000;background:white';document.body.append(modal);});
  await page.evaluate(()=>window.muse.browserCommand('annotate',{mode:'element'}));await clickWeb('#modal',{x:30,y:30});
  await page.locator('#browser-selection').filter({hasText:'#modal'}).waitFor({timeout:1500});
  await clickControl(page,'browser-cancel');await web.locator('#modal').evaluate(element=>element.remove());
  const frameLink=await child.locator('#link').boundingBox();
  await page.evaluate(()=>window.muse.browserCommand('annotate',{mode:'element'}));
  const framePoint=await point(frameLink.x+5,frameLink.y+5);await web.mouse.click(framePoint.x,framePoint.y);
  await page.locator('#browser-selection').filter({hasText:'#frame'}).waitFor({timeout:1500});
  assert.equal(web.frames().find(frame=>frame.url()===url+'/frame')?.url(),url+'/frame','Annotation must not activate links inside an iframe');
  await page.locator('#browser-add').click();await page.locator('.attachment-context').waitFor();
  assert.match(await page.locator('.attachment-context').textContent(),/<iframe/);
  await page.locator('.attachment button[aria-label="Remove image"]').click();
  await web.locator('#frame').evaluate(element=>element.remove());
  await page.locator('#browser-url').fill(url+'/next');await page.locator('#browser-url').press('Enter');
  await web.waitForURL(url+'/next');
  assert.equal(await page.locator('#browser-add').isDisabled(),true);
  await assert.rejects(page.evaluate(()=>window.muse.browserCommand('navigate',{url:'file:///C:/secret'})));
  assert.equal((await page.evaluate(()=>window.muse.getState())).error,'','Browser address errors must not mark the engine conversation as failed');
  const appState=await page.evaluate(()=>window.muse.getState());
  await app.evaluate(({BrowserWindow},state)=>BrowserWindow.getAllWindows()[0].webContents.send('muse:event',{type:'state',state:{...state,items:[{itemId:'browser-review-test',kind:'fileChanges',files:[{path:'design.html',patch:'+design'}],added:1,removed:0}]}}),appState);
  await page.locator('.change-badge').click();await page.locator('.changes-panel').waitFor();
  const viewInfo=()=>app.evaluate(({BrowserWindow})=>{const window=BrowserWindow.getAllWindows()[0];const view=window.contentView.children.find(child=>child.webContents && child.webContents!==window.webContents);return{visible:view.getVisible(),bounds:view.getBounds()};});
  await page.waitForTimeout(150);
  assert.equal((await viewInfo()).visible,false,'Native browser must not cover the file diff panel');
  await page.locator('.changes-close').click();await page.waitForTimeout(150);
  assert.equal((await viewInfo()).visible,true);
  await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].webContents.setZoomFactor(1.2));
  await page.waitForTimeout(300);
  const uiRect=await page.locator('#browser-viewport').evaluate(element=>{const rect=element.getBoundingClientRect();return{x:rect.x,y:rect.y,width:rect.width,height:rect.height};});
  const nativeRect=(await viewInfo()).bounds;
  for(const field of ['x','y','width','height'])assert.ok(Math.abs(nativeRect[field]-uiRect[field]*1.2)<=2,`${field} does not match the zoomed browser viewport`);
  for(const zoom of [.8,1.25]){
  await app.evaluate(({webContents},zoom)=>webContents.getAllWebContents().find(web=>web.getURL().startsWith('http:')).setZoomFactor(zoom),zoom);
  await web.locator('#card').evaluate(element=>{element.style.cssText='position:fixed;right:5px;top:20px;width:60px;height:60px;padding:0;overflow:hidden;';});
  await page.evaluate(()=>window.muse.browserCommand('annotate',{mode:'element'}));await clickWeb('#card');
  await page.locator('#browser-selection').filter({hasText:'#card'}).waitFor();
  const zoomCrop=await selectedImageSize();
  await page.locator('#browser-add').click();await page.locator('.attachment-context').waitFor({timeout:3000});
  await writeFile('artifacts/browser-selected-zoom.png',Buffer.from((await page.locator('#attachments img').getAttribute('src')).split(',')[1],'base64'));
  await page.waitForFunction(()=>document.querySelector('#attachments img')?.naturalWidth>0);await assertSelectedImage(zoomCrop,'App/page zoom');
  await page.locator('.attachment button[aria-label="Remove image"]').click();
  }
  await app.evaluate(({BrowserWindow,webContents})=>{BrowserWindow.getAllWindows()[0].webContents.setZoomFactor(1);webContents.getAllWebContents().find(web=>web.getURL().startsWith('http:')).setZoomFactor(1);});
  await web.locator('#card').evaluate(element=>{element.style.cssText='';});
  await web.evaluate(()=>window.previewMarker='same-page');
  await page.locator('#browser-mobile').click();
  await web.waitForFunction(()=>innerWidth===390);
  assert.equal(await web.locator('#card').evaluate(element=>getComputedStyle(element).color),'rgb(0, 128, 0)','Mobile must activate responsive CSS');
  await page.evaluate(async()=>{const rect=document.getElementById('browser-viewport').getBoundingClientRect();await window.muse.browserCommand('bounds',{x:rect.x,y:rect.y,width:rect.width,height:rect.height});});
  await page.evaluate(()=>window.muse.browserCommand('annotate',{mode:'element'}));await clickWeb('#link');
  await page.locator('#browser-selection').filter({hasText:'#link'}).waitFor();
  await page.locator('#browser-desktop').click();
  await web.waitForFunction(()=>innerWidth>=1279);
  assert.equal(await page.locator('#browser-add').isDisabled(),true,'Changing viewport must invalidate selection');
  assert.equal(await web.locator('#card').evaluate(element=>getComputedStyle(element).color),'rgb(24, 77, 160)');
  assert.equal(await web.evaluate(()=>window.previewMarker),'same-page','Changing viewport must preserve page/login state');
  await page.locator('#browser-expand').click();
  await page.waitForFunction(()=>document.body.classList.contains('browser-expanded'));
  await page.waitForTimeout(200);
  assert.ok(await page.locator('#browser-panel').evaluate(element=>element.getBoundingClientRect().width/innerWidth)>.95,'Expanded browser must fill the app');
  await page.screenshot({path:'artifacts/browser-desktop-preview.png'});
  await writeFile('artifacts/browser-desktop-page.png',Buffer.from(await app.evaluate(({webContents})=>webContents.getAllWebContents().find(web=>web.getURL().startsWith('http:')).capturePage().then(image=>image.toPNG().toString('base64'))),'base64'));
  await page.locator('#browser-mobile').click();await web.waitForFunction(()=>innerWidth===390);
  await page.waitForTimeout(200);await page.screenshot({path:'artifacts/browser-mobile-preview.png'});
  await writeFile('artifacts/browser-mobile-page.png',Buffer.from(await app.evaluate(({webContents})=>webContents.getAllWebContents().find(web=>web.getURL().startsWith('http:')).capturePage().then(image=>image.toPNG().toString('base64'))),'base64'));
  await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].webContents.setZoomFactor(1.2));await page.waitForTimeout(250);
  await page.evaluate(()=>window.muse.browserCommand('annotate',{mode:'element'}));await clickWeb('#link');
  await page.locator('#browser-selection').filter({hasText:'#link'}).waitFor();
  const mobileCrop=await selectedImageSize();
  await page.locator('#browser-add').click();await page.locator('.attachment-context').waitFor();
  assert.match(await page.locator('.attachment-context').textContent(),/#link/);
  assert.match(await page.locator('.attachment-context').textContent(),/Screenshot: cropped to this selection/);
  await page.waitForFunction(()=>document.querySelector('#attachments img')?.naturalWidth>0);await assertSelectedImage(mobileCrop,'Expanded Mobile element');
  assert.equal(await page.evaluate(()=>document.body.classList.contains('browser-expanded')),false,'Adding an annotation must return to the main chat');
  assert.equal(await page.locator('#prompt').evaluate(element=>element===document.activeElement),true);
  await page.locator('.attachment button[aria-label="Remove image"]').click();
  await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].webContents.setZoomFactor(1));await page.waitForTimeout(250);
  await web.evaluate(()=>{document.body.style.minHeight='4000px';scrollTo(0,100);});await page.waitForTimeout(150);
  await page.evaluate(()=>window.muse.browserCommand('annotate',{mode:'element'}));await clickWeb('#link');await page.locator('#browser-selection').filter({hasText:'#link'}).waitFor();
  const scrolledCrop=await selectedImageSize();await page.locator('#browser-add').click();await page.locator('.attachment-context').waitFor();
  await page.waitForFunction(()=>document.querySelector('#attachments img')?.naturalWidth>0);await assertSelectedImage(scrolledCrop,'Scrolled Mobile element');
  await writeFile('artifacts/browser-selected-scrolled.png',Buffer.from((await page.locator('#attachments img').getAttribute('src')).split(',')[1],'base64'));
  await page.locator('#browser-url').fill(url+'/slow');await page.locator('#browser-url').press('Enter');
  await waitForCondition(page,async()=>(await window.muse.browserCommand('state')).loading);
  assert.equal(await page.locator('#browser-desktop').isDisabled(),true,'Device changes must wait for the new page to load');
  await assert.rejects(page.evaluate(()=>window.muse.browserCommand('device',{mode:'desktop'})),/page.*load/i);
  await page.waitForFunction(()=>!document.getElementById('browser-mobile').disabled);
  assert.equal(await web.evaluate(()=>window.bootWidth),390);
  await app.evaluate(({webContents})=>webContents.getAllWebContents().find(web=>web.getURL().startsWith('http:')).forcefullyCrashRenderer());
  await page.locator('#browser-error').filter({hasText:'Page stopped responding'}).waitFor();
  assert.equal(await page.locator('#browser-desktop').isDisabled(),true,'A stopped renderer must be reloaded before changing viewport');
  await app.evaluate(({BrowserWindow})=>{const window=BrowserWindow.getAllWindows()[0];const [width,height]=window.getSize();window.setSize(width+30,height);});
  await page.waitForTimeout(200);assert.equal(page.isClosed(),false,'A crashed web page must not close Mora Desktop');
  await page.locator('#browser-reload').click();
  let recovered;const recoveryDeadline=Date.now()+10000;
  do{try{recovered=await app.evaluate(({webContents})=>webContents.getAllWebContents().find(web=>web.getURL().startsWith('http:')).executeJavaScript('({bootWidth:window.bootWidth,hasCard:!!document.getElementById("card")})'));}catch{}if(recovered?.hasCard)break;await new Promise(resolve=>setTimeout(resolve,100));}while(Date.now()<recoveryDeadline);
  assert.equal(recovered?.hasCard,true,'Reload must recover a crashed browser without restarting Muse');
  assert.equal(recovered.bootWidth,390,'Reload after a page crash must retain the mobile viewport at boot');
  await clickControl(page,'browser-before');
  await page.waitForFunction(()=>document.querySelector('#browser-after')?.disabled===false);
  await app.evaluate(({webContents})=>webContents.getAllWebContents().find(web=>web.getURL().startsWith('http:')).executeJavaScript('document.getElementById("card").style.background="pink"'));
  await clickControl(page,'browser-after');
  await page.locator('.comparison-viewer').waitFor();
  assert.equal(await page.locator('.comparison-viewer img').count(),2);
  assert.match(await page.locator('.comparison-viewer').textContent(),/Visual comparison.*does not verify/i);
  await page.getByRole('button',{name:'Close comparison',exact:true}).click();
  assert.equal(await page.locator('#browser-mobile').getAttribute('aria-pressed'),'true');
  await page.locator('#browser-desktop').click();
  await assert.rejects(page.evaluate(()=>window.muse.browserCommand('compare-after')),/capture before again/i);
  await clickControl(page,'browser-close');
  assert.equal(await page.locator('#browser-panel').isVisible(),false);
  console.log('PASS browser: Desktop/Mobile viewport, cropped element/region PNG and HTML, scrolling, app/page zoom, expansion, isolation and renderer-crash recovery');
} finally {await app.close();await new Promise(resolve=>server.close(resolve));}
