import {createRequire} from 'node:module';
import {createServer} from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
import path from 'node:path';
const require=createRequire(import.meta.url);
const {chromium}=require('./runtime-packages.cjs').runtimeRequire('playwright');
const png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+ip1sAAAAASUVORK5CYII=';
const server=createServer(async(req,res)=>{
  const file={'/':'index.html','/style.css':'style.css','/renderer.js':'renderer.js','/markdown.js':'markdown.js','/project-ui.js':'project-ui.js','/work-ui.js':'work-ui.js','/images.js':'images.js','/projects.js':'projects.js','/browser-ui.js':'browser-ui.js','/video-frames.js':'video-frames.js','/usage.js':'usage.js','/assets/mora-mark.svg':'assets/mora-mark.svg'}[req.url];
  if(!file){res.writeHead(404).end();return;}
  res.setHeader('Content-Type',file.endsWith('.svg')?'image/svg+xml':file.endsWith('.css')?'text/css':file.endsWith('.js')?'application/javascript':'text/html');
  res.end(await readFile(path.join('src',file)));
});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const browser=await chromium.launch({channel:'msedge',headless:true});
try{
 const page=await browser.newPage({viewport:{width:1200,height:820}});
 await page.addInitScript(({png})=>{
  let state={items:[],sessions:[],models:[{modelId:'muse-test',displayLabel:'Muse test',variants:['minimal','max']}],modelId:'muse-test',reasoningEffort:'max',executionMode:'readonly',workspace:'C:\\Test',connection:'ready',engineVersion:'fixture',busy:false,pendingQueue:[]};
  let callback;window.smoke={projectActions:[],restores:[],accountActions:[],projectsCreated:[],trelloActions:[],stopCalls:0,failDraft:false,sent:[],copied:'',deleted:[],removed:[],renamed:[],created:[],emit:next=>{state={...state,...next};callback?.({type:'state',state});}};
  window.muse={projectCommand:async action=>{window.smoke.projectActions.push(action);},checkpointCommand:async(action,payload)=>{if(action==='list')return [{id:'cp1',label:'Before request',fileCount:1,createdAt:new Date().toISOString(),manual:false}];if(action==='preview')return {token:'token',checkpoint:{label:'Before request',manual:false},changes:[{path:'app.js',status:'restore original',conflict:true}]};if(action==='restore'){window.smoke.restores.push(payload);return {restored:1};}},chooseProjectParent:async()=> 'C:\\Projects',createProject:async payload=>{window.smoke.projectsCreated.push(payload);return state;},accountCommand:async action=>{window.smoke.accountActions.push(action);window.smoke.emit({account:action==='login'?{status:'pending',message:'Approve the code',userCode:'DEMO-CODE'}:{status:'required',message:'Sign in required'}});},getState:async()=>state,onEvent:cb=>{callback=cb;return()=>{}},copyText:async text=>{window.smoke.copied=text},setOptions:async options=>{state={...state,...options};return state},pickImages:async()=>[{mediaType:'image/png',base64Data:png,name:'image.png'}],newChat:async projectPath=>{window.smoke.created.push(projectPath);return state},resumeChat:async()=>state,deleteChat:async id=>{window.smoke.deleted.push(id);return state},removeProject:async projectPath=>{window.smoke.removed.push(projectPath);return state},renameChat:async (id,title)=>{window.smoke.renamed.push([id,title]);return state},chooseWorkspace:async()=>state,chooseMuse:async()=>state,connect:async()=>state,trelloCommand:async (action,payload)=>{window.smoke.trelloActions.push([action,payload?.board]);if(action==='state'||action==='disconnect')return {configured:false};return {configured:true,verified:true,keyOnly:action==='test',boardName:'Demo board',boardUrl:'https://trello.com/b/demo',listCount:3,username:'demo-user'};},stopTurn:async()=>{window.smoke.stopCalls++;window.smoke.emit({busy:false,stopping:false,queuePaused:true});},sendMessage:async value=>{window.smoke.sent.push(value);return{accepted:true}},saveDraft:async value=>{if(window.smoke.failDraft)throw new Error('Disk save failed');window.smoke.draft=value;},queueCommand:async action=>{if(action==='clear')window.smoke.emit({pendingQueue:[]});return state;},usageCommand:async()=>{window.smoke.usageCalls=(window.smoke.usageCalls||0)+1;return {tier:'pro',window:{usedPercent:34,resetsAtMs:Date.now()+3720000,windowDurationMins:300},weekly:{usedPercent:9,resetsAtMs:Date.now()+172800000},observedAtMs:Date.now()};}};
 },{png});
 await page.goto(`http://127.0.0.1:${server.address().port}`);
 assert.equal(await page.title(),'Mora Desktop');
 assert.equal(await page.locator('.brand strong').textContent(),'Mora');
 await page.setViewportSize({width:1200,height:500});
 await page.locator('#settings-button').click();
 assert.equal(await page.evaluate(()=>getComputedStyle(document.querySelector('#settings-panel')).overflowY),'auto');
 await page.evaluate(()=>{const p=document.querySelector('#settings-panel');p.scrollTop=p.scrollHeight;});
 assert.equal(await page.evaluate(()=>document.querySelector('#settings-panel').scrollTop>0),true);
 assert.equal(await page.locator('#trello-disconnect').isVisible(),true);
 await page.locator('#settings-button').click();
 await page.setViewportSize({width:1200,height:820});
 await page.waitForFunction(()=>[...document.querySelectorAll('.brand-mark,.welcome-emblem')].every(img=>img.complete&&img.naturalWidth>0));
 assert.equal(await page.locator('#create-project svg').count(),1);
 assert.equal(await page.evaluate(()=>{const a=getComputedStyle(document.querySelector('#new-chat')),b=getComputedStyle(document.querySelector('#create-project'));return a.backgroundColor===b.backgroundColor&&a.borderRadius===b.borderRadius&&a.borderColor===b.borderColor&&a.fontSize===b.fontSize;}),true);
 await page.evaluate(()=>window.smoke.emit({sessionId:'missing-history',error:'The original engine log is missing.',historyMissing:true}));
 await page.locator('#dismiss-error').click();
 await page.evaluate(()=>window.smoke.emit({engineVersion:'state update'}));
 assert.equal(await page.locator('#error-banner').isVisible(),false);
 await page.evaluate(()=>window.smoke.emit({sessionId:'normal-general',projectPath:null,error:'',historyMissing:false}));
 assert.equal(await page.locator('#error-banner').isVisible(),false);
 await page.locator('#prompt').fill('Follow up');
 assert.equal(await page.locator('#send-button').isEnabled(),true);
 await page.locator('#prompt').fill('');
 await page.evaluate(()=>window.smoke.emit({error:'Muse exited (1) before completing the request.'}));
 await page.locator('#dismiss-error').click();
 await page.evaluate(()=>{window.smoke.emit({error:'',busy:true});window.smoke.emit({busy:false,error:'Muse exited (1) before completing the request.'});});
 assert.equal(await page.locator('#error-banner').isVisible(),true);
 await page.evaluate(()=>window.smoke.emit({error:''}));
 await page.evaluate(()=>window.smoke.emit({projectPath:null,projects:['C:\\Muse','C:\\ExampleProject'],sessions:[
  {sessionId:'g',title:'General question',projectPath:null,workspace:'C:\\Profile\\general-chat'},
  {sessionId:'m',title:'Develop Muse',workspace:'C:\\Muse'},
  {sessionId:'s',title:'Explain the project',workspace:'C:\\ExampleProject'},
 ]}));
 assert.equal(await page.locator('#general-sessions .session-row').count(),1);
 assert.equal(await page.locator('.project-group').count(),2);
 assert.equal(await page.locator('.project-group').first().locator('.session-button').textContent(),'Develop Muse');
 await page.evaluate(()=>{document.querySelector('.project-group summary').click();window.smoke.emit({engineVersion:'streaming update'});});
 assert.equal(await page.locator('.session-row[data-session-id="m"]').isVisible(),false);
 await page.locator('.project-group').first().locator('summary').click();
 await page.locator('.project-group').first().locator('summary').click();
 assert.equal(await page.locator('.session-row[data-session-id="m"]').isVisible(),false);
 await page.locator('.project-group').first().locator('summary').click();
 await page.getByRole('button',{name:'New chat in Muse',exact:true}).click();
 assert.equal(await page.evaluate(()=>window.smoke.created.at(-1)),'C:\\Muse');
 assert.equal(await page.locator('.project-group .project-remove').count(),2);
 const projectRemove=page.locator('.project-group').first().locator('.project-remove');
 await page.locator('.project-group').first().locator('summary').hover();
 await projectRemove.click();
 assert.equal(await page.evaluate(()=>window.smoke.removed.length),0);
 assert.equal(await projectRemove.evaluate(el=>el.classList.contains('confirm')),true);
 await projectRemove.click();
 await page.waitForFunction(()=>window.smoke.removed.length===1);
 assert.equal(await page.evaluate(()=>window.smoke.removed[0]),'C:\\Muse');
 await page.locator('#new-chat').click();
 assert.equal(await page.evaluate(()=>window.smoke.created.at(-1)),null);
 assert.equal(await page.locator('#project-name').textContent(),'General chat');
 assert.equal(await page.locator('#execution-mode').isVisible(),false);
 await page.locator('#settings-button').click();
 assert.equal(await page.locator('#trello-settings').isVisible(),true);
 assert.equal(await page.locator('#trello-test').isDisabled(),true);
 await page.locator('#trello-key').fill('pastapikey12345678');
 await page.locator('#trello-token').fill('pasttoken12345678');
 await page.locator('#trello-board').fill('https://trello.com/b/abc12345/demo');
 assert.equal(await page.locator('#trello-test').isDisabled(),false);
 await page.locator('#trello-test').click();
 await page.waitForFunction(()=>document.querySelector('#trello-status').textContent.includes('Demo board'));
 assert.match(await page.locator('#trello-status').textContent(),/Demo board.*3 lists.*press Connect to save/);
 await page.locator('#trello-connect').click();
 await page.waitForFunction(()=>document.querySelector('#trello-key').value==='' && !document.querySelector('#trello-status').textContent.includes('press Connect'));
 assert.equal(await page.locator('#trello-board').inputValue(),'https://trello.com/b/abc12345/demo');
 assert.equal(await page.locator('#trello-disconnect').isDisabled(),false);
 await page.locator('#trello-disconnect').click();
 await page.waitForFunction(()=>document.querySelector('#trello-status').textContent==='Not connected');
 assert.equal(await page.locator('#trello-board').inputValue(),'');
 assert.equal(await page.locator('#trello-disconnect').isDisabled(),true);
 assert.deepEqual(await page.evaluate(()=>window.smoke.trelloActions.map(a=>a[0])),['state','test','connect','disconnect']);
 await page.locator('#settings-button').click();
 await page.screenshot({path:'artifacts/muse-project-groups.png'});
 await page.evaluate(()=>window.smoke.emit({projectPath:'C:\\Test',projects:[],sessions:[]}));
 await page.screenshot({path:'artifacts/mora-welcome.png'});
 await page.locator('#prompt').fill('Hello Mora');
 await page.evaluate(()=>document.querySelector('#prompt').dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',isComposing:true,bubbles:true,cancelable:true})));
 assert.equal(await page.evaluate(()=>window.smoke.sent.length),0);
 await page.locator('#prompt').press('Shift+Enter');
 assert.match(await page.locator('#prompt').inputValue(),/\n/);
 await page.locator('#attach-button').click();
 assert.equal(await page.locator('.attachment').count(),1);
 await page.evaluate(({png})=>{const bytes=Uint8Array.from(atob(png),c=>c.charCodeAt(0));const data=new DataTransfer();data.items.add(new File([bytes],'pasted.png',{type:'image/png'}));document.querySelector('#prompt').dispatchEvent(new ClipboardEvent('paste',{clipboardData:data,bubbles:true,cancelable:true}));},{png});
 await page.waitForFunction(()=>document.querySelectorAll('.attachment').length===2);
 await page.locator('#prompt').press('Enter');
 await page.waitForFunction(()=>window.smoke.sent.length===1);
 assert.equal(await page.evaluate(()=>window.smoke.sent[0].images.length),2);
 assert.match(await page.evaluate(()=>window.smoke.sent[0].text),/Hello Mora/);
 await page.waitForFunction(()=>document.querySelector('#prompt').value==='');
 await page.evaluate(()=>window.smoke.emit({items:[{itemId:'a',kind:'agentMessage',revision:1,status:'completed',text:'<img src=x onerror="window.pwned=1">\n```js\nconsole.log(42);\n```'}]}));
 assert.equal(await page.evaluate(()=>window.pwned),undefined);
 assert.equal(await page.locator('.message-body img').count(),0);
 await page.waitForFunction(()=>document.querySelector('.message.assistant .avatar img')?.naturalWidth>0);
 await page.screenshot({path:'artifacts/mora-message.png'});
 await page.locator('.code-header button').click();
 assert.equal(await page.evaluate(()=>window.smoke.copied),'console.log(42);\n');
 await page.route('https://lh3.googleusercontent.com/aida/**',route=>route.fulfill({contentType:'image/png',body:Buffer.from(png,'base64')}));
 await page.evaluate(()=>window.smoke.emit({items:[{itemId:'stitch-preview',kind:'agentMessage',status:'completed',text:'The new design\n(https://lh3.googleusercontent.com/aida/fixture-design)\n```text\nhttps://lh3.googleusercontent.com/aida/code-example\n```'}]}));
 assert.equal(await page.locator('.stitch-image img').count(),1,'A plain Stitch output URL must render as an image; code URLs remain literal');
 await page.waitForFunction(()=>document.querySelector('.stitch-image img')?.naturalWidth>0);
 await page.locator('.stitch-image .image-preview-button').click();
 assert.equal(await page.locator('.image-viewer').isVisible(),true);
 await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.querySelector('.image-viewer'));
 await page.evaluate(()=>window.smoke.emit({items:[{itemId:'stitch-preview',kind:'agentMessage',status:'completed',text:'![Card](https://lh3.googleusercontent.com/aida/fixture-design)\n[Design](https://lh3.googleusercontent.com/aida/fixture-design-2)\nhttps://untrusted.example/image.png'}]}));
 assert.equal(await page.locator('.stitch-image img').count(),2);
 assert.match(await page.locator('.message-body').textContent(),/https:\/\/untrusted.example\/image.png/);
 await page.locator('.image-copy-link').first().click();
 assert.equal(await page.evaluate(()=>window.smoke.copied),'https://lh3.googleusercontent.com/aida/fixture-design');
 await page.route('https://lh3.googleusercontent.com/aida/broken',route=>route.abort());
 await page.evaluate(()=>window.smoke.emit({items:[{itemId:'stitch-broken',kind:'agentMessage',status:'completed',text:'https://lh3.googleusercontent.com/aida/broken'}]}));
 await page.locator('.stitch-image figcaption').filter({hasText:'Preview unavailable'}).waitFor();
 assert.equal(await page.locator('.image-preview-button').isVisible(),false);
 assert.equal(await page.locator('.image-copy-link').isVisible(),true);
 await page.evaluate(()=>window.smoke.emit({items:[{itemId:'stitch-code',kind:'agentMessage',status:'inProgress',text:'Before\n```html\nhttps://lh3.googleusercontent.com/aida/code-example\n'}]}));
 assert.equal(await page.locator('.stitch-image').count(),0,'An unfinished streamed code fence must keep image links literal');
 await page.evaluate(()=>window.smoke.emit({items:[{itemId:'stitch-html',kind:'agentMessage',status:'completed',text:'<img src="https://lh3.googleusercontent.com/aida/code-example">'}]}));
 assert.equal(await page.locator('.stitch-image').count(),0,'Raw HTML must stay literal, including image attributes');
 await page.evaluate(()=>window.smoke.emit({items:[{itemId:'stitch-multiline-html',kind:'agentMessage',status:'inProgress',text:'Example:\n<img\n class="design"\n src="https://lh3.googleusercontent.com/aida/code-example"'}]}));
 assert.equal(await page.locator('.stitch-image').count(),0,'Multiline and incomplete HTML tags must also stay literal');
 await page.evaluate(()=>window.smoke.emit({busy:true,items:[{itemId:'b',kind:'toolCall',revision:1,status:'inProgress',tool:'powershell',visibleOutput:'FILE_OK'}]}));
 assert.equal(await page.locator('#workspace-button').isDisabled(),true);
 assert.equal(await page.locator('#model').isDisabled(),true);
 await page.locator('.tool-card summary').click();
 assert.match(await page.locator('.tool-card pre').textContent(),/FILE_OK/);
 await page.evaluate(()=>window.smoke.emit({busy:true,finishing:true,items:[{itemId:'answer',kind:'agentMessage',status:'inProgress',text:'The reply is ready'}]}));
 assert.match(await page.locator('#working-label').textContent(),/Reply ready/);
 assert.equal(await page.locator('#prompt').isEnabled(),true);
 await page.locator('#prompt').fill('Draft the next message');
 await page.locator('#prompt').press('Enter');
 await page.waitForFunction(()=>window.smoke.sent.length===2);
 await page.waitForFunction(()=>document.querySelector('#prompt').value==='');
 await page.evaluate(()=>window.smoke.emit({pendingQueue:[{queueId:'q1',text:'Draft the next message',images:[]}]}));
 await page.waitForFunction(()=>document.querySelectorAll('.queue-badge').length===1);
 assert.equal(await page.locator('.queue-badge').textContent(),'Queued');
 assert.equal(await page.locator('#send-button').isVisible(),true);
 await page.locator('#stop-button').click();
 assert.equal(await page.locator('.queue-badge').count(),1);
 await page.getByRole('button',{name:'Clear queue',exact:true}).click();
 await page.waitForFunction(()=>document.querySelectorAll('.queue-badge').length===0);
 await page.evaluate(()=>window.smoke.emit({busy:true,finishing:false}));
 await page.locator('#stop-button').click();
 await page.waitForFunction(()=>document.querySelector('#stop-button').hidden);
 await page.evaluate(()=>{const data=new DataTransfer();data.items.add(new File([new Uint8Array(10*1024*1024+1)],'huge.png',{type:'image/png'}));document.querySelector('#prompt').dispatchEvent(new ClipboardEvent('paste',{clipboardData:data,bubbles:true,cancelable:true}));});
 await page.waitForFunction(()=>document.querySelector('#error-text').textContent.includes('10 MB'));
 await page.evaluate(()=>window.smoke.emit({sessions:[{sessionId:'s1',title:'First chat',workspace:'C:\\A'},{sessionId:'s2',title:'Second chat',workspace:'C:\\A'}]}));
 await page.waitForFunction(()=>document.querySelectorAll('.session-row').length===2);
 assert.equal(await page.locator('.session-menu-button').count(),0);
 assert.equal(await page.locator('.session-row .session-delete-icon').count(),2);
 const del=page.locator('.session-row[data-session-id="s2"] .session-delete-icon');
 const delOpacity=()=>page.evaluate(()=>getComputedStyle(document.querySelector('.session-row[data-session-id="s2"] .session-delete-icon')).opacity);
 assert.equal(await delOpacity(),'0');
 await page.locator('.session-row[data-session-id="s2"]').hover();
 assert.equal(await delOpacity(),'1');
 await del.click();
 assert.equal(await page.evaluate(()=>window.smoke.deleted.length),0);
 assert.equal(await del.evaluate(el=>el.classList.contains('confirm')),true);
 await del.click();
 await page.waitForFunction(()=>window.smoke.deleted.length===1);
 assert.equal(await page.evaluate(()=>window.smoke.deleted[0]),'s2');
 const renameEdit=page.locator('.session-row[data-session-id="s1"] .session-edit-icon');
 await page.locator('.session-row[data-session-id="s1"]').hover();
 await renameEdit.click();
 const renameInput=page.locator('.session-row[data-session-id="s1"] .session-rename-input');
 assert.equal(await renameInput.inputValue(),'First chat');
 await renameInput.fill('Renamed chat');
 await renameInput.press('Enter');
 await page.waitForFunction(()=>window.smoke.renamed.length===1);
 assert.deepEqual(await page.evaluate(()=>window.smoke.renamed[0]),['s1','Renamed chat']);
 await renameEdit.click();
 await page.locator('.session-row[data-session-id="s1"] .session-rename-input').press('Escape');
 assert.equal(await page.locator('.session-rename-input').count(),0);
 assert.equal(await page.evaluate(()=>window.smoke.renamed.length),1);
 const dropOnComposer=files=>page.evaluate(list=>{const dt=new DataTransfer();for(const f of list){const file=new File([new Uint8Array(f.bytes)],f.name,{type:f.type});if(f.size)Object.defineProperty(file,'size',{value:f.size});dt.items.add(file);}const event=new DragEvent('drop',{bubbles:true});Object.defineProperty(event,'dataTransfer',{value:dt});document.querySelector('#composer').dispatchEvent(event);},files);
 const attachedBefore=await page.locator('.attachment').count();
 await dropOnComposer([{name:'big.mp4',type:'video/mp4',bytes:8,size:101*1024*1024}]);
 await page.waitForFunction(()=>document.querySelector('#error-text').textContent.includes('100 MB'));
 assert.equal(await page.locator('.attachment').count(),attachedBefore);
 await dropOnComposer([{name:'clip.avi',type:'video/avi',bytes:8}]);
 await page.waitForFunction(()=>document.querySelector('#error-text').textContent.includes('MP4, MOV, or WebM'));
 assert.equal(await page.locator('.attachment').count(),attachedBefore);
 await dropOnComposer([{name:'note.txt',type:'text/plain',bytes:5}]);
 await page.waitForTimeout(300);
 assert.equal(await page.title(),'Mora Desktop');
 assert.equal(await page.locator('.attachment').count(),attachedBefore);
 await page.evaluate(()=>{const dt=new DataTransfer();dt.items.add(new File(['x'],'a.png',{type:'image/png'}));const event=new DragEvent('dragover',{bubbles:true});Object.defineProperty(event,'dataTransfer',{value:dt});document.querySelector('#composer').dispatchEvent(event);});
 assert.equal(await page.locator('#composer.dragging').count(),1);
 await page.evaluate(()=>{document.querySelector('#composer').dispatchEvent(new DragEvent('dragleave',{bubbles:true}));});
 assert.equal(await page.locator('#composer.dragging').count(),0);
 await page.evaluate(()=>{window.smoke.realPick=window.muse.pickImages;window.muse.pickImages=async()=>[{mediaType:'image/png',base64Data:'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=',name:'tiny.png'},{mediaType:'video/mp4',base64Data:'AAAA',name:'broken.mp4',size:3}];});
 await page.locator('#attach-button').click();
 await page.waitForFunction(n=>document.querySelectorAll('.attachment').length===n,attachedBefore+1);
 await page.waitForFunction(()=>document.querySelector('#error-text').textContent.includes('could not be read'));
 await page.evaluate(()=>{window.muse.pickImages=window.smoke.realPick;});
 await page.locator('.attachment [aria-label="Remove image"]').last().click();
 await page.waitForFunction(before=>document.querySelectorAll('.attachment').length===before,attachedBefore);
 await page.evaluate(()=>window.smoke.emit({items:[{itemId:'change-test',kind:'fileChanges',added:68,removed:3,files:[{path:'src/feature.js',status:'modified',added:68,removed:3,patch:'@@ -1 +1 @@\n-old value\n+<script>literal text</script>\n context'}]}]}));
 await page.locator('.change-badge').waitFor();
 assert.match(await page.locator('.change-badge').textContent(),/1 file changed.*\+68.*-3/);
 await page.locator('.change-badge').click();
 await page.locator('.changes-panel').waitFor();
 assert.equal(await page.locator('.diff-line.added').textContent(),'+<script>literal text</script>');
 assert.equal(await page.locator('.changes-panel script').count(),0);
 await page.evaluate(()=>window.smoke.emit({busy:true,items:[{itemId:'step',kind:'activity',text:'Preparing the response'},{itemId:'change-test',kind:'fileChanges',live:true,added:2,removed:1,files:[{path:'src/other.js',added:1,removed:0,patch:'+other'},{path:'src/feature.js',added:1,removed:1,patch:'@@ -1 +1 @@\n-old\n+updated live'}]}]}));
 assert.equal(await page.locator('.change-row').count(),0);
 assert.equal(await page.locator('#live-review').isVisible(),true);
 assert.match(await page.locator('#live-review').textContent(),/2 files changed.*\+2.*-1.*Live/);
 assert.equal(await page.locator('.diff-filename').textContent(),'src/feature.js');
 assert.equal(await page.locator('.diff-line.added').textContent(),'+updated live');
 assert.equal(await page.locator('.activity-step').textContent(),'Preparing the response');
 await page.evaluate(()=>window.smoke.emit({items:[{itemId:'change-test',kind:'fileChanges',live:true,added:1,removed:0,files:[{path:'src/feature.js',patch:'+'+'x'.repeat(300)}]}]}));
 await page.locator('.changes-preview').evaluate(el=>{el.scrollLeft=600;});
 assert.equal(await page.locator('.changes-preview').evaluate(el=>el.scrollLeft),600);
 await page.evaluate(()=>window.smoke.emit({items:[{itemId:'change-test',kind:'fileChanges',live:true,added:2,removed:0,files:[{path:'src/feature.js',patch:'+'+'y'.repeat(300)}]}]}));
 await page.evaluate(()=>window.smoke.emit({items:[...Array(25).keys()].map(i=>({itemId:'fill-'+i,kind:'agentMessage',status:'completed',text:'Filler '+i+'\n'.repeat(30)})).concat([{itemId:'change-test',kind:'fileChanges',live:true,added:2,removed:0,files:[{path:'src/feature.js',patch:'+'+'y'.repeat(300)}]}])}));
 await page.evaluate(()=>{const area=document.querySelector('#scroll-area');area.scrollTop=area.scrollHeight;});
 assert.equal(await page.locator('#live-review').isVisible(),true);
 await page.evaluate(()=>{document.querySelector('#scroll-area').scrollTop=0;});
 assert.equal(await page.locator('#live-review').isVisible(),true);
 assert.equal(await page.locator('.change-row').count(),0);
 await page.evaluate(()=>window.smoke.emit({items:[{itemId:'change-test',kind:'fileChanges',live:true,added:2,removed:0,files:[{path:'src/feature.js',patch:'+'+'y'.repeat(300)}]}]}));
 assert.equal(await page.locator('.changes-preview').evaluate(el=>el.scrollLeft),600);
 await page.screenshot({path:'artifacts/muse-file-changes.png'});
 await page.locator('.changes-close').click();
 assert.equal(await page.locator('.changes-panel').count(),0);
 await page.evaluate(()=>window.smoke.emit({items:[{itemId:'change-test',kind:'fileChanges',live:false,added:3,removed:1,files:[{path:'src/feature.js',patch:'+closed update'}]}]}));
 assert.equal(await page.locator('#live-review').isVisible(),false);
 assert.equal(await page.locator('.change-row').count(),1);
 assert.equal(await page.locator('.changes-panel').count(),0);
 await page.evaluate(()=>{const base=Date.now(), original=Date.now;window.smoke.restoreClock=()=>{Date.now=original;};window.smoke.emit({busy:false});Date.now=()=>base;window.smoke.emit({busy:true});Date.now=()=>base+135000;});
 await page.waitForTimeout(1100);
 assert.equal(await page.locator('#elapsed').textContent(),'2m 15s');
 await page.evaluate(()=>{window.smoke.restoreClock();window.smoke.emit({busy:false});});
 await mkdir('artifacts',{recursive:true});
 await page.screenshot({path:'artifacts/mora-desktop-tools.png'});

 await page.evaluate(({png})=>{
   window.smoke.emit({busy:false,pendingQueue:[],items:[{itemId:'stable',kind:'userMessage',text:'Keep this row',images:[{mediaType:'image/png',base64Data:png}]},{itemId:'stream',kind:'agentMessage',status:'inProgress',text:'Start'},{itemId:'lazy',kind:'toolCall',status:'completed',visibleOutput:'Large output'.repeat(10000)}]});
   window.smoke.nodes={user:document.querySelector('.message.user'),image:document.querySelector('.message.user img'),sidebar:document.querySelector('.session-row'),tool:document.querySelector('.tool-card')};
 },{png});
 assert.equal(await page.locator('.tool-card pre').count(),0);
 await page.evaluate(()=>window.smoke.emit({items:[{itemId:'stable',kind:'userMessage',text:'Keep this row',images:[{mediaType:'image/png',base64Data:document.querySelector('.message.user img').src.split(',')[1]}]},{itemId:'stream',kind:'agentMessage',status:'inProgress',text:'# Result\n\n- First\n- Second\n\n| File | Status |\n| --- | --- |\n| app.js | Pass |'},{itemId:'lazy',kind:'toolCall',status:'completed',visibleOutput:'Large output'.repeat(10000)}]}));
 assert.equal(await page.evaluate(()=>window.smoke.nodes.user===document.querySelector('.message.user') && window.smoke.nodes.image===document.querySelector('.message.user img') && window.smoke.nodes.sidebar===document.querySelector('.session-row') && window.smoke.nodes.tool===document.querySelector('.tool-card')),true);
 assert.equal(await page.locator('.message-body h1').textContent(),'Result');
 assert.equal(await page.locator('.message-body li').count(),2);
 assert.equal(await page.locator('.message-body table td').count(),2);
 await page.locator('.tool-card summary').click();assert.match(await page.locator('.tool-card pre').textContent(),/Large output/);
 await page.locator('#prompt').fill('Saved draft');
 await page.waitForFunction(()=>window.smoke.draft?.text==='Saved draft');
 await page.evaluate(()=>window.smoke.emit({sessionId:'other-chat',draft:{text:'Another draft',images:[]}}));
 assert.equal(await page.locator('#prompt').inputValue(),'Another draft');
 const regressions=[];
 await page.evaluate(async()=>{window.smoke.emit({sessionId:'slow-chat',loading:true,draft:{text:'',images:[]}});await window.flushMoraDraft();});
 if(await page.evaluate(()=>window.smoke.draft.sessionId)!=='other-chat')regressions.push('Loading chat must not save the old composer under the new chat');
 await page.evaluate(()=>window.smoke.emit({loading:false,draft:{text:'Saved after slow history load',images:[]}}));
 if(await page.locator('#prompt').inputValue()!=='Saved after slow history load')regressions.push('Slow history loading must restore the saved draft');
 await page.evaluate(()=>{window.smoke.failDraft=true;window.smoke.emit({busy:true});});
 const stopped=await page.evaluate(()=>window.smoke.stopCalls);
 await page.locator('#stop-button').click();
 await page.waitForFunction(count=>window.smoke.stopCalls>count,stopped,{timeout:2000}).catch(()=>regressions.push('Stop must reach the engine when saving the draft fails'));
 await page.evaluate(()=>{window.smoke.failDraft=false;window.smoke.emit({busy:false,error:''});});
 await page.locator('#attach-button').click();
 await page.waitForFunction(()=>window.smoke.draft?.images.length===1,null,{timeout:2000}).catch(()=>regressions.push('Adding an image must autosave without typing'));
 await page.getByRole('button',{name:'Remove image',exact:true}).click();
 await page.waitForFunction(()=>window.smoke.draft?.images.length===0,null,{timeout:2000}).catch(()=>regressions.push('Removing an image must autosave without typing'));
 assert.deepEqual(regressions,[]);
 await page.evaluate(()=>window.smoke.emit({account:{status:'required',message:'Sign in to Muse'}}));
 assert.equal(await page.locator('#send-button').isDisabled(),true);
 await page.locator('#settings-button').click();await page.locator('#sign-in').click();
 await page.waitForFunction(()=>document.querySelector('#login-code').textContent==='DEMO-CODE');
 assert.equal(await page.locator('#sign-in').isVisible(),false);
 await page.locator('#cancel-sign-in').click();
 await page.waitForFunction(()=>document.querySelector('#login-code').hidden);
 await page.locator('#create-project').click();
 await page.getByRole('textbox',{name:'Project name',exact:true}).fill('First app');
 await page.getByRole('button',{name:'Choose parent folder',exact:true}).click();
 await page.getByRole('button',{name:'Create project',exact:true}).click();
 await page.waitForFunction(()=>window.smoke.projectsCreated.length===1);
 assert.equal(await page.evaluate(()=>window.smoke.projectsCreated[0].name),'First app');
 await page.evaluate(()=>window.smoke.emit({projectPath:'C:\\Projects\\First app',projectWork:{root:'C:\\Projects\\First app',run:{status:'ready',url:'http://localhost:3000'},tests:{status:'failed',message:'Tests failed',results:[{script:'test',status:'failed',output:'failure'}]}},executionMode:'readonly'}));
 await page.locator('#run-project').waitFor({state:'hidden'});assert.equal(await page.locator('#fix-tests').isDisabled(),true);
 await page.locator('#stop-project').click();assert.equal(await page.evaluate(()=>window.smoke.projectActions.at(-1)),'stop');
 await page.evaluate(()=>window.smoke.emit({projectWork:{root:'C:\\Projects\\First app',run:{status:'stopped'},tests:{status:'not checked'}}}));
 await page.locator('#checkpoints').click();await page.getByRole('button',{name:'Review restore'}).click();
 assert.equal(await page.locator('.checkpoint-dialog input[type=checkbox]').first().isChecked(),false);
 await page.locator('.checkpoint-dialog input[type=checkbox]').first().check();await page.locator('.checkpoint-dialog input[type=checkbox]').last().check();await page.getByRole('button',{name:'Restore selected files'}).click();
 await page.waitForFunction(()=>window.smoke.restores.length===1);assert.equal(await page.evaluate(()=>window.smoke.restores[0].allowConflicts),true);await page.getByRole('button',{name:'Close',exact:true}).click();
 await page.locator('#usage-button').click();
 await page.waitForFunction(()=>document.querySelectorAll('.usage-row').length===2);
 assert.equal(await page.locator('#usage-summary').textContent(),'5h 66% · wk 91%');
 assert.equal(await page.evaluate(()=>window.smoke.usageCalls),1);
 assert.equal(await page.locator('.usage-row small').first().textContent(),'66% left · resets in 1h 2m');
 await page.locator('#usage-refresh').click();
 await page.waitForFunction(()=>window.smoke.usageCalls===2);
 await page.evaluate(()=>{window.smoke.realUsage=window.muse.usageCommand;window.muse.usageCommand=async()=>{throw new Error('offline');};});
 await page.locator('#usage-refresh').click();
 await page.waitForFunction(()=>document.querySelector('.usage-error')?.textContent==='offline');
 await page.evaluate(()=>{window.muse.usageCommand=window.smoke.realUsage;});
 await page.keyboard.press('Escape');
 assert.equal(await page.locator('#usage-popover').isVisible(),false);
 console.log('PASS deterministic UI: stable streamed rows, lazy output, safe Markdown/images, durable drafts/attachments, Stop on save failure, queue and changes');
}finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
