import {clickControl} from './electron-ui.js';
import {createRequire} from 'node:module';
import {createServer} from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
import path from 'node:path';
const require=createRequire(import.meta.url);
const {chromium}=require('./runtime-packages.cjs').runtimeRequire('playwright');
const png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+ip1sAAAAASUVORK5CYII=';
const server=createServer(async(req,res)=>{
  const file={'/':'index.html','/style.css':'style.css','/renderer.js':'renderer.js','/markdown.js':'markdown.js','/project-ui.js':'project-ui.js','/work-ui.js':'work-ui.js','/images.js':'images.js','/projects.js':'projects.js','/browser-ui.js':'browser-ui.js','/assets/mora-mark.svg':'assets/mora-mark.svg'}[req.url];
  if(['/tester-ui.js','/website-ui.js','/website-coverage.js','/library-ui.js','/find-ui.js','/quick-actions.js','/setup-ui.js','/menu-ui.js','/mora-ui.js','/usage-ui.js','/usage.js','/video-frames.js'].includes(req.url)){res.setHeader('Content-Type','application/javascript');res.end(await readFile('src'+req.url));return;}
  if(req.url==='/workspace.css'){res.setHeader('Content-Type','text/css');res.end(await readFile('src/workspace.css'));return;}
  if(!file){res.writeHead(404).end();return;}
  res.setHeader('Content-Type',file.endsWith('.svg')?'image/svg+xml':file.endsWith('.css')?'text/css':file.endsWith('.js')?'application/javascript':'text/html');
  res.end(await readFile(path.join('src',file)));
});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const browser=await chromium.launch({...(process.argv[2]?{executablePath:path.resolve(process.argv[2])}:{channel:'msedge'}),headless:true});
try{
 const page=await browser.newPage({viewport:{width:1200,height:820}});
 await page.addInitScript(({png})=>{
  let state={items:[],sessions:[],models:[{modelId:'muse-test',displayLabel:'Muse test',variants:['minimal','max']}],modelId:'muse-test',reasoningEffort:'max',executionMode:'readonly',workspace:'C:\\Test',connection:'ready',engineVersion:'fixture',busy:false,pendingQueue:[]};
  let callback;window.smoke={projectActions:[],restores:[],accountActions:[],projectsCreated:[],stopCalls:0,failDraft:false,sent:[],copied:'',deleted:[],created:[],emit:next=>{state={...state,...next};callback?.({type:'state',state});}};
  window.muse={projectCommand:async action=>{window.smoke.projectActions.push(action);},checkpointCommand:async(action,payload)=>{if(action==='list')return [{id:'cp1',label:'Before request',fileCount:1,createdAt:new Date().toISOString(),manual:false}];if(action==='preview')return {token:'token',checkpoint:{label:'Before request',manual:false},changes:[{path:'app.js',status:'restore original',conflict:true}]};if(action==='restore'){window.smoke.restores.push(payload);return {restored:1};}},chooseProjectParent:async()=> 'C:\\Projects',createProject:async payload=>{window.smoke.projectsCreated.push(payload);return state;},accountCommand:async action=>{window.smoke.accountActions.push(action);window.smoke.emit({account:action==='login'?{status:'pending',message:'Approve the code',userCode:'DEMO-CODE'}:{status:'required',message:'Sign in required'}});},getState:async()=>state,onEvent:cb=>{callback=cb;return()=>{}},copyText:async text=>{window.smoke.copied=text},setOptions:async options=>{state={...state,...options};return state},pickImages:async()=>[{mediaType:'image/png',base64Data:png,name:'image.png'}],newChat:async projectPath=>{window.smoke.created.push(projectPath);return state},resumeChat:async()=>state,deleteChat:async id=>{window.smoke.deleted.push(id);return state},chooseWorkspace:async()=>state,chooseMuse:async()=>state,connect:async()=>state,stopTurn:async()=>{window.smoke.stopCalls++;window.smoke.emit({busy:false,stopping:false,queuePaused:true});},sendMessage:async value=>{window.smoke.sent.push(value);return{accepted:true}},saveDraft:async value=>{if(window.smoke.failDraft)throw new Error('Disk save failed');window.smoke.draft=value;},queueCommand:async action=>{if(action==='clear')window.smoke.emit({pendingQueue:[]});return state;}};
  window.smoke.testerCalls=[];
  window.smoke.queueCalls=[];window.muse.queueCommand=async(action,payload={})=>{
    window.smoke.queueCalls.push({action,payload});
    let pendingQueue=state.pendingQueue,queuePaused=state.queuePaused;
    if(action==='clear')pendingQueue=[];
    if(action==='pause'||action==='resume')queuePaused=action==='pause';
    if(action==='remove')pendingQueue=pendingQueue.filter(entry=>entry.queueId!==payload.queueId);
    if(action==='edit')pendingQueue=pendingQueue.map(entry=>entry.queueId===payload.queueId?{...entry,text:payload.text}:entry);
    window.smoke.emit({pendingQueue,queuePaused});return state;
  };
  window.smoke.reconnects=0;window.muse.connect=async()=>{window.smoke.reconnects++;window.smoke.emit({connection:'ready',error:''});return state;};
  window.muse.exportProject=async()=>{if(window.smoke.exportFails)throw Error('Source limits exceeded.');return {destination:'C:\\Exports\\App.zip',fileCount:2,sha256:'a'.repeat(64)};};
  window.muse.revealProjectExport=async()=>{window.smoke.revealed=true;};
  window.muse.inspectSetup=async()=>[{id:'muse',title:'Muse engine',status:'ready',detail:'Connected'},{id:'node',title:'Node.js',status:'missing',detail:'Install Node.js, then restart Mora.'}];
  window.smoke.brief={text:'Goal: build a local shop\r\n',revision:'brief-1'};
  window.muse.projectBriefCommand=async(action,payload)=>{if(action==='read')return window.smoke.brief;window.smoke.brief={text:payload.text,revision:'brief-2'};return window.smoke.brief;};
  window.muse.testerCommand=async(action,payload)=>{
    window.smoke.testerCalls.push({action,payload});
    if(action==='list')return state.tester?[state.tester]:[];
    if(action==='evidence')return png;
    if(action==='start')window.smoke.emit({testerActive:true,tester:{id:'r1',project:state.projectPath,createdAt:new Date().toISOString(),status:'running',actions:4,message:'Checking cart',cases:[{id:'CASE-001',title:'<b>Cart</b>',expected:'Cart contains item',status:'confirmed',steps:[{id:'ACTION-4',action:{action:'assert',check:'text',expected:'Cart (1)'},result:{passed:false,screenshot:{name:'screen-1.png'}}}]},{id:'CASE-002',title:'Reload',status:'not tested',steps:[]}],issues:[{id:'BUG-001',title:'Cart did not update',status:'confirmed'}],gaps:[]}});
    if(action==='stop')window.smoke.emit({testerActive:false,tester:{...state.tester,status:'paused'}});
    if(action==='resume')window.smoke.emit({testerActive:true,tester:{...state.tester,status:'running'}});
    if(action==='load')window.smoke.emit({tester:state.tester});
    return state.tester;
  };
 },{png});
 await page.goto(`http://127.0.0.1:${server.address().port}`);
 await page.locator('#connection-badge').filter({hasText:'Connected'}).waitFor();
 await page.locator('#welcome-setup').click();await page.getByRole('dialog',{name:'Setup readiness',exact:true}).waitFor();
 assert.match(await page.locator('.setup-checks').textContent(),/Node.js.*missing.*Install Node.js/);
 await page.getByRole('button',{name:'Close setup',exact:true}).click();
 await page.evaluate(()=>window.smoke.emit({connection:'disconnected',error:'The engine disconnected.'}));
 assert.equal(await page.locator('#recovery-reconnect').count(),1,'A disconnected engine needs an explicit recovery action');
 await page.locator('#recovery-reconnect').click();await page.waitForFunction(()=>window.smoke.reconnects===1);
 await page.evaluate(()=>window.smoke.emit({error:'Node is unavailable.'}));await page.locator('#recovery-setup').click();await page.getByRole('dialog',{name:'Setup readiness',exact:true}).waitFor();await page.getByRole('button',{name:'Close setup',exact:true}).click();
 await page.evaluate(()=>window.smoke.emit({error:'',lastOutcome:{status:'interrupted',turnId:'recovery-test',message:'Request interrupted.'}}));
 await page.locator('#prompt').fill('Keep this draft');await page.getByRole('button',{name:'Continue in chat',exact:true}).click();assert.equal(await page.locator('#prompt').inputValue(),'Keep this draft');assert.equal(await page.evaluate(()=>document.activeElement.id),'prompt');assert.equal(await page.evaluate(()=>window.smoke.sent.length),0);
 await page.evaluate(()=>window.smoke.emit({lastOutcome:null}));await page.locator('#prompt').fill('');
 assert.equal(await page.locator('#sidebar-toggle').count(),1,'The navigation needs a persistent show/hide control');
 await page.locator('#sidebar-toggle').click();assert.equal(await page.locator('.sidebar').isVisible(),false);
 await page.locator('#welcome-setup').click();await page.getByRole('button',{name:'Open engine settings',exact:true}).click();await page.locator('.setup-dialog').waitFor({state:'detached'});
 assert.equal(await page.locator('#settings-panel').isVisible(),true,'Setup opens engine settings even with collapsed navigation');await page.locator('#settings-close').click();await page.locator('#sidebar-toggle').click();
 await page.reload();await page.locator('#connection-badge').filter({hasText:'Connected'}).waitFor();assert.equal(await page.locator('.sidebar').isVisible(),false,'Collapsed navigation survives reload');
 await page.keyboard.press('Control+b');assert.equal(await page.locator('.sidebar').isVisible(),true);
 await page.locator('#new-chat').focus();await page.keyboard.press('Control+b');assert.equal(await page.locator('#sidebar-toggle').evaluate(e=>e===document.activeElement),true,'Collapsing navigation must not strand focus');
 await page.locator('#sidebar-toggle').click();
 await page.evaluate(()=>{
  window.muse.chatMetadata=async(id,action,title)=>{const state=await window.muse.getState();const {changeConversation}=await import('/projects.js');changeConversation(state,id,action,title);window.smoke.emit({sessions:state.sessions});return state;};
  window.smoke.removedProjects=[];window.muse.removeProject=async root=>{window.smoke.removedProjects.push(root);const state=await window.muse.getState();state.projects=state.projects.filter(project=>project!==root);state.sessions=state.sessions.filter(chat=>chat.projectPath!==root);window.smoke.emit(state);return state;};
  window.smoke.emit({sessionId:'chat-a',projectPath:null,sessions:[{sessionId:'chat-a',projectPath:null,workspace:'private',title:'Alpha'},{sessionId:'chat-b',projectPath:'C:/Example',workspace:'C:/Example',title:'Build'},{sessionId:'chat-c',projectPath:null,workspace:'private',title:'Old',archived:true}],projects:['C:/Example','D:/Empty'],items:[{itemId:'find-a',kind:'agentMessage',status:'completed',text:'A safe **match** here.\n\nA safe match again.\n\n> A safe **match** quote.\n\n| Header |\n| --- |\n| A safe **match** cell. |\n\n<img src=x onerror=alert(1)>'}]});
 });
 await page.locator('#library-search').fill('example');assert.equal(await page.locator('.session-row').count(),1);
 await page.locator('#library-search').fill('does not exist');assert.match(await page.locator('#general-sessions').textContent(),/No matching/);
 await page.locator('#library-clear').click();assert.equal(await page.locator('.session-row').count(),2);
 await page.getByRole('button',{name:'Rename Alpha',exact:true}).click();await page.getByLabel('Rename chat',{exact:true}).fill('Cancelled draft');await page.keyboard.press('Escape');assert.equal(await page.getByRole('button',{name:'Options for Alpha',exact:true}).count(),1);
 await page.getByRole('button',{name:'Rename Alpha',exact:true}).click();await page.getByLabel('Rename chat',{exact:true}).fill('Inline title');await page.keyboard.press('Enter');await page.getByRole('button',{name:'Options for Inline title',exact:true}).waitFor();assert.equal(await page.evaluate(async()=> (await window.muse.getState()).sessions[0].customTitle),true);
 await page.evaluate(()=>window.muse.chatMetadata('chat-a','rename','Alpha'));
 await page.getByRole('button',{name:'Remove project Empty',exact:true}).click();assert.match(await page.locator('.project-remove-dialog').textContent(),/archived chats.*folder and files stay on disk/s);assert.equal(await page.getByRole('button',{name:'Cancel',exact:true}).evaluate(node=>node===document.activeElement),true);await page.getByRole('button',{name:'Cancel',exact:true}).click();assert.equal(await page.evaluate(()=>window.smoke.removedProjects.length),0);
 await page.getByRole('button',{name:'Remove project Empty',exact:true}).click();await page.getByRole('button',{name:'Remove project',exact:true}).click();await page.locator('.project-remove-dialog').waitFor({state:'hidden'});assert.deepEqual(await page.evaluate(()=>window.smoke.removedProjects),['D:/Empty']);assert.equal(await page.getByRole('button',{name:'Remove project Example',exact:true}).count(),1);
 await page.getByRole('button',{name:'Options for Alpha',exact:true}).click();await page.getByLabel('Chat title',{exact:true}).fill('Renamed');await page.getByRole('button',{name:'Save title',exact:true}).click();await page.locator('.chat-dialog').waitFor({state:'hidden'});
 await page.getByRole('button',{name:'Options for Renamed',exact:true}).click();await page.getByRole('button',{name:'Pin',exact:true}).click();await page.locator('.chat-dialog').waitFor({state:'hidden'});assert.match(await page.locator('#general-sessions .session-button').textContent(),/★ Renamed/);
 await page.getByRole('button',{name:'Options for Renamed',exact:true}).click();await page.getByRole('button',{name:'Save title',exact:true}).focus();await page.evaluate(()=>window.smoke.emit({busy:true}));assert.equal(await page.getByRole('button',{name:'Save title',exact:true}).evaluate(el=>el===document.activeElement),true);assert.equal(await page.getByRole('button',{name:'Archive chat',exact:true}).isDisabled(),true);await page.keyboard.press('Escape');
 await page.evaluate(()=>window.smoke.emit({busy:false}));await page.getByRole('button',{name:'Options for Renamed',exact:true}).click();await page.getByRole('button',{name:'Archive chat',exact:true}).click();await page.locator('.chat-dialog').waitFor({state:'hidden'});assert.equal(await page.locator('#library-archived').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('#general-sessions .session-row').count(),2);
 await page.getByRole('button',{name:'Options for Renamed',exact:true}).click();await page.getByRole('button',{name:'Restore chat',exact:true}).click();await page.locator('.chat-dialog').waitFor({state:'hidden'});assert.equal(await page.locator('#library-active').getAttribute('aria-pressed'),'true');assert.equal(await page.evaluate(async()=> (await window.muse.getState()).sessionId),'chat-a');
 await page.locator('#prompt').focus();await page.keyboard.press('Control+f');await page.locator('#find-text').fill('safe match');assert.equal(await page.locator('#find-count').textContent(),'1 of 4');
 await page.locator('#find-text').press('Enter');assert.equal(await page.locator('#find-count').textContent(),'2 of 4');await page.locator('#find-text').press('Shift+Enter');assert.equal(await page.locator('#find-count').textContent(),'1 of 4');
 await page.evaluate(()=>window.smoke.emit({items:[{itemId:'find-a',kind:'agentMessage',status:'inProgress',text:'A safe **match** here.\n\nA safe match again.\n\nStreamed safe match.'}]}));await page.waitForFunction(()=>document.querySelector('#find-count').textContent==='1 of 3');
 assert.equal(await page.locator('.message-body mark').count(),0);assert.equal(await page.evaluate(()=>CSS.highlights.get('conversation-matches').size),3);
 await page.screenshot({path:'artifacts/chat-library-find.png'});
 await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>document.activeElement?.id),'prompt');
 await page.keyboard.press('Control+f');await page.locator('#find-text').fill('[.*');assert.equal(await page.locator('#find-count').textContent(),'No matches');await page.evaluate(()=>window.smoke.emit({sessionId:'chat-b'}));assert.equal(await page.locator('#find-text').inputValue(),'');await page.keyboard.press('Escape');
 await page.locator('#library-archived').click();await page.evaluate(()=>window.smoke.emit({sessionId:'new-chat'}));assert.equal(await page.locator('#library-active').getAttribute('aria-pressed'),'true');await page.locator('#library-active').click();await page.evaluate(()=>window.smoke.emit({sessionId:null,sessions:[],projects:[],items:[],busy:false}));
 assert.equal(await page.title(),'Mora Desktop');
 await page.keyboard.press('Control+k');await page.getByRole('dialog',{name:'Quick actions and shortcuts'}).waitFor();
 await page.getByLabel('Search quick actions',{exact:true}).fill('find');await page.getByRole('button',{name:'Find in current conversation',exact:false}).click();assert.equal(await page.locator('#conversation-find').isVisible(),true);await page.keyboard.press('Escape');
 await page.locator('#sidebar-toggle').click();await page.keyboard.press('Control+Shift+f');assert.equal(await page.locator('.sidebar').isVisible(),true);assert.equal(await page.locator('#library-search').evaluate(el=>el===document.activeElement),true);
 await page.evaluate(()=>window.smoke.emit({busy:true}));await page.keyboard.press('Control+k');await page.getByLabel('Search quick actions',{exact:true}).fill('new conversation');assert.equal(await page.getByRole('button',{name:/New conversation.*Ctrl\+N/}).isDisabled(),true);await page.keyboard.press('Escape');await page.evaluate(()=>window.smoke.emit({busy:false}));
 assert.equal(await page.locator('.brand strong').textContent(),'Mora');
 await page.waitForFunction(()=>[...document.querySelectorAll('.brand-mark,.welcome-emblem')].every(img=>img.complete&&img.naturalWidth>0));
 await page.evaluate(()=>window.smoke.emit({sessionId:'missing-history',error:'The original engine log is missing.',historyMissing:true}));
 assert.equal(await page.locator('#recovery-new-chat').isVisible(),true);await page.evaluate(()=>window.smoke.emit({busy:true}));assert.equal(await page.locator('#recovery-new-chat').isDisabled(),true);await page.evaluate(()=>window.smoke.emit({busy:false}));
 await page.locator('#dismiss-error').click();
 await page.evaluate(()=>window.smoke.emit({engineVersion:'state update'}));
 assert.equal(await page.locator('#error-banner').isVisible(),false);
 await page.evaluate(()=>window.smoke.emit({sessionId:'normal-general',projectPath:null,error:'',historyMissing:false}));
 assert.equal(await page.locator('#error-banner').isVisible(),false);
 await page.locator('#prompt').fill('Follow up');
 assert.equal(await page.locator('#send-button').isEnabled(),true);
 await page.locator('#prompt').fill('');
 await page.evaluate(()=>window.smoke.emit({error:'Muse exited (1) before completing the request.'}));
 await page.locator('#dismiss-error').click();
 await page.evaluate(()=>{window.smoke.emit({error:'',busy:true});window.smoke.emit({busy:false,error:'Muse exited (1) before completing the request.'});});
 assert.equal(await page.locator('#error-banner').isVisible(),true);
 await page.evaluate(()=>window.smoke.emit({error:''}));
 await page.evaluate(()=>window.smoke.emit({projectPath:null,projects:['C:\\Muse','C:\\ExampleProject'],sessions:[
  {sessionId:'g',title:'General question',projectPath:null,workspace:'C:\\Profile\\general-chat'},
  {sessionId:'m',title:'Develop Muse',workspace:'C:\\Muse'},
  {sessionId:'s',title:'Explain the project',workspace:'C:\\ExampleProject'},
 ]}));
 assert.equal(await page.locator('#general-sessions .session-row').count(),1);
 assert.equal(await page.locator('.project-group').count(),2);
 assert.equal(await page.locator('.project-group').first().locator('.session-button').textContent(),'Develop Muse');
 await page.evaluate(()=>{document.querySelector('.project-group summary').click();window.smoke.emit({engineVersion:'streaming update'});});
 assert.equal(await page.locator('.session-row[data-session-id="m"]').isVisible(),false);
 await page.locator('.project-group').first().locator('summary').click();
 await page.locator('.project-group').first().locator('summary').click();
 assert.equal(await page.locator('.session-row[data-session-id="m"]').isVisible(),false);
 await page.locator('.project-group').first().locator('summary').click();
 await page.getByRole('button',{name:'New chat in Muse',exact:true}).click();
 assert.equal(await page.evaluate(()=>window.smoke.created.at(-1)),'C:\\Muse');
 await page.locator('#new-chat').click();
 assert.equal(await page.evaluate(()=>window.smoke.created.at(-1)),null);
 assert.equal(await page.locator('#project-name').textContent(),'General chat');
 assert.equal(await page.locator('#execution-mode').isVisible(),false);
 await page.screenshot({path:'artifacts/muse-project-groups.png'});
 await page.evaluate(()=>window.smoke.emit({projectPath:'C:\\Test',projects:[],sessions:[]}));
 await page.screenshot({path:'artifacts/mora-welcome.png'});
 await page.locator('#prompt').fill('Hello Mora');
 await page.evaluate(()=>document.querySelector('#prompt').dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',isComposing:true,bubbles:true,cancelable:true})));
 assert.equal(await page.evaluate(()=>window.smoke.sent.length),0);
 await page.locator('#prompt').press('Shift+Enter');
 assert.match(await page.locator('#prompt').inputValue(),/\n/);
 await page.locator('#attach-button').click();
 assert.equal(await page.locator('.attachment').count(),1);
 await page.evaluate(({png})=>{const bytes=Uint8Array.from(atob(png),c=>c.charCodeAt(0));const data=new DataTransfer();data.items.add(new File([bytes],'pasted.png',{type:'image/png'}));document.querySelector('#prompt').dispatchEvent(new ClipboardEvent('paste',{clipboardData:data,bubbles:true,cancelable:true}));},{png});
 await page.waitForFunction(()=>document.querySelectorAll('.attachment').length===2);
 await page.locator('#prompt').press('Enter');
 await page.waitForFunction(()=>window.smoke.sent.length===1);
 assert.equal(await page.evaluate(()=>window.smoke.sent[0].images.length),2);
 assert.match(await page.evaluate(()=>window.smoke.sent[0].text),/Hello Mora/);
 await page.waitForFunction(()=>document.querySelector('#prompt').value==='');
 await page.evaluate(()=>window.smoke.emit({items:[{itemId:'a',kind:'agentMessage',revision:1,status:'completed',text:'<img src=x onerror="window.pwned=1">\n```js\nconsole.log(42);\n```'}]}));
 assert.equal(await page.evaluate(()=>window.pwned),undefined);
 assert.equal(await page.locator('.message-body img').count(),0);
 await page.waitForFunction(()=>document.querySelector('.message.assistant .avatar img')?.naturalWidth>0);
 await page.screenshot({path:'artifacts/mora-message.png'});
 await page.locator('.code-header button').click();
 assert.equal(await page.evaluate(()=>window.smoke.copied),'console.log(42);\n');
 await page.route('https://lh3.googleusercontent.com/aida/**',route=>route.fulfill({contentType:'image/png',body:Buffer.from(png,'base64')}));
 await page.evaluate(()=>window.smoke.emit({items:[{itemId:'stitch-preview',kind:'agentMessage',status:'completed',text:'The new design\n(https://lh3.googleusercontent.com/aida/fixture-design)\n```text\nhttps://lh3.googleusercontent.com/aida/code-example\n```'}]}));
 assert.equal(await page.locator('.stitch-image img').count(),1,'A plain Stitch output URL must render as an image; code URLs remain literal');
 await page.waitForFunction(()=>document.querySelector('.stitch-image img')?.naturalWidth>0);
 await page.locator('.stitch-image .image-preview-button').click();
 assert.equal(await page.locator('.image-viewer').isVisible(),true);
 await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.querySelector('.image-viewer'));
 await page.evaluate(()=>window.smoke.emit({items:[{itemId:'stitch-preview',kind:'agentMessage',status:'completed',text:'![Card](https://lh3.googleusercontent.com/aida/fixture-design)\n[Design](https://lh3.googleusercontent.com/aida/fixture-design-2)\nhttps://untrusted.example/image.png'}]}));
 assert.equal(await page.locator('.stitch-image img').count(),2);
 assert.match(await page.locator('.message-body').textContent(),/https:\/\/untrusted.example\/image.png/);
 await page.locator('.image-copy-link').first().click();
 assert.equal(await page.evaluate(()=>window.smoke.copied),'https://lh3.googleusercontent.com/aida/fixture-design');
 await page.route('https://lh3.googleusercontent.com/aida/broken',route=>route.abort());
 await page.evaluate(()=>window.smoke.emit({items:[{itemId:'stitch-broken',kind:'agentMessage',status:'completed',text:'https://lh3.googleusercontent.com/aida/broken'}]}));
 await page.locator('.stitch-image figcaption').filter({hasText:'Preview unavailable'}).waitFor();
 assert.equal(await page.locator('.image-preview-button').isVisible(),false);
 assert.equal(await page.locator('.image-copy-link').isVisible(),true);
 await page.evaluate(()=>window.smoke.emit({items:[{itemId:'stitch-code',kind:'agentMessage',status:'inProgress',text:'Before\n```html\nhttps://lh3.googleusercontent.com/aida/code-example\n'}]}));
 assert.equal(await page.locator('.stitch-image').count(),0,'An unfinished streamed code fence must keep image links literal');
 await page.evaluate(()=>window.smoke.emit({items:[{itemId:'stitch-html',kind:'agentMessage',status:'completed',text:'<img src="https://lh3.googleusercontent.com/aida/code-example">'}]}));
 assert.equal(await page.locator('.stitch-image').count(),0,'Raw HTML must stay literal, including image attributes');
 await page.evaluate(()=>window.smoke.emit({items:[{itemId:'stitch-multiline-html',kind:'agentMessage',status:'inProgress',text:'Example:\n<img\n class="design"\n src="https://lh3.googleusercontent.com/aida/code-example"'}]}));
 assert.equal(await page.locator('.stitch-image').count(),0,'Multiline and incomplete HTML tags must also stay literal');
 await page.evaluate(()=>window.smoke.emit({busy:true,items:[{itemId:'b',kind:'toolCall',revision:1,status:'inProgress',tool:'powershell',visibleOutput:'FILE_OK'}]}));
 assert.equal(await page.locator('#workspace-button').isDisabled(),true);
 assert.equal(await page.locator('#model').isDisabled(),true);
 assert.match(await page.locator('.tool-card pre').textContent(),/FILE_OK/,'A running tool should show its output');
 await page.locator('.tool-card summary').click();await page.locator('.tool-card pre').waitFor({state:'detached'});
 await page.locator('.tool-card summary').click();
 assert.match(await page.locator('.tool-card pre').textContent(),/FILE_OK/,'Reopening a tool should restore its output');
 await page.evaluate(()=>window.smoke.emit({busy:true,finishing:true,items:[{itemId:'answer',kind:'agentMessage',status:'inProgress',text:'The reply is ready'}]}));
 assert.match(await page.locator('#working-label').textContent(),/Reply ready/);
 assert.equal(await page.locator('#prompt').isEnabled(),true);
 await page.locator('#prompt').fill('Draft the next message');
 await page.locator('#prompt').press('Enter');
 await page.waitForFunction(()=>window.smoke.sent.length===2);
 await page.waitForFunction(()=>document.querySelector('#prompt').value==='');
 await page.evaluate(()=>window.smoke.emit({pendingQueue:[{queueId:'q1',text:'Draft the next message',images:[]}]}));
 await page.waitForFunction(()=>document.querySelectorAll('.queue-badge').length===1);
 assert.equal(await page.locator('.queue-badge').textContent(),'Queued');
 assert.equal(await page.locator('#queue-messages .message.queued').count(),1,'Pending messages belong next to the composer');
 assert.equal(await page.locator('#messages .message.queued').count(),0,'Pending messages should not fill the conversation');
 const queuedBounds=await page.locator('.message.queued').boundingBox(),queuedComposerBounds=await page.locator('#composer').boundingBox();
 assert.ok(queuedBounds.height<=44,'A short queued message is one compact line');
 assert.ok(queuedBounds.y+queuedBounds.height<=queuedComposerBounds.y && queuedComposerBounds.y-queuedBounds.y-queuedBounds.height<=12,'The queue sits immediately above the composer');
 await page.locator('.message.queued').getByRole('button',{name:'Edit',exact:true}).click();
 await page.getByRole('textbox',{name:'Edit queued message',exact:true}).fill('Keep my unsaved edit');
 await page.evaluate(()=>window.smoke.emit({activity:'Another tool is working',queuePaused:true}));
 assert.equal(await page.getByRole('textbox',{name:'Edit queued message',exact:true}).inputValue(),'Keep my unsaved edit','Progress and pause updates preserve the queue editor');
 await page.keyboard.press('Escape');assert.equal(await page.getByRole('textbox',{name:'Edit queued message',exact:true}).count(),0);
 assert.equal(await page.locator('.queue-edit-button').evaluate(node=>node===document.activeElement),true);
 await page.evaluate(({png})=>window.smoke.emit({queuePaused:false,pendingQueue:[{queueId:'q1',text:'Hi',images:[]},{queueId:'q2',text:'Please fix this image',images:[{mediaType:'image/png',base64Data:png}]}]}),{png});
 await page.getByRole('button',{name:'View 1 queued image',exact:true}).click();
 await page.getByRole('button',{name:'Enlarge queued image',exact:true}).click();await page.getByRole('dialog').waitFor();await page.getByRole('button',{name:'Close image',exact:true}).click();
 await page.getByRole('textbox',{name:'Edit queued message',exact:true}).fill('Edited follow-up');await page.getByRole('button',{name:'Save queued message',exact:true}).click();
 await page.waitForFunction(()=>document.querySelectorAll('.queue-edit').length===0);
 assert.deepEqual(await page.evaluate(()=>window.smoke.queueCalls.at(-1)),{action:'edit',payload:{queueId:'q2',text:'Edited follow-up'}});
 assert.equal(await page.getByRole('button',{name:'View 1 queued image',exact:true}).count(),1,'Editing text keeps its queued image');
 await page.locator('.message.queued').nth(1).getByRole('button',{name:'Remove',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.message.queued').length===1);
 assert.deepEqual(await page.evaluate(()=>window.smoke.queueCalls.at(-1)),{action:'remove',payload:{queueId:'q2'}});
 await page.locator('.composer-area').screenshot({path:'artifacts/mora-queue.png'});
 await page.locator('#queue-menu > summary').click();assert.equal(await page.getByRole('button',{name:'Pause queue',exact:true}).isVisible(),true);
 await page.keyboard.press('Escape');assert.equal(await page.locator('#queue-menu').getAttribute('open'),null);assert.equal(await page.locator('#queue-menu > summary').evaluate(node=>node===document.activeElement),true);
 await clickControl(page,'queue-toggle');await page.waitForFunction(()=>document.querySelector('.queue-badge').textContent==='Paused');
 await clickControl(page,'queue-toggle');await page.waitForFunction(()=>document.querySelector('.queue-badge').textContent==='Queued');
 await page.setViewportSize({width:860,height:640});
 await page.evaluate(()=>window.smoke.emit({pendingQueue:Array.from({length:8},(_,i)=>({queueId:'long-'+i,text:'A long queued message with lines\n'+'More text '.repeat(100),images:[]}))}));
 assert.ok((await page.locator('#queue-messages').boundingBox()).height<=180,'Many queued messages leave room for typing');
 assert.ok(await page.locator('.message.queued').evaluateAll(nodes=>nodes.every(node=>node.scrollWidth<=node.clientWidth)),'Long prompts fit the strip');
 await page.locator('#queue-menu > summary').click();
 const queueMenuBounds=await page.locator('#queue-menu .menu-content').boundingBox();assert.ok(queueMenuBounds.x>=0&&queueMenuBounds.y>=0&&queueMenuBounds.x+queueMenuBounds.width<=860,'The small-window queue menu stays visible');await page.keyboard.press('Escape');
 await page.evaluate(()=>window.smoke.emit({pendingQueue:[{queueId:'q1',text:'Hi',images:[]}]}));await page.setViewportSize({width:1200,height:820});
 assert.equal(await page.locator('#send-button').isVisible(),true);
 await page.locator('#stop-button').click();
 assert.equal(await page.locator('.queue-badge').count(),1);
 await clickControl(page,'queue-clear');
 await page.waitForFunction(()=>document.querySelectorAll('.queue-badge').length===0);
 assert.equal(await page.locator('#queue-dock').isVisible(),false);assert.equal(await page.locator('#queue-menu').getAttribute('open'),null);
 await page.evaluate(()=>window.smoke.emit({busy:true,finishing:false}));
 await page.locator('#stop-button').click();
 await page.waitForFunction(()=>document.querySelector('#stop-button').hidden);
 await page.evaluate(()=>{const data=new DataTransfer();data.items.add(new File([new Uint8Array(10*1024*1024+1)],'huge.png',{type:'image/png'}));document.querySelector('#prompt').dispatchEvent(new ClipboardEvent('paste',{clipboardData:data,bubbles:true,cancelable:true}));});
 await page.waitForFunction(()=>document.querySelector('#error-text').textContent.includes('10 MB'));
 await page.evaluate(()=>window.smoke.emit({sessions:[{sessionId:'s1',title:'First chat',workspace:'C:\\A'},{sessionId:'s2',title:'Second chat',workspace:'C:\\A'}]}));
 await page.waitForFunction(()=>document.querySelectorAll('.session-row').length===2);
 assert.equal(await page.locator('.session-menu-button').count(),0);
 assert.equal(await page.locator('.session-row .session-delete-icon').count(),2);
 const del=page.locator('.session-row[data-session-id="s2"] .session-delete-icon');
 const delOpacity=()=>page.evaluate(()=>getComputedStyle(document.querySelector('.session-row[data-session-id="s2"] .session-delete-icon')).opacity);
 assert.equal(await delOpacity(),'0');
 await page.locator('.session-row[data-session-id="s2"]').hover();
 assert.equal(await delOpacity(),'1');
 await del.click();
 assert.equal(await page.evaluate(()=>window.smoke.deleted.length),0);
 assert.equal(await del.evaluate(el=>el.classList.contains('confirm')),true);
 await del.click();
 await page.waitForFunction(()=>window.smoke.deleted.length===1);
 assert.equal(await page.evaluate(()=>window.smoke.deleted[0]),'s2');
 await page.evaluate(()=>window.smoke.emit({items:[{itemId:'change-test',kind:'fileChanges',added:68,removed:3,files:[{path:'src/feature.js',status:'modified',added:68,removed:3,patch:'@@ -1 +1 @@\n-old value\n+<script>literal text</script>\n context'}]}]}));
 await page.locator('.change-badge').waitFor();
 assert.match(await page.locator('.change-badge').textContent(),/Edited src\/feature\.js.*\+68.*-3/);
 await page.locator('.change-badge').click();
 await page.locator('.changes-panel').waitFor();
 assert.equal(await page.locator('.diff-line.added').textContent(),'+<script>literal text</script>');
 assert.equal(await page.locator('.changes-panel script').count(),0);
 await page.evaluate(()=>window.smoke.emit({busy:true,items:[{itemId:'step',kind:'activity',text:'Preparing the response'},{itemId:'change-test',kind:'fileChanges',live:true,added:2,removed:1,files:[{path:'src/other.js',added:1,removed:0,patch:'+other'},{path:'src/feature.js',added:1,removed:1,patch:'@@ -1 +1 @@\n-old\n+updated live'}]}]}));
 assert.match(await page.locator('#live-review').textContent(),/2 files changed.*Live/);assert.equal(await page.locator('.change-badge').count(),0,'Live changes have one visible home above the composer');
 const liveBounds=await page.locator('#live-review').boundingBox(),composerBounds=await page.locator('#composer').boundingBox();assert.ok(liveBounds.y+liveBounds.height<=composerBounds.y);
 assert.equal(await page.locator('.diff-filename').textContent(),'src/feature.js');
 assert.equal(await page.locator('.diff-line.added').textContent(),'+updated live');
 assert.equal(await page.locator('.activity-step').textContent(),'Preparing the response');
 await page.evaluate(()=>window.smoke.emit({items:[{itemId:'change-test',kind:'fileChanges',live:true,added:1,removed:0,files:[{path:'src/feature.js',patch:'+'+'x'.repeat(300)}]}]}));
 await page.locator('.changes-preview').evaluate(el=>{el.scrollLeft=600;});
 assert.equal(await page.locator('.changes-preview').evaluate(el=>el.scrollLeft),600);
 await page.evaluate(()=>window.smoke.emit({items:[{itemId:'change-test',kind:'fileChanges',live:true,added:2,removed:0,files:[{path:'src/feature.js',patch:'+'+'y'.repeat(300)}]}]}));
 assert.equal(await page.locator('.changes-preview').evaluate(el=>el.scrollLeft),600);
 await page.screenshot({path:'artifacts/muse-file-changes.png'});
 await page.locator('.changes-close').click();
 assert.equal(await page.locator('.changes-panel').count(),0);
 await page.evaluate(()=>window.smoke.emit({items:[{itemId:'change-test',kind:'fileChanges',live:false,added:3,removed:1,files:[{path:'src/feature.js',patch:'+closed update'}]}]}));
 assert.equal(await page.locator('#live-review').isVisible(),false);assert.equal(await page.locator('.change-badge').count(),1);
 assert.equal(await page.locator('.changes-panel').count(),0);
 await page.evaluate(()=>{const base=Date.now(), original=Date.now;window.smoke.restoreClock=()=>{Date.now=original;};window.smoke.emit({busy:false});Date.now=()=>base;window.smoke.emit({busy:true});Date.now=()=>base+135000;});
 await page.waitForTimeout(1100);
 assert.equal(await page.locator('#elapsed').textContent(),'2m 15s');
 await page.evaluate(()=>{window.smoke.restoreClock();window.smoke.emit({busy:false});});
 await mkdir('artifacts',{recursive:true});
 await page.screenshot({path:'artifacts/mora-desktop-tools.png'});

 await page.evaluate(({png})=>{
   window.smoke.emit({busy:false,pendingQueue:[],items:[{itemId:'stable',kind:'userMessage',text:'Keep this row',images:[{mediaType:'image/png',base64Data:png}]},{itemId:'stream',kind:'agentMessage',status:'inProgress',text:'Start'},{itemId:'lazy',kind:'toolCall',status:'completed',visibleOutput:'Large output'.repeat(10000)}]});
   window.smoke.nodes={user:document.querySelector('.message.user'),image:document.querySelector('.message.user img'),sidebar:document.querySelector('.session-row'),tool:document.querySelector('.tool-card')};
 },{png});
 assert.equal(await page.locator('.tool-card pre').count(),0);
 await page.evaluate(()=>window.smoke.emit({items:[{itemId:'stable',kind:'userMessage',text:'Keep this row',images:[{mediaType:'image/png',base64Data:document.querySelector('.message.user img').src.split(',')[1]}]},{itemId:'stream',kind:'agentMessage',status:'inProgress',text:'# Result\n\n- First\n- Second\n\n| File | Status |\n| --- | --- |\n| app.js | Pass |'},{itemId:'lazy',kind:'toolCall',status:'completed',visibleOutput:'Large output'.repeat(10000)}]}));
 assert.equal(await page.evaluate(()=>window.smoke.nodes.user===document.querySelector('.message.user') && window.smoke.nodes.image===document.querySelector('.message.user img') && window.smoke.nodes.sidebar===document.querySelector('.session-row') && window.smoke.nodes.tool===document.querySelector('.tool-card')),true);
 assert.equal(await page.locator('.message-body h1').textContent(),'Result');
 assert.equal(await page.locator('.message-body li').count(),2);
 assert.equal(await page.locator('.message-body table td').count(),2);
 await page.locator('.tool-card summary').click();assert.match(await page.locator('.tool-card pre').textContent(),/Large output/);
 await page.locator('#prompt').fill('Saved draft');
 await page.waitForFunction(()=>window.smoke.draft?.text==='Saved draft');
 await page.evaluate(()=>window.smoke.emit({sessionId:'other-chat',draft:{text:'Another draft',images:[]}}));
 assert.equal(await page.locator('#prompt').inputValue(),'Another draft');
 const regressions=[];
 await page.evaluate(async()=>{window.smoke.emit({sessionId:'slow-chat',loading:true,draft:{text:'',images:[]}});await window.flushMoraDraft();});
 if(await page.evaluate(()=>window.smoke.draft.sessionId)!=='other-chat')regressions.push('Loading chat must not save the old composer under the new chat');
 await page.evaluate(()=>window.smoke.emit({loading:false,draft:{text:'Saved after slow history load',images:[]}}));
 if(await page.locator('#prompt').inputValue()!=='Saved after slow history load')regressions.push('Slow history loading must restore the saved draft');
 await page.evaluate(()=>{window.smoke.failDraft=true;window.smoke.emit({busy:true});});
 const stopped=await page.evaluate(()=>window.smoke.stopCalls);
 await page.locator('#stop-button').click();
 await page.waitForFunction(count=>window.smoke.stopCalls>count,stopped,{timeout:2000}).catch(()=>regressions.push('Stop must reach the engine when saving the draft fails'));
 await page.evaluate(()=>{window.smoke.failDraft=false;window.smoke.emit({busy:false,error:''});});
 await page.locator('#attach-button').click();
 await page.waitForFunction(()=>window.smoke.draft?.images.length===1,null,{timeout:2000}).catch(()=>regressions.push('Adding an image must autosave without typing'));
 await page.getByRole('button',{name:'Remove image',exact:true}).click();
 await page.waitForFunction(()=>window.smoke.draft?.images.length===0,null,{timeout:2000}).catch(()=>regressions.push('Removing an image must autosave without typing'));
 assert.deepEqual(regressions,[]);
 await page.evaluate(()=>window.smoke.emit({account:{status:'required',message:'Sign in to Muse'}}));
 assert.equal(await page.locator('#send-button').isDisabled(),true);
 await page.locator('#settings-button').click();await page.locator('#sign-in').click();
 await page.waitForFunction(()=>document.querySelector('#login-code').textContent==='DEMO-CODE');
 assert.equal(await page.locator('#sign-in').isVisible(),false);
 await page.locator('#cancel-sign-in').click();
 await page.waitForFunction(()=>document.querySelector('#login-code').hidden);
 await page.locator('#settings-close').click();
 await clickControl(page,'create-project');
 await page.getByRole('textbox',{name:'Project name',exact:true}).fill('First app');
 await page.getByRole('button',{name:'Choose parent folder',exact:true}).click();
 await page.getByRole('button',{name:'Create project',exact:true}).click();
 await page.waitForFunction(()=>window.smoke.projectsCreated.length===1);
 assert.equal(await page.evaluate(()=>window.smoke.projectsCreated[0].name),'First app');
 await clickControl(page,'create-project');await page.getByRole('textbox',{name:'Project name',exact:true}).fill('Plain site');await page.getByRole('button',{name:'Project starter',exact:true}).click();await page.getByRole('menuitemradio',{name:'Plain HTML/CSS/JS website',exact:true}).click();await page.getByRole('button',{name:'Choose parent folder',exact:true}).click();await page.getByRole('button',{name:'Create project',exact:true}).click();await page.waitForFunction(()=>window.smoke.projectsCreated.length===2);assert.equal(await page.evaluate(()=>window.smoke.projectsCreated[1].starter),'static');
 await page.evaluate(()=>window.smoke.emit({projectPath:'C:\\Projects\\First app',projectWork:{root:'C:\\Projects\\First app',run:{status:'ready',url:'http://localhost:3000'},tests:{status:'failed',message:'Tests failed',results:[{script:'test',status:'failed',output:'failure'}]}},executionMode:'readonly'}));
 assert.equal(await page.locator('#error-banner').isVisible(),true,'Failed project checks must offer recovery without an engine error');assert.equal(await page.locator('#recovery-results').isVisible(),true);await page.locator('#recovery-results').click();assert.equal(await page.locator('#project-results').isVisible(),true);await page.locator('#recovery-results').click();assert.equal(await page.locator('#project-results').isVisible(),true);await clickControl(page,'project-output');
 await page.evaluate(()=>window.smoke.emit({projectPath:'C:\\Projects\\Other'}));assert.equal(await page.locator('#recovery-results').isVisible(),false,'Recovery output must belong to the selected project');await page.evaluate(()=>window.smoke.emit({projectPath:'C:\\Projects\\First app',error:''}));
 await clickControl(page,'export-project');await page.getByText('SHA-256: '+'a'.repeat(64),{exact:true}).waitFor();await page.getByRole('button',{name:'Copy checksum',exact:true}).click();assert.equal(await page.evaluate(()=>window.smoke.copied),'a'.repeat(64));await page.getByRole('button',{name:'Show ZIP in folder',exact:true}).click();assert.equal(await page.evaluate(()=>window.smoke.revealed),true);await page.getByRole('button',{name:'Close export',exact:true}).click();await page.locator('.export-dialog').waitFor({state:'detached'});assert.equal(await page.locator('#workspace-menu > summary').evaluate(e=>e===document.activeElement),true);
 await page.evaluate(()=>window.smoke.exportFails=true);await clickControl(page,'export-project');await page.getByText('Source limits exceeded.',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Copy checksum',exact:true}).isVisible(),false);await page.getByRole('button',{name:'Close export',exact:true}).click();await page.evaluate(()=>window.smoke.exportFails=false);
 await page.locator('#run-project').waitFor({state:'hidden'});assert.equal(await page.locator('#fix-tests').isDisabled(),true);
 await clickControl(page,'project-brief');await page.getByLabel('Shared project brief',{exact:true}).waitFor();
 assert.equal(await page.getByRole('button',{name:'Save brief',exact:true}).isDisabled(),true);
 await page.getByRole('button',{name:'Close brief',exact:true}).click();await page.locator('.brief-dialog').waitFor({state:'detached',timeout:1000});assert.equal(await page.locator('.brief-dialog').count(),0,'An untouched CRLF brief is not dirty');await clickControl(page,'project-brief');
 await page.evaluate(()=>window.smoke.emit({executionMode:'full'}));await page.getByLabel('Shared project brief',{exact:true}).fill('Goal: keep the shop simple');
 await page.getByRole('button',{name:'Save brief',exact:true}).click();await page.waitForFunction(()=>window.smoke.brief.text==='Goal: keep the shop simple');
 await page.getByRole('button',{name:'Close brief',exact:true}).click();
 await page.evaluate(()=>window.smoke.emit({executionMode:'readonly'}));
 await clickControl(page,'stop-project');assert.equal(await page.evaluate(()=>window.smoke.projectActions.at(-1)),'stop');
 await page.evaluate(()=>window.smoke.emit({projectWork:{root:'C:\\Projects\\First app',run:{status:'stopped'},tests:{status:'not checked'}}}));
 await page.evaluate(()=>window.smoke.emit({lastOutcome:{status:'finished',turnId:'request-undo',message:'Built your app',checkpointId:'cp1'}}));
 await page.evaluate(()=>{window.smoke.originalProjectCommand=window.muse.projectCommand;window.smoke.stopResolves=[];window.muse.projectCommand=async name=>{if(name==='stop')await new Promise(resolve=>window.smoke.stopResolves.push(resolve));};window.smoke.emit({projectWork:{root:'C:\\Projects\\First app',run:{status:'ready'},tests:{status:'not checked'}}});});
 await page.getByRole('button',{name:'Open preview',exact:true}).waitFor();
 await mkdir('artifacts/frontend-proof',{recursive:true});await page.screenshot({path:'artifacts/frontend-proof/timeline-outcome.png'});
 await page.getByRole('button',{name:'Undo this request',exact:true}).evaluate(button=>{button.click();button.click();});
 await page.waitForFunction(()=>window.smoke.stopResolves.length===2);
 await page.evaluate(()=>{window.smoke.emit({projectWork:{root:'C:\\Projects\\First app',run:{status:'stopped'},tests:{status:'not checked'}}});for(const resolve of window.smoke.stopResolves)resolve();window.muse.projectCommand=window.smoke.originalProjectCommand;});
 await page.locator('.checkpoint-dialog').first().waitFor();assert.equal(await page.locator('.checkpoint-dialog').count(),1,'Concurrent Undo opens one review');await page.getByRole('button',{name:'Close',exact:true}).click();
 await page.getByRole('button',{name:'Undo this request',exact:true}).click();
 await page.getByRole('button',{name:'Restore selected files'}).waitFor();
 await page.getByRole('button',{name:'Close',exact:true}).click();
 await clickControl(page,'checkpoints');await page.getByRole('button',{name:'Review restore'}).click();
 assert.equal(await page.locator('.checkpoint-dialog input[type=checkbox]').first().isChecked(),false);
 await page.locator('.checkpoint-dialog input[type=checkbox]').first().check();await page.locator('.checkpoint-dialog input[type=checkbox]').last().check();await page.getByRole('button',{name:'Restore selected files'}).click();
 await page.waitForFunction(()=>window.smoke.restores.length===1);assert.equal(await page.evaluate(()=>window.smoke.restores[0].allowConflicts),true);await page.getByRole('button',{name:'Close',exact:true}).click();
 await clickControl(page,'ai-tester');await page.getByLabel('What should work?').fill('Cart adds one item');await page.getByRole('button',{name:'Start report',exact:true}).click();
 assert.equal(await page.getByRole('button',{name:'Start report',exact:true}).isDisabled(),true);
 assert.equal(await page.locator('.tester-report b').count(),0);
 await page.getByRole('button',{name:'Stop testing',exact:true}).click();
 await page.locator('.tester-report summary').first().click();await page.getByRole('button',{name:'View evidence',exact:true}).click();await page.locator('.tester-report img').waitFor();
 await page.locator('.tester-report input[type=checkbox]').check();assert.equal(await page.getByRole('button',{name:'Repair selected issues',exact:true}).isEnabled(),false);await page.evaluate(()=>window.smoke.emit({executionMode:'full'}));assert.equal(await page.getByRole('button',{name:'Repair selected issues',exact:true}).isEnabled(),true);
 await page.screenshot({path:'artifacts/mora-tester-report.png'});
 await page.getByRole('button',{name:'Resume unfinished cases',exact:true}).click();assert.equal(await page.evaluate(()=>window.smoke.testerCalls.at(-1).action),'resume');
 await page.getByRole('button',{name:'Stop testing',exact:true}).click();await page.keyboard.press('Escape');await page.locator('.tester-dialog').waitFor({state:'detached'});
 await clickControl(page,'ai-tester');await page.getByRole('button',{name:'Saved reports',exact:true}).click();await page.locator('.tester-report button').first().click();assert.equal(await page.locator('.tester-report details').count(),2);await page.keyboard.press('Escape');
 await page.evaluate(()=>{window.smoke.websiteCalls=[];window.muse.websiteTesterCommand=async(action,payload)=>{window.smoke.websiteCalls.push({action,payload});if(action==='open')window.smoke.emit({websiteActive:true,website:{id:'site1',scope:{entryUrl:payload.url},request:payload.request,status:'manual',steps:[],findings:[],gaps:[]}});};window.smoke.emit({projectPath:null,websiteActive:false,testerActive:false,busy:false});});
 await clickControl(page,'website-tester');assert.equal(await page.getByRole('button',{name:'Repair selected issues',exact:true}).count(),0);
 await page.getByLabel('Website URL',{exact:true}).fill('https://example.com');await page.getByLabel('Workflow and expected result',{exact:true}).fill('Search finds matching results');await page.getByRole('button',{name:'Open website',exact:true}).click();
 assert.equal(await page.evaluate(()=>window.smoke.websiteCalls[0].payload.url),'https://example.com');assert.equal(await page.getByRole('button',{name:'Start checking',exact:true}).isEnabled(),true);
 await page.evaluate(()=>window.smoke.emit({website:{id:'site1',scope:{entryUrl:'https://example.com'},status:'awaiting permission',steps:[],findings:[],gaps:[],pending:{id:'permission1',control:'<b>Submit</b>',reason:'Review the interaction',step:{action:'click'}}}}));
 assert.equal(await page.locator('.website-permission b').count(),0);await page.getByRole('button',{name:'Allow once',exact:true}).click();assert.deepEqual(await page.evaluate(()=>window.smoke.websiteCalls.at(-1)),{action:'approve',payload:{id:'permission1',allow:true}});
 await page.evaluate(()=>window.smoke.emit({website:{id:'site1',scope:{entryUrl:'https://example.com'},status:'awaiting permission',steps:[],findings:[],gaps:[],cases:[{title:'Search timing',family:'timing',status:'queued'}],discovery:{states:[{title:'Search',url:'https://example.com'}],features:[],transitions:[],relations:[]},pending:{id:'case1',kind:'case',title:'Search timing',reason:'Review this exact case',steps:[{action:'type',targetLabel:'Search',value:'Tea'},{action:'assert',check:'textValue',expected:'Tea'}]}}}));
 assert.match(await page.locator('.website-permission').innerText(),/Tea/);await page.getByRole('button',{name:'Allow this case',exact:true}).click();assert.equal(await page.evaluate(()=>window.smoke.websiteCalls.at(-1).payload.id),'case1');
 await page.getByRole('button',{name:'Update testing focus',exact:true}).click();assert.equal(await page.evaluate(()=>window.smoke.websiteCalls.at(-1).action),'steer');
 await page.getByRole('tab',{name:'Setup',exact:true}).click();await page.getByText('Account, screen size and website limits',{exact:true}).click();await page.getByLabel('Exclude paths',{exact:true}).fill('/private');await page.getByRole('button',{name:'Update testing focus',exact:true}).click();assert.equal(await page.evaluate(()=>window.smoke.websiteCalls.at(-1).payload.scope.excludePaths),'/private');
 await page.evaluate(()=>window.smoke.emit({websiteActive:true,website:{id:'site1',scope:{entryUrl:'https://example.com'},request:'Search finds matching results',status:'manual',steps:[],findings:[],gaps:[],discovery:{states:[],features:[{id:'feature1',key:'k1',name:'Search',url:'https://example.com'}],transitions:[],relations:[]}}}));
 await page.getByRole('tab',{name:'Explore',exact:true}).click();await page.getByRole('button',{name:'Focus on Search',exact:true}).click();assert.deepEqual(await page.evaluate(()=>window.smoke.websiteCalls.at(-1)),{action:'focus',payload:{id:'feature1'}});
 await page.getByRole('tab',{name:'Teach',exact:true}).click();await page.getByRole('button',{name:'Record workflow',exact:true}).click();assert.deepEqual(await page.evaluate(()=>window.smoke.websiteCalls.at(-1)),{action:'teach',payload:{mode:'record'}});
 await page.evaluate(()=>window.smoke.emit({website:{id:'site1',scope:{entryUrl:'https://example.com'},status:'manual',steps:[],findings:[],gaps:[],teaching:{mode:'record',status:'recording',steps:[{action:'type',targetLabel:'Search',value:'<b>Tea</b>'}],errors:[]}}}));
 assert.equal(await page.locator('#website-pane-teach b').count(),0);assert.equal(await page.getByRole('button',{name:'Start checking',exact:true}).isDisabled(),true);await page.getByRole('button',{name:'Finish recording',exact:true}).click();assert.equal(await page.evaluate(()=>window.smoke.websiteCalls.at(-1).action),'finish-teaching');
 await page.evaluate(()=>window.smoke.emit({website:{id:'site1',scope:{entryUrl:'https://example.com'},status:'manual',steps:[],findings:[],gaps:[],teaching:{mode:'record',status:'review',steps:[{action:'type',targetLabel:'Search',value:'Tea'}],errors:[]}}}));
 await page.getByLabel('Demonstrated workflow expected outcome',{exact:true}).fill('Search shows Tea');await page.getByRole('button',{name:'Use this workflow',exact:true}).click();assert.deepEqual(await page.evaluate(()=>window.smoke.websiteCalls.at(-1)),{action:'use-teaching',payload:{expected:'Search shows Tea'}});
 await page.getByRole('tab',{name:'Reports',exact:true}).click();await page.getByLabel('Include masked screenshots in export',{exact:true}).check();await page.getByRole('button',{name:'Export HTML',exact:true}).click();assert.deepEqual(await page.evaluate(()=>window.smoke.websiteCalls.at(-1)),{action:'export',payload:{id:'site1',format:'html',includeEvidence:true}});
 await page.getByRole('button',{name:'Stop and close browser',exact:true}).click();assert.equal(await page.evaluate(()=>window.smoke.websiteCalls.at(-1).action),'stop');await page.evaluate(()=>window.smoke.emit({websiteActive:false}));await page.getByRole('button',{name:'Reopen saved report',exact:true}).click();assert.equal(await page.evaluate(()=>window.smoke.websiteCalls.at(-1).action),'reopen');await page.keyboard.press('Escape');
 await page.evaluate(()=>window.smoke.emit({sessionId:'long-chat',busy:false,websiteActive:false,projectPath:null,lastOutcome:null,items:Array.from({length:450},(_,i)=>({itemId:'long-'+i,kind:'agentMessage',status:'completed',text:'Saved reply '+i}))}));
 assert.equal(await page.locator('#messages > *').count(),200);await page.locator('#load-older').click();assert.equal(await page.locator('#messages > *').count(),400);
 await page.locator('#load-older').click();assert.equal(await page.locator('#messages > *').count(),450);assert.equal(await page.locator('#load-older').isVisible(),false);
 await page.evaluate(()=>window.smoke.emit({sessionId:'other-long-chat'}));assert.equal(await page.locator('#messages > *').count(),200);
 console.log('PASS deterministic UI: existing chat/project flows and website setup without a project, safe permission rendering, approval and Stop');
}finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
