import {previewOccluded} from './menu-ui.js';
import {formatContextReference} from './context-references.js';
const node=(tag,text='')=>{const element=document.createElement(tag);element.textContent=text;return element;};
export function setupContextNavigation(api,{update,error,flushDraft}) {
  if(!api.contextCommand)return ()=>{};
  let state={},generation=0,opener,working=false,navigationTarget=null;
  const button=node('button','Context & search');button.id='context-tools';button.type='button';button.className='context-tools';document.getElementById('quick-actions').after(button);
  const dialog=node('dialog'),heading=node('h2','Context & search'),tabs=node('div'),query=node('input'),status=node('p'),results=node('div'),close=node('button','Close');dialog.className='workspace-dialog context-dialog';dialog.setAttribute('aria-label','Context & search');query.type='search';query.maxLength=256;query.setAttribute('aria-label','Search saved messages or project logs');query.placeholder='Search messages…';status.setAttribute('role','status');results.className='context-results';tabs.className='context-tabs';let scope='search-chats',timer;
  for(const [action,label] of [['search-chats','Saved chats'],['search-logs','Project logs'],['handoff','Handoff'],['resolve','Attach context']]){const tab=node('button',label);tab.type='button';tab.dataset.action=action;tab.addEventListener('click',()=>{scope=action;generation++;results.replaceChildren();query.hidden=['handoff','resolve'].includes(scope);query.placeholder=scope==='search-logs'?'Search project logs…':'Search saved messages…';for(const other of tabs.children)other.setAttribute('aria-pressed',String(other===tab));if(scope==='resolve')attachForm();else if(scope==='handoff')run();else{query.focus();run();}});tabs.append(tab);}
  async function run() {
    clearTimeout(timer);const current=++generation,owner=state.sessionId;status.textContent='Searching…';results.replaceChildren();
    try{const response=await api.contextCommand(scope,{sessionId:owner,query:query.value});if(current!==generation||owner!==state.sessionId||!dialog.open)return;
      if(scope==='handoff'){const text=node('textarea');text.readOnly=true;text.value=response.text;text.setAttribute('aria-label','Recorded handoff summary');text.rows=14;const copy=node('button','Copy handoff');copy.addEventListener('click',()=>api.copyText(response.text).catch(error));results.append(text,copy);status.textContent=response.truncated?'Summary shortened to fit.':'Recorded facts; verification is labelled with its limits.';return;}
      status.textContent=`${response.total} matching messages${response.truncated?' · showing a bounded selection':''}${response.unavailable?` · ${response.unavailable} histories unavailable`:''}`;
      for(const hit of response.results){if(scope==='search-logs'){const row=node('div',`${hit.source} · line ${hit.line}\n${hit.excerpt}`);row.dir='auto';results.append(row);continue;}
        const open=node('button',`${hit.title||'Chat'}${hit.archived?' (archived)':''}\n${hit.excerpt}`);open.dir='auto';open.addEventListener('click',async()=>{if(working)return;const operation=++generation,startOwner=state.sessionId;working=true;open.disabled=true;const current=()=>operation===generation&&dialog.open;try{await flushDraft();if(!current()||startOwner!==state.sessionId)return;if(hit.sessionId!==state.sessionId){navigationTarget=hit.sessionId;const resumed=await api.resumeChat(hit.sessionId);if(!current()||![startOwner,hit.sessionId].includes(state.sessionId))return;update(resumed);}if(!current())return;const next=await api.contextCommand('jump',{sessionId:hit.sessionId,itemId:hit.itemId});if(!current()||state.sessionId!==hit.sessionId)return;update(next);dialog.close();requestAnimationFrame(()=>{if(state.sessionId===hit.sessionId)document.querySelector(`[data-message-id="${CSS.escape(hit.itemId)}"]`)?.scrollIntoView({block:'center'});});}catch(cause){if(current()){error(cause);status.textContent=cause.message;}}finally{working=false;navigationTarget=null;open.disabled=false;}});results.append(open);}
    }catch(cause){if(current===generation&&owner===state.sessionId){status.textContent=cause.message;}}
  }
  function attachForm(){status.textContent='Use @file(path) or @folder(path). Folders attach source names; files attach bounded text.';const kind=node('select'),path=node('input'),preview=node('button','Preview context'),add=node('button','Add reference');for(const value of ['file','folder']){const option=node('option',value);option.value=value;kind.append(option);}kind.setAttribute('aria-label','Context type');path.setAttribute('aria-label','Relative project path');path.placeholder='src/app.js';path.maxLength=1024;add.disabled=true;let reference,owner=state.sessionId;
    preview.addEventListener('click',async()=>{const operation=++generation;add.disabled=true;const value={kind:kind.value,path:path.value.trim()},current=()=>operation===generation&&owner===state.sessionId&&dialog.open&&scope==='resolve'&&results.contains(path)&&kind.value===value.kind&&path.value.trim()===value.path;if(!value.path){status.textContent='Enter a relative path, or . for the project folder.';return;}try{const response=await api.contextCommand('resolve',{sessionId:owner,references:[value]});if(!current())return;reference=value;status.textContent=response.text;add.disabled=false;}catch(cause){if(current())status.textContent=cause.message;}});
    for(const input of [kind,path])input.addEventListener('input',()=>{generation++;add.disabled=true;reference=null;});add.addEventListener('click',()=>{if(!reference||owner!==state.sessionId)return;const prompt=document.getElementById('prompt');prompt.value+=(prompt.value?'\n':'')+formatContextReference(reference.kind,reference.path);prompt.dispatchEvent(new Event('input'));dialog.close();prompt.focus();});results.append(kind,path,preview,add);path.focus();}
  dialog.append(heading,tabs,query,status,results,close);document.body.append(dialog);close.addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>{generation++;clearTimeout(timer);api.browserCommand?.('occlude',{hidden:previewOccluded()}).catch(()=>{});if(opener?.isConnected)opener.focus();});query.addEventListener('input',()=>{generation++;clearTimeout(timer);timer=setTimeout(run,180);});button.addEventListener('click',()=>{opener=document.activeElement;dialog.showModal();api.browserCommand?.('occlude',{hidden:true}).catch(()=>{});tabs.querySelector('button').click();});
  return next=>{if(state.sessionId!==next.sessionId&&next.sessionId!==navigationTarget){generation++;if(dialog.open&&!working){dialog.close();}}state=next;};
}
