const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('muse', {
  getState: () => ipcRenderer.invoke('muse:get-state'),
  connect: () => ipcRenderer.invoke('muse:connect'),
  accountCommand: action => ipcRenderer.invoke('muse:account',action),
  chooseProjectParent: () => ipcRenderer.invoke('muse:project-parent'),
  createProject: payload => ipcRenderer.invoke('muse:create-project',payload),
  checkpointCommand: (action,payload) => ipcRenderer.invoke('muse:checkpoints',action,payload),
  projectCommand: action => ipcRenderer.invoke('muse:project-work',action),
  newChat: (projectPath = null) => ipcRenderer.invoke('muse:new-chat', projectPath),
  resumeChat: id => ipcRenderer.invoke('muse:resume-chat', id),
  deleteChat: id => ipcRenderer.invoke('muse:delete-chat', id),
  removeProject: projectPath => ipcRenderer.invoke('muse:remove-project', projectPath),
  renameChat: (id, title) => ipcRenderer.invoke('muse:rename-chat', id, title),
  sendMessage: message => ipcRenderer.invoke('muse:send', message),
  stopTurn: () => ipcRenderer.invoke('muse:stop'),
  queueCommand: (action,payload) => ipcRenderer.invoke('muse:queue',action,payload),
  saveDraft: draft => ipcRenderer.invoke('muse:save-draft',draft),
  chooseWorkspace: () => ipcRenderer.invoke('muse:choose-workspace'),
  chooseMuse: () => ipcRenderer.invoke('muse:choose-muse'),
  setOptions: options => ipcRenderer.invoke('muse:set-options', options),
  pickImages: () => ipcRenderer.invoke('muse:pick-images'),
  copyText: text => ipcRenderer.invoke('muse:copy-text', text),
  openLink: url => ipcRenderer.invoke('muse:open-link',url),
  browserCommand: (action, payload) => ipcRenderer.invoke('muse:browser', action, payload),
  stitchCommand: (action, payload) => ipcRenderer.invoke('muse:stitch', action, payload),
  trelloCommand: (action, payload) => ipcRenderer.invoke('muse:trello', action, payload),
  usageCommand: () => ipcRenderer.invoke('muse:usage'),
  onEvent: callback => { const listener = (_event, value) => callback(value); ipcRenderer.on('muse:event', listener); return () => ipcRenderer.removeListener('muse:event', listener); }
});
