const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('muse', {
  getState: () => ipcRenderer.invoke('muse:get-state'),
  connect: () => ipcRenderer.invoke('muse:connect'),
  accountCommand: action => ipcRenderer.invoke('muse:account',action),
  chooseProjectParent: () => ipcRenderer.invoke('muse:project-parent'),
  createProject: payload => ipcRenderer.invoke('muse:create-project',payload),
  checkpointCommand: (action,payload) => ipcRenderer.invoke('muse:checkpoints',action,payload),
  projectCommand: action => ipcRenderer.invoke('muse:project-work',action),
  testerCommand: (action,payload) => ipcRenderer.invoke('muse:tester',action,payload),
  websiteTesterCommand: (action,payload) => ipcRenderer.invoke('muse:website-tester',action,payload),
  newChat: (projectPath = null) => ipcRenderer.invoke('muse:new-chat', projectPath),
  resumeChat: id => ipcRenderer.invoke('muse:resume-chat', id),
  deleteChat: id => ipcRenderer.invoke('muse:delete-chat', id),
  chatMetadata: (id,action,title) => ipcRenderer.invoke('muse:chat-metadata',id,action,title),
  notificationOptions: enabled => ipcRenderer.invoke('muse:notification-options',enabled),
  sendMessage: message => ipcRenderer.invoke('muse:send', message),
  stopTurn: () => ipcRenderer.invoke('muse:stop'),
  queueCommand: (action,payload) => ipcRenderer.invoke('muse:queue',action,payload),
  saveDraft: draft => ipcRenderer.invoke('muse:save-draft',draft),
  chooseWorkspace: () => ipcRenderer.invoke('muse:choose-workspace'),
  chooseMuse: () => ipcRenderer.invoke('muse:choose-muse'),
  setOptions: options => ipcRenderer.invoke('muse:set-options', options),
  pickImages: () => ipcRenderer.invoke('muse:pick-images'),
  copyText: text => ipcRenderer.invoke('muse:copy-text', text),
  openLink: url => ipcRenderer.invoke('muse:open-link',url),
  browserCommand: (action, payload) => ipcRenderer.invoke('muse:browser', action, payload),
  stitchCommand: (action, payload) => ipcRenderer.invoke('muse:stitch', action, payload),
  onEvent: callback => { const listener = (_event, value) => callback(value); ipcRenderer.on('muse:event', listener); return () => ipcRenderer.removeListener('muse:event', listener); }
});
