import {websiteCoverage} from './website-coverage.js';

export function setupWebsiteTester(api,onError) {
  const button=document.getElementById('website-tester');let state={},dialog,status,results,permission,teachingPanel,url,request,role,origins,resources,include,exclude,viewport,mode,actions,minutes,accessibility,replay,open,start,steer,pause,stop,saveLogin,forgetLogin,pick,record,finishTeaching,saveTeaching,focusSelected,expected,reopen,exportHtml,exportJson,includeEvidence,signature='',teachingSignature='',permissionSignature='',lastOpen,lastReport;
  const el=(tag,text)=>{const node=document.createElement(tag);if(text!==undefined)node.textContent=text;return node;};
  const command=async(action,payload)=>{try{return await api.websiteTesterCommand(action,payload);}catch(error){onError(error);if(status)status.textContent=(error.message||String(error)).replace(/^Error invoking remote method '[^']+': Error: /,'');}};
  function evidence(parent,reportId,screenshot){if(!screenshot)return;const view=el('button','View screenshot');view.type='button';view.addEventListener('click',async()=>{const data=await command('evidence',{id:reportId,name:screenshot.name});if(data){const image=el('img');image.src='data:image/png;base64,'+data;image.alt='Website evidence with input fields masked';parent.append(image);view.remove();}});parent.append(view);}
  function draw(){
    if(!dialog)return;const r=state.website,active=!!state.websiteActive,running=['running','awaiting permission','opening'].includes(r?.status);
    const teaching=['recording','selecting'].includes(r?.teaching?.status);
    open.disabled=active||!!state.busy||!!state.testerActive;start.disabled=!active||running||teaching||state.connection!=='ready';steer.disabled=!active||teaching||r?.status==='opening'||state.connection!=='ready';pause.disabled=!active||r?.status==='opening';stop.disabled=!active;saveLogin.disabled=!active||running||teaching;forgetLogin.disabled=!r||running;
    pick.disabled=record.disabled=!active||r?.status==='opening'||teaching;finishTeaching.disabled=!teaching;saveTeaching.disabled=!active||r?.teaching?.status!=='review'||r.teaching.mode!=='record'||!!r.teaching.errors?.length||!!r.teaching.truncated;focusSelected.disabled=!active||!r?.teaching?.selection||teaching||state.connection!=='ready';
    reopen.disabled=active||!r;exportHtml.disabled=exportJson.disabled=!r||running||teaching;
    for(const input of [url,role,origins,resources,viewport])input.disabled=active;
    if(r?.id!==lastReport){lastReport=r?.id;if(r){url.value=r.scope.entryUrl;request.value=r.request||'';role.value=r.scope.roleId||'guest';include.value=(r.scope.includePaths||[]).join(', ');exclude.value=(r.scope.excludePaths||[]).join(', ');if(r.options){mode.value=r.options.mode;actions.value=r.options.maxActions;minutes.value=r.options.maxMs/60000;accessibility.checked=r.options.accessibility;replay.checked=r.options.replay;}}}
    status.textContent=r?`${r.status} · ${r.message||''}`:'Enter a URL. No project folder is needed.';
    const nextTeaching=JSON.stringify(r?.teaching);if(nextTeaching!==teachingSignature){teachingSignature=nextTeaching;teachingPanel.replaceChildren();const t=r?.teaching;if(t){teachingPanel.append(el('p',`${t.status}${t.selection?' · Selected: '+t.selection.targetLabel:''}${t.truncated?' · Too many actions; record a shorter workflow.':''}`));const list=el('ol');for(const s of t.steps||[])list.append(el('li',`${s.action} · ${s.targetLabel}${s.value?' → '+s.value:''}`));teachingPanel.append(list);for(const error of t.errors||[])teachingPanel.append(el('p',error));}}
    const next=JSON.stringify(r);if(next===signature)return;signature=next;const expanded=[...results.querySelectorAll('details[open]')].map(d=>d.firstElementChild?.textContent);results.replaceChildren();if(!r){permission.replaceChildren();return;}
    const nextPermission=JSON.stringify(r.pending);if(nextPermission!==permissionSignature){permissionSignature=nextPermission;permission.replaceChildren();if(r.pending){
      const p=r.pending,isCase=p.kind==='case';permission.append(el('strong',isCase?(p.replay?'Approve exact reproduction':'Approve this short test case'):'Approve an interaction on the live website'),el('p',p.reason));
      if(isCase){permission.append(el('p',p.title));const list=el('ol');for(const step of p.steps){list.append(el('li',`${step.action} · ${step.targetLabel||step.target||''}${step.value?' → '+step.value:''}${step.action==='assert'?' · '+step.check+' expected '+String(step.expected):''}${step.guard?' · Requires: '+step.guard:''}`));}permission.append(list);}
      else permission.append(el('p',`${p.step.action} · ${p.control||p.step.value||''}${p.step.action==='type'?' → '+p.step.value:''}`));
      const allow=el('button',isCase?(p.replay?'Allow replay':'Allow this case'):'Allow once'),deny=el('button','Decline');allow.type=deny.type='button';for(const control of [allow,deny])control.addEventListener('click',()=>{allow.disabled=deny.disabled=true;command('approve',{id:p.id,allow:control===allow});});permission.append(allow,deny);
    }}
    const coverage=websiteCoverage(r),map=r.discovery;if(map){results.append(el('h3','Discovered'),el('p',`${coverage.states} states · ${coverage.controls} discovered controls · ${coverage.exercised} exercised · ${coverage.checked} with assertions · ${coverage.unchecked} without assertions · ${map.relations.filter(r=>r.status==='observed').length} observed relationships`));const views=el('details');views.append(el('summary','Pages and states'));const list=el('ul');for(const view of map.states.slice(-30))list.append(el('li',`${view.title||view.url} · ${view.roleId||'guest'} · ${view.summary||''}`));views.append(list);results.append(views);
      const features=el('details');features.append(el('summary','Choose a discovered feature'));for(const feature of map.features){const row=el('p'),focus=el('button','Focus on '+feature.name);focus.type='button';focus.disabled=!active||teaching||state.connection!=='ready';focus.addEventListener('click',()=>command('focus',{id:feature.id}));row.append(focus,el('span',' · '+feature.url));features.append(row);}results.append(features);}
    const counts={passed:0,failed:0,blocked:0};for(const step of r.steps||[])if(step.result?.status in counts)counts[step.result.status]++;
    results.append(el('h3','Checked outcomes'),el('p',`${counts.passed} passed assertions · ${counts.failed} failed assertions · ${counts.blocked} blocked · ${r.actions||0} browser operations`));
    if(r.metrics)results.append(el('p',`${Math.round(r.metrics.elapsedMs/1000)} seconds · ${r.metrics.decisions} planning decisions · ${r.metrics.checksPerMinute||0} checks/minute in this run`));
    const current=r.cases?.find(c=>c.status==='running');if(current)results.append(el('h3','Testing now'),el('p',current.title));if(r.focus)results.append(el('p','Priority: '+r.focus.name));if(r.workflows?.length)results.append(el('p',`${r.workflows.length} demonstrated workflows saved. Each run still needs a fresh plan and approval.`));
    const cases=el('ul');for(const c of r.cases||[])cases.append(el('li',`${c.title} · ${c.family} · ${c.status}${c.reason?' — '+c.reason:''}${c.replayReason?' — '+c.replayReason:''}`));results.append(cases);
    results.append(el('h3','Findings'));
    if(!r.findings?.length)results.append(el('p','No findings recorded. Review untested and blocked behavior before drawing conclusions.'));
    for(const finding of r.findings||[]){const row=el('details');row.append(el('summary',`${finding.title||'Expected outcome'} · ${finding.status}`),el('p',`Confidence: ${finding.confidence||'observed'} · Severity: ${finding.severity||'unrated'}\n${finding.url||''}\n${finding.impact||''}`));if(finding.kind!=='accessibility')row.append(el('p',`Expected: ${String(finding.expected)}\nObserved: ${String(finding.actual)}\nBasis: ${finding.basis}`));else{row.append(el('p',`${finding.ruleId} · ${JSON.stringify(finding.target)}`));if(/^https:\/\/dequeuniversity\.com\//.test(finding.helpUrl||'')){const link=el('a','Accessibility rule guidance');link.href=finding.helpUrl;link.target='_blank';link.rel='noopener noreferrer';row.append(link);}}results.append(row);}
    const scans=r.accessibility||[];if(scans.length){results.append(el('h3','Accessibility'),el('p',`${scans.length} states scanned · ${scans.reduce((n,s)=>n+s.incomplete.length,0)} inconclusive rule results need manual review. Automated scans do not establish accessibility conformance.`));for(const scan of scans){const row=el('details');row.append(el('summary',`${scan.url} · ${scan.violations.length} rule violations · ${scan.incomplete.length} need review`));for(const item of scan.incomplete)row.append(el('p',`${item.id}: ${item.help||'Manual review needed'}`));evidence(row,r.id,scan.screenshot);results.append(row);}}
    const timeline=el('details');timeline.open=true;timeline.append(el('summary','Action and evidence timeline'));const steps=el('ol');
    for(const step of r.steps||[]){const row=el('li');row.append(el('span',`${step.action.action} ${step.control||step.action.target||''} — ${step.result?.status||step.status}`));if(step.action.action==='assert')row.append(el('p',`Expected: ${String(step.action.expected)}\nBasis: ${step.action.basis}\nObserved: ${step.result?.actual??'not checked'}`));if(step.result?.reason)row.append(el('p',step.result.reason));evidence(row,r.id,step.result?.screenshot);steps.append(row);}timeline.append(steps);results.append(timeline);
    if(r.blockedOrigins?.length)results.append(el('p',`Blocked dependencies or navigation: ${r.blockedOrigins.join(', ')}. Close the browser and add an origin to the appropriate scope field if required.`));
    results.append(el('h3','Not tested'),el('p',[...(r.gaps||[]),'Coverage describes observed behavior only. Other accounts require supplied logins. Service workers, downloads, canvas and drag-and-drop remain unsupported. Autonomous coverage is experimental.'].join('\n')));
    for(const details of results.querySelectorAll('details'))if(expanded.includes(details.firstElementChild?.textContent))details.open=true;
  }
  function show(seed={}){
    if(dialog){if(seed.url&&!state.websiteActive)url.value=seed.url;return;}
    dialog=el('dialog');dialog.className='tester-dialog website-dialog';dialog.setAttribute('aria-label','Website tester');
    dialog.append(el('h2','Website tester'),el('p','Discover a website and test its observed behavior. Mora uses rendered pages without source or repair tools. Page text is sent to your connected AI; use test accounts and avoid sensitive pages.'));
    const form=el('form');const field=(name,tag='input')=>{const label=el('label',name),input=el(tag);input.setAttribute('aria-label',name);label.append(input);form.append(label);return input;};
    const select=(name,choices,value)=>{const input=field(name,'select');for(const [id,label] of choices){const option=el('option',label);option.value=id;input.append(option);}input.value=value;return input;};
    url=field('Website URL');url.type='url';url.required=true;url.placeholder='https://example.com';url.value=seed.url||state.website?.scope.entryUrl||'';
    request=field('Workflow and expected result','textarea');request.rows=3;request.maxLength=12000;request.placeholder='Describe the behavior or rules Mora should check.';request.value=seed.request||state.website?.request||'';
    mode=select('What to test',[['workflow','Selected workflow'],['page','This page and its states'],['site','Discover and test this website']],state.website?.options?.mode||'workflow');
    role=field('Account label');role.value=state.website?.scope.roleId||'guest';role.maxLength=60;viewport=select('Screen size',[['desktop','Desktop'],['mobile','Mobile viewport']],state.website?.scope.viewport||'desktop');
    const advanced=el('details'),summary=el('summary','Website scope and limits');advanced.append(summary);form.append(advanced);
    function scopeField(name){const input=field(name);input.placeholder='Optional, comma separated';advanced.append(input.parentElement);return input;}
    origins=scopeField('Additional navigation origins');resources=scopeField('Additional resource origins');include=scopeField('Include paths');exclude=scopeField('Exclude paths');
    for(const [input,value] of [[origins,state.website?.scope.navigationOrigins?.slice(1)],[resources,state.website?.scope.resourceOrigins?.filter(v=>!state.website.scope.navigationOrigins?.includes(v))],[include,state.website?.scope.includePaths],[exclude,state.website?.scope.excludePaths]])input.value=(value||[]).join(', ');
    actions=scopeField('Maximum browser operations');actions.type='number';actions.min='1';actions.max='500';actions.value=state.website?.options?.maxActions||100;minutes=scopeField('Time limit in minutes');minutes.type='number';minutes.min='1';minutes.max='60';minutes.value=(state.website?.options?.maxMs||900000)/60000;
    accessibility=field('Run accessibility scans');accessibility.type='checkbox';accessibility.checked=state.website?.options?.accessibility!==false;advanced.append(accessibility.parentElement);replay=field('Offer exact reproduction of failures');replay.type='checkbox';replay.checked=state.website?.options?.replay!==false;advanced.append(replay.parentElement);
    advanced.append(el('p','Navigation origins allow pages and login redirects. Resource origins allow supporting APIs, images and fonts. Paths start with /. Wider scope shares the same testing budget. Each short case needs explicit approval.'));
    const options=()=>({mode:mode.value,maxActions:Number(actions.value),maxDecisions:Math.min(750,Math.max(20,Number(actions.value)*2)),maxMs:Number(minutes.value)*60000,accessibility:accessibility.checked,replay:replay.checked});
    open=el('button','Open website');open.type='submit';form.append(open);form.addEventListener('submit',async event=>{event.preventDefault();open.disabled=true;await command('open',{url:url.value,request:request.value,roleId:role.value,viewport:viewport.value,navigationOrigins:origins.value,resourceOrigins:resources.value,includePaths:include.value,excludePaths:exclude.value,options:options()});draw();});
    const controls=el('div');controls.className='tester-controls';function control(label,handler){const node=el('button',label);node.type='button';node.addEventListener('click',handler);controls.append(node);return node;}
    start=control('Start checking',()=>command('start',{request:request.value,options:options()}));steer=control('Update testing focus',()=>command('steer',{request:request.value,options:options(),scope:{includePaths:include.value,excludePaths:exclude.value}}));pause=control('Take over / sign in',()=>command('takeover'));saveLogin=control('Save this login',()=>command('save-login'));forgetLogin=control('Forget saved login',()=>command('forget-login'));stop=control('Stop and close browser',()=>command('stop'));
    const teach=el('details');teach.append(el('summary','Select a control or demonstrate a workflow'),el('p','Sign in first. Selection highlights a control without activating it. Recording follows your real actions on the website, including any changes you make. Finish here after up to eight actions, then describe the expected outcome. Private fields are excluded.'));
    pick=control('Select in browser',()=>command('teach',{mode:'pick'}));record=control('Record workflow',()=>command('teach',{mode:'record'}));finishTeaching=control('Finish recording',()=>command('finish-teaching'));focusSelected=control('Focus on selected control',()=>command('focus',{id:'selected'}));
    expected=field('Demonstrated workflow expected outcome','textarea');expected.maxLength=4000;expected.rows=2;
    saveTeaching=control('Use this workflow',async()=>{const value=await command('use-teaching',{expected:expected.value});if(value?.request)request.value=value.request;});teachingPanel=el('section');teachingPanel.setAttribute('aria-label','Recorded workflow');teach.append(pick,record,finishTeaching,focusSelected,teachingPanel,expected.parentElement,saveTeaching);
    reopen=control('Reopen saved report',()=>command('reopen',{id:state.website.id}));includeEvidence=field('Include masked screenshots in export');includeEvidence.type='checkbox';
    const exportReport=async format=>{const result=await command('export',{id:state.website.id,format,includeEvidence:includeEvidence.checked});if(result?.saved)status.textContent='Saved '+result.name;};
    exportHtml=control('Export HTML',()=>exportReport('html'));exportJson=control('Export JSON',()=>exportReport('json'));controls.append(includeEvidence.parentElement);
    control('Saved reports',async()=>{if(state.websiteActive){onError(Error('Close the website browser before opening history.'));return;}const saved=await command('list');if(!saved)return;results.replaceChildren();signature='';for(const item of saved){const load=el('button',`${new Date(item.createdAt).toLocaleString()} · ${item.scope.entryUrl} · ${item.status}`);load.type='button';load.addEventListener('click',()=>command('load',{id:item.id}));results.append(load);}if(!saved.length)results.append(el('p','No website reports yet.'));});
    control('Close panel',()=>dialog.close());status=el('p');status.setAttribute('role','status');status.setAttribute('aria-live','polite');permission=el('section');permission.className='website-permission';permission.setAttribute('aria-label','Website action permission');results=el('section');results.className='tester-report';
    dialog.append(form,controls,teach,status,permission,results);dialog.addEventListener('close',()=>{dialog.remove();dialog=null;signature=teachingSignature=permissionSignature='';lastReport=undefined;api.browserCommand?.('occlude',{hidden:false}).catch(()=>{});button.focus();});api.browserCommand?.('occlude',{hidden:true}).catch(()=>{});document.body.append(dialog);dialog.showModal();draw();url.focus();
  }
  button.addEventListener('click',()=>show());
  return next=>{state=next;button.disabled=!!state.loading||!!state.testerActive;if(state.websiteOpen?.id!==lastOpen){lastOpen=state.websiteOpen?.id;if(lastOpen)show(state.websiteOpen);}draw();};
}
