import {websiteCoverage} from './website-coverage.js';

const tabs=['Setup','Overview','Tests','Findings','Explore','Evidence','Teach','Reports'];
const labels={manual:'Ready for you',running:'Testing',opening:'Opening browser','awaiting permission':'Approval needed',done:'Run finished',paused:'Paused',stopped:'Stopped',blocked:'Needs attention',passed:'Passed','observed failure':'Failed once','reproduced finding':'Reproduced',queued:'Waiting','not tested':'Not tested','needs clarification':'Needs a rule',replanned:'Plan corrected'};
const attention=['blocked','needs clarification','not tested','observed failure','reproduced finding'];
const el=(tag,text,className)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(className)n.className=className;return n;};
const value=v=>typeof v==='object'?JSON.stringify(v):String(v??'Not recorded');
const badge=v=>el('span',labels[v]||v||'Unknown','website-badge '+(['passed','done'].includes(v)?'good':attention.includes(v)||v==='awaiting permission'?'attention':''));
function empty(parent,title,text){const box=el('div',undefined,'website-empty');box.append(el('h3',title),el('p',text));parent.append(box);}

export function setupWebsiteTester(api,onError){
 const button=document.getElementById('website-tester');let state={},dialog,tab='Setup',lastOpen,lastReport,signature='',permissionSignature='',history=[],historyLoaded=false,evidenceCase='',evidenceStep='';
 let panes={},nav={},f={},c={},views={},status,errorBox,notice,permission,identity,form,teachingPanel;
 const images=new Map(),approved=new Set(),pending=new Set();
 const btn=(text,handler,cls)=>{const n=el('button',text,cls);n.type='button';n.addEventListener('click',handler);return n;};
 const command=async(action,payload)=>{if(pending.has(action)&&!['evidence','list'].includes(action))return;pending.add(action);if(errorBox)errorBox.hidden=true;draw();try{return await api.websiteTesterCommand(action,payload);}catch(error){onError(error);if(errorBox){errorBox.textContent=(error.message||String(error)).replace(/^Error invoking remote method '[^']+': Error: /,'');errorBox.hidden=false;}return {commandFailed:true};}finally{pending.delete(action);draw();}};
 function setTab(name,{focus=false}={}){tab=name;for(const item of tabs){panes[item].hidden=item!==name;nav[item].setAttribute('aria-selected',String(item===name));nav[item].tabIndex=item===name?0:-1;}if(focus)nav[name].focus();}
 function details(title,id){const box=el('details',undefined,'website-item');box.dataset.key=id;box.append(el('summary',title));return box;}
 function redraw(parent,render){
  const opened=new Set([...parent.querySelectorAll('details[open]')].map(n=>n.dataset.key)),focused=parent.contains(document.activeElement)?document.activeElement.dataset.focus:null;
  parent.replaceChildren();render();
  for(const node of parent.querySelectorAll('summary,button,a')){const group=node.closest('[data-key]')?.dataset.key||'view';node.dataset.focus=group+'-'+(node.dataset.key||node.tagName+'-'+node.textContent);}
  for(const n of parent.querySelectorAll('details'))if(opened.has(n.dataset.key))n.open=true;
  if(focused)parent.querySelector(`[data-focus="${CSS.escape(focused)}"]`)?.focus({preventScroll:true});
 }
 function pair(parent,label,text){const row=el('div',undefined,'website-pair');row.append(el('strong',label),el('span',value(text)));parent.append(row);}
 function steps(parent,list){const ol=el('ol',undefined,'website-steps');for(const s of list||[]){const target=s.targetLabel||state.website?.discovery?.features?.find(f=>f.key===s.target)?.name||s.target||'';ol.append(el('li',`${s.action==='assert'?'Check':s.action} ${target}${s.value!==''&&s.value!=null?' → '+s.value:''}${s.action==='assert'?' · '+s.check+' = '+value(s.expected):''}${s.guard?' · Requires '+s.guard:''}`));}parent.append(ol);}
 function viewEvidence(caseId,stepId){evidenceCase=caseId||'';evidenceStep=stepId||'';f.activity.value='all';setTab('Evidence');renderEvidence();}
 function evidence(parent,reportId,screenshot){if(!screenshot?.name)return;const key=reportId+'/'+screenshot.name,cached=images.get(key);if(cached){const img=el('img');img.src='data:image/png;base64,'+cached;img.alt='Website evidence; input fields are masked';img.loading='lazy';parent.append(img);return;}const view=btn('View screenshot',async()=>{view.disabled=true;view.textContent='Loading screenshot…';const data=await command('evidence',{id:reportId,name:screenshot.name});if(typeof data==='string'&&lastReport===reportId){images.set(key,data);if(view.isConnected){evidence(parent,reportId,screenshot);view.remove();}}else if(view.isConnected){view.disabled=false;view.textContent='Retry screenshot';}});view.dataset.key='image-'+screenshot.name;parent.append(view);}
 function renderCases(){redraw(views.Tests,()=>{const all=state.website?.cases||[],query=f.caseSearch.value.toLowerCase(),filter=f.caseFilter.value,rows=all.filter(c=>(c.title+' '+c.family+' '+(c.reason||'')).toLowerCase().includes(query)&&(filter==='all'||filter==='attention'&&attention.includes(c.status)||c.status===filter));views.Tests.append(el('p',`${rows.length} of ${all.length} test cases`,'website-muted'));if(!rows.length)empty(views.Tests,all.length?'No matching tests':'Your test plan will appear here',all.length?'Try another search or status.':'Start checking to discover workflows and build cases with expected outcomes.');for(const record of rows){const row=details('',record.id);row.firstElementChild.append(el('span',record.title),badge(record.status));pair(row,'Test family',record.family);if(record.reason)pair(row,'Result',record.reason);if(record.replayReason)pair(row,'Reproduction',record.replayReason);pair(row,'Expected rule',record.grounding?.quote||'A supported requirement is still needed.');if(record.start)pair(row,'Starting page',record.start.url+' · '+record.start.roleId);if(record.precondition)pair(row,'Before testing',record.precondition);if(record.startChecks?.length){row.append(el('h4','Required starting conditions'));steps(row,record.startChecks);}row.append(el('h4','Planned steps'));steps(row,record.steps);if(record.reset?.length){row.append(el('h4','Setup before retrying'));steps(row,record.reset);}if(record.executions?.length)row.append(btn('View evidence',()=>viewEvidence(record.id)));views.Tests.append(row);}});}
 function renderFindings(){redraw(views.Findings,()=>{const all=state.website?.findings||[],rank={critical:0,high:1,serious:1,moderate:2,medium:2,minor:3,low:3,unrated:4},rows=all.filter(r=>(r.title+' '+(r.impact||'')).toLowerCase().includes(f.findingSearch.value.toLowerCase())&&(f.findingFilter.value==='all'||r.kind===f.findingFilter.value)).sort((a,b)=>(rank[a.severity]??4)-(rank[b.severity]??4));if(!rows.length)empty(views.Findings,all.length?'No matching findings':'No findings recorded',all.length?'Try another search or category.':'Review blocked and untested behavior before drawing conclusions.');for(const record of rows){const row=details('',record.id);row.firstElementChild.append(el('span',record.title||'Expected outcome'),badge(record.status));pair(row,'Severity',record.severity||'Not rated');pair(row,'Confidence',record.confidence||'Observed');if(record.url)pair(row,'Page',record.url);if(record.impact)pair(row,'Impact',record.impact);if(record.kind!=='accessibility'){pair(row,'Expected',record.expected);pair(row,'Observed',record.actual);pair(row,'Supporting rule',record.basis);if(record.replay)pair(row,'Reproduction',record.replay.status+(record.replay.reason?' · '+record.replay.reason:''));}else{pair(row,'Accessibility rule',record.ruleId);pair(row,'Affected element',record.target);if(/^https:\/\/dequeuniversity\.com\//.test(record.helpUrl||'')){const link=el('a','Read accessibility rule guidance');link.href=record.helpUrl;link.target='_blank';link.rel='noopener noreferrer';row.append(link);}}if(record.caseId||record.stepId)row.append(btn('View evidence',()=>viewEvidence(record.caseId,record.stepId)));views.Findings.append(row);}});}
 function renderExplore(){redraw(views.Explore,()=>{const map=state.website?.discovery;if(!map){empty(views.Explore,'Discover the website','Pages, controls and observed relationships will appear as Mora explores.');return;}const rows=map.features.filter(r=>(r.name+' '+r.url).toLowerCase().includes(f.featureSearch.value.toLowerCase()));views.Explore.append(el('p',`${rows.length} matching controls · ${map.states.length} observed states · ${(map.relations||[]).filter(r=>r.status==='observed').length} observed relationships`,'website-muted'));for(const record of rows){const row=el('div',undefined,'website-feature'),text=el('div'),focus=btn('Focus here',()=>command('focus',{id:record.id}));focus.setAttribute('aria-label','Focus on '+record.name);focus.dataset.key=record.id;focus.disabled=!state.websiteActive||state.connection!=='ready'||['recording','selecting'].includes(state.website.teaching?.status);text.append(el('strong',record.name),el('p',record.family+' · '+record.url));row.append(text,focus);views.Explore.append(row);}const pages=details('Pages and states','pages');for(const view of map.states.slice(-30))pair(pages,view.title||view.url,view.url+' · '+view.roleId+'\n'+(view.summary||''));views.Explore.append(pages);if(!rows.length)empty(views.Explore,'No matching controls','Try another search or continue discovery.');});}
 function renderEvidence(){redraw(views.Evidence,()=>{const r=state.website,all=r?.steps||[],rows=all.filter(s=>(!evidenceCase||s.caseId===evidenceCase)&&(!evidenceStep||s.id===evidenceStep)&&(f.activity.value==='all'||s.result?.status===f.activity.value));if(evidenceCase||evidenceStep)views.Evidence.append(btn('Show all activity',()=>{evidenceCase=evidenceStep='';renderEvidence();}));views.Evidence.append(el('p',`${rows.length} of ${all.length} browser actions. Interactions alone are not passing tests.`,'website-muted'));if(!rows.length)empty(views.Evidence,'No matching activity','Evidence appears after an action. Try another filter.');for(const step of rows){const row=details('',step.id);row.firstElementChild.append(el('span',`${all.indexOf(step)+1}. ${step.action.action} ${step.control||''}`),badge(step.result?.status||step.status));if(evidenceStep===step.id)row.open=true;if(step.action.action==='assert'){pair(row,'Expected',step.action.expected);pair(row,'Observed',step.result?.actual);pair(row,'Supporting rule',step.action.basis);}if(step.result?.reason)pair(row,'Details',step.result.reason);if(step.at)pair(row,'Time',new Date(step.at).toLocaleTimeString());evidence(row,r.id,step.result?.screenshot);views.Evidence.append(row);}for(const scan of r?.accessibility||[]){const row=details(`Accessibility · ${scan.violations.length} violations · ${scan.incomplete.length} need review`,scan.id);pair(row,'Page',scan.url);for(const item of scan.incomplete)pair(row,item.id,item.help||'Manual review needed');evidence(row,r.id,scan.screenshot);views.Evidence.append(row);}});}
 function renderOverview(){redraw(views.Overview,()=>{const r=state.website;if(!r){empty(views.Overview,'Ready when you are','Open a website from Setup, sign in if needed, then start checking.');return;}const cases=r.cases||[],coverage=websiteCoverage(r),cards=el('div',undefined,'website-metrics');for(const [label,count] of [['Passed cases',cases.filter(c=>c.status==='passed').length],['Findings',r.findings?.length||0],['Need attention',cases.filter(c=>['blocked','needs clarification'].includes(c.status)).length],['Not tested',cases.filter(c=>['queued','not tested'].includes(c.status)).length]]){const card=el('div');card.append(el('strong',count),el('span',label));cards.append(card);}views.Overview.append(cards);const activity=el('div',undefined,'website-callout');activity.append(el('h3',cases.find(c=>c.status==='running')?.title||labels[r.status]||r.status),el('p',r.message||''));if(r.focus)activity.append(el('p','Current priority: '+r.focus.name));views.Overview.append(activity);if(r.metrics&&r.options)for(const [label,used,limit] of [['Browser operations',r.metrics.actions,r.options.maxActions],['Minutes used',Math.round((r.metrics.elapsedMs||0)/6000)/10,r.options.maxMs/60000]]){const row=el('label',`${label}: ${used} / ${limit}`),bar=el('progress');bar.max=limit||1;bar.value=used||0;bar.setAttribute('aria-label',label);row.append(bar);views.Overview.append(row);}views.Overview.append(el('h3','Observed coverage'),el('p',`${coverage.controls} controls discovered · ${coverage.exercised} exercised · ${coverage.checked} with outcome checks · ${coverage.unchecked} without outcome checks.`),el('p','These counts describe observed controls, not a percentage of the whole website.','website-muted'),el('h3','Remaining gaps'));const gaps=el('ul');for(const gap of r.gaps||[])gaps.append(el('li',gap));for(const origin of r.blockedOrigins||[])gaps.append(el('li','Blocked dependency: '+origin+'. Stop the browser and adjust permitted domains in Setup if needed.'));if(!gaps.childElementCount)gaps.append(el('li','No specific gap recorded yet. This does not establish complete coverage.'));views.Overview.append(gaps);const limits=details('Testing limits','limits');limits.append(el('p','Autonomous coverage is experimental. Other accounts need supplied logins. Downloads, service workers, canvas and drag-and-drop are unsupported. Automated accessibility scans do not establish conformance. Reloading cannot undo saved website changes.'));views.Overview.append(limits);});}
 function renderHistory(){redraw(views.Reports,()=>{const rows=history.filter(r=>(r.scope.entryUrl+' '+r.status+' '+r.scope.roleId).toLowerCase().includes(f.historySearch.value.toLowerCase()));if(!rows.length)empty(views.Reports,historyLoaded?'No matching saved reports':'Your previous runs','Refresh reports to load saved runs. Stop the current browser before loading another report.');for(const record of rows){const row=el('div',undefined,'website-feature'),text=el('div'),load=btn('Open report',()=>command('load',{id:record.id}));text.append(el('strong',record.scope.entryUrl),el('p',new Date(record.createdAt).toLocaleString()+' · '+record.scope.roleId+' · '+(labels[record.status]||record.status)));load.disabled=!!state.websiteActive;row.append(text,load);views.Reports.append(row);}});}
 function renderTeaching(){redraw(teachingPanel,()=>{const t=state.website?.teaching;if(!t){empty(teachingPanel,'Show Mora a workflow','Select a control to focus testing, or record up to eight real actions and describe the expected result.');return;}teachingPanel.append(el('h3',t.status==='recording'?`Recording · ${t.steps?.length||0} / 8 actions`:t.status==='selecting'?'Choose a control in the browser':t.status==='review'?'Review your demonstration':t.status));if(t.selection)pair(teachingPanel,'Selected control',t.selection.targetLabel);steps(teachingPanel,t.steps);for(const message of t.errors||[])teachingPanel.append(el('p',message,'website-warning'));if(t.truncated)teachingPanel.append(el('p','This recording is incomplete. Record a shorter workflow.','website-warning'));});}
 function drawPermission(){const p=state.website?.pending,next=JSON.stringify(p);if(next===permissionSignature)return;permissionSignature=next;permission.replaceChildren();permission.hidden=!p;if(!p)return;permission.append(el('h3',p.replay?'Review reproduction':'Review live website actions'),el('p',p.title||p.reason));if(p.title)permission.append(el('p',p.reason));const sequence=el('div',undefined,'website-permission-steps');steps(sequence,p.kind==='case'?p.steps:[{...p.step,targetLabel:p.control}]);if(p.startingConditions?.length){sequence.append(el('strong','Required starting conditions'));steps(sequence,p.startingConditions);}permission.append(sequence);const allow=btn(p.kind==='case'?(p.replay?'Allow replay':'Allow this case'):'Allow once',()=>reply(true),'website-primary'),deny=btn('Decline',()=>reply(false));const reply=async allowed=>{if(approved.has(p.id))return;approved.add(p.id);allow.disabled=deny.disabled=true;const result=await command('approve',{id:p.id,allow:allowed});if(result?.commandFailed&&state.website?.pending?.id===p.id){approved.delete(p.id);allow.disabled=deny.disabled=false;}};allow.disabled=deny.disabled=approved.has(p.id);permission.append(allow,deny);}
 function draw(){if(!dialog)return;const r=state.website,active=!!state.websiteActive,running=['running','awaiting permission','opening'].includes(r?.status),teaching=['recording','selecting'].includes(r?.teaching?.status),ready=state.connection==='ready';
  c.open.disabled=active||!!state.busy||!!state.testerActive||pending.has('open');c.start.disabled=!active||running||teaching||!ready||pending.has('start');c.steer.disabled=!active||teaching||r?.status==='opening'||!ready||pending.has('steer');c.pause.disabled=!active||r?.status==='opening'||pending.has('takeover');c.stop.disabled=!active||pending.has('stop');c.saveLogin.disabled=!active||running||teaching;c.forgetLogin.disabled=!r||running;c.reopen.disabled=active||!r||pending.has('reopen');c.exportHtml.disabled=c.exportJson.disabled=!r||running||teaching;c.pick.disabled=c.record.disabled=!active||r?.status==='opening'||teaching;c.finish.disabled=!teaching;c.useTeaching.disabled=!active||r?.teaching?.status!=='review'||r.teaching.mode!=='record'||!!r.teaching.errors?.length||!!r.teaching.truncated||!f.expected.value.trim();c.focus.disabled=!active||!r?.teaching?.selection||teaching||!ready;
  for(const node of dialog.querySelectorAll('[data-actions]'))node.setAttribute('aria-pressed',String(Number(node.dataset.actions)===Number(f.actions.value)&&Number(node.dataset.minutes)===Number(f.minutes.value)));c.open.hidden=active;c.start.hidden=c.steer.hidden=c.pause.hidden=c.stop.hidden=!active;
  for(const name of ['url','role','origins','resources','viewport'])f[name].disabled=active;
  if(r?.id!==lastReport){lastReport=r?.id;images.clear();approved.clear();evidenceCase=evidenceStep='';f.caseSearch.value=f.findingSearch.value=f.featureSearch.value='';f.caseFilter.value=f.findingFilter.value='all';if(r){for(const [name,text] of Object.entries({url:r.scope.entryUrl,request:r.request||'',role:r.scope.roleId||'guest',viewport:r.scope.viewport||'desktop',mode:r.options?.mode||'workflow',actions:r.options?.maxActions||100,minutes:(r.options?.maxMs||900000)/60000,include:(r.scope.includePaths||[]).join(', '),exclude:(r.scope.excludePaths||[]).join(', '),origins:(r.scope.navigationOrigins||[]).filter(v=>v!==new URL(r.scope.entryUrl).origin).join(', '),resources:(r.scope.resourceOrigins||[]).filter(v=>!r.scope.navigationOrigins.includes(v)).join(', ')}))f[name].value=text;f.accessibility.checked=r.options?.accessibility!==false;f.replay.checked=r.options?.replay!==false;f.mode.dispatchEvent(new Event('change'));for(const node of dialog.querySelectorAll('[data-actions]'))node.setAttribute('aria-pressed',String(Number(node.dataset.actions)===Number(f.actions.value)&&Number(node.dataset.minutes)===Number(f.minutes.value)));setTab('Overview');}}
  status.textContent=r?(labels[r.status]||r.status)+' · '+(r.message||''):'Open a website to begin.';identity.textContent=r?r.scope.entryUrl+' · '+r.scope.roleId:'Browser-only testing';notice.textContent=!active?'Open a website, then sign in and start checking.':!ready?'Connect your engine in Mora to start checking.':teaching?'Finish your demonstration before starting automation.':running?'You can take over or stop at any time.':'The browser is ready for manual sign-in or automated checks.';
  const next=JSON.stringify([r,active,ready]);drawPermission();if(next===signature)return;signature=next;renderOverview();renderCases();renderFindings();renderExplore();renderEvidence();renderTeaching();renderHistory();
 }
 function show(seed={}){if(dialog){if(seed.url&&!state.websiteActive){f.url.value=seed.url;setTab('Setup');}return;}
  dialog=el('dialog',undefined,'tester-dialog website-dialog');dialog.setAttribute('aria-label','Website tester');const header=el('header',undefined,'website-header'),heading=el('div'),right=el('div',undefined,'website-header-actions');heading.append(el('h2','Website tester'));identity=el('p','Browser-only testing');heading.append(identity);right.append(el('span','Experimental','website-badge'),btn('Hide panel',()=>dialog.close()));header.append(heading,right);
  const workspace=el('div',undefined,'website-workspace'),navigation=el('nav',undefined,'website-nav'),body=el('div',undefined,'website-body');navigation.setAttribute('role','tablist');navigation.setAttribute('aria-label','Tester sections');
  for(const name of tabs){const key=name.toLowerCase(),node=btn(name,()=>setTab(name));node.id='website-tab-'+key;node.setAttribute('role','tab');node.setAttribute('aria-controls','website-pane-'+key);node.addEventListener('keydown',event=>{let i=tabs.indexOf(name);if(['ArrowRight','ArrowDown'].includes(event.key))i=(i+1)%tabs.length;else if(['ArrowLeft','ArrowUp'].includes(event.key))i=(i+tabs.length-1)%tabs.length;else if(event.key==='Home')i=0;else if(event.key==='End')i=tabs.length-1;else return;event.preventDefault();setTab(tabs[i],{focus:true});});nav[name]=node;navigation.append(node);const pane=el('section',undefined,'website-pane');pane.id='website-pane-'+key;pane.setAttribute('role','tabpanel');pane.setAttribute('aria-labelledby',node.id);pane.tabIndex=0;panes[name]=pane;body.append(pane);}workspace.append(navigation,body);
  form=el('form');form.id='website-setup-form';form.noValidate=true;const field=(name,label,tag='input',parent=form)=>{const wrap=el('label',label),input=el(tag);input.id='website-field-'+name;input.setAttribute('aria-label',label);wrap.htmlFor=input.id;wrap.append(input);parent.append(wrap);f[name]=input;return input;};const select=(name,label,choices,parent=form)=>{const input=field(name,label,'select',parent);for(const [v,text] of choices){const item=el('option',text);item.value=v;input.append(item);}return input;};
  panes.Setup.append(el('h3','1. Choose what to test'),el('p','Mora discovers and checks the rendered website. No project folder is needed.','website-muted'),form);const url=field('url','Website URL');url.type='url';url.required=true;url.placeholder='https://example.com';url.value=seed.url||'';
  select('mode','What to test',[['site','Discover this website'],['page','Only this page and its states'],['workflow','A specific workflow']]);const modeHelp=el('p',undefined,'website-muted');modeHelp.dataset.modeHint='';form.append(modeHelp);const explainMode=()=>{modeHelp.textContent={site:'Explore permitted pages and the connections between them.',page:'Stay on the starting page, including menus, dialogs and changing states.',workflow:'Concentrate on the workflow you describe below.'}[f.mode.value];};f.mode.addEventListener('change',explainMode);explainMode();const request=field('request','Workflow and expected result','textarea');request.rows=3;request.maxLength=12000;request.placeholder='For example: Test search and filters. Show only products matching the selected category.';request.value=seed.request||'';
  form.append(el('h3','2. Set your testing budget'));const presets=el('div',undefined,'website-presets');for(const [label,operations,time] of [['Quick',60,5],['Standard',100,15],['Intensive',300,30]]){const node=btn(label,()=>{f.actions.value=operations;f.minutes.value=time;for(const b of presets.children)b.setAttribute('aria-pressed',String(b===node));});node.dataset.actions=operations;node.dataset.minutes=time;node.setAttribute('aria-pressed',String(label==='Standard'));presets.append(node);}form.append(presets,el('p','Budgets limit browser operations and time. More time allows deeper checks but does not guarantee complete coverage.','website-muted'));
  const limits=el('div',undefined,'website-form-grid');form.append(limits);for(const [name,label,v,max] of [['actions','Maximum browser operations',100,500],['minutes','Time limit in minutes',15,60]]){const input=field(name,label,'input',limits);input.type='number';input.min='1';input.max=String(max);input.value=v;input.addEventListener('input',()=>{for(const b of presets.children)b.setAttribute('aria-pressed','false');});}
  const advanced=details('Account, screen size and website limits','setup-advanced');form.append(advanced);const grid=el('div',undefined,'website-form-grid');advanced.append(grid);field('role','Account label','input',grid).value='guest';f.role.maxLength=60;select('viewport','Screen size',[['desktop','Desktop'],['mobile','Mobile viewport']],grid);for(const [name,label] of [['origins','Additional navigation origins'],['resources','Additional resource origins'],['include','Include paths'],['exclude','Exclude paths']])field(name,label,'input',grid).placeholder=name==='include'||name==='exclude'?'/settings, /account':'https://example.com';advanced.append(el('p','Navigation origins permit pages and login redirects. Resource origins permit supporting APIs, fonts and images. Paths start with /. Separate multiple entries with commas.','website-muted'));for(const [name,label] of [['accessibility','Run accessibility scans'],['replay','Offer exact reproduction of failures']]){const input=field(name,label,'input',advanced);input.type='checkbox';input.checked=true;}
  const account=el('div',undefined,'website-inline-actions');c.saveLogin=btn('Save this login',()=>command('save-login'));c.forgetLogin=btn('Forget saved login',()=>command('forget-login'));account.append(c.saveLogin,c.forgetLogin);advanced.append(account);form.append(el('h3','3. Open and sign in'),el('p','Page text is sent to your connected AI. Use test accounts and avoid sensitive pages. Approve each exact test before it interacts with the live website.','website-muted'));c.open=el('button','Open website','website-primary');c.open.type='submit';c.open.setAttribute('form',form.id);
  const options=()=>({mode:f.mode.value,maxActions:Number(f.actions.value),maxDecisions:Math.min(750,Math.max(20,Number(f.actions.value)*2)),maxMs:Number(f.minutes.value)*60000,accessibility:f.accessibility.checked,replay:f.replay.checked});
  const validate=(opening=false)=>{for(const input of Object.values(f))input.removeAttribute('aria-invalid');let invalid,message;if(opening){try{const v=new URL(f.url.value);if(!['http:','https:'].includes(v.protocol)||v.username||v.password)throw Error();}catch{invalid=f.url;message='Enter a complete http:// or https:// URL without embedded credentials.';}}if(!invalid&&(!Number.isInteger(Number(f.actions.value))||Number(f.actions.value)<1||Number(f.actions.value)>500)){invalid=f.actions;message='Choose 1–500 browser operations.';}if(!invalid&&(!Number.isInteger(Number(f.minutes.value))||Number(f.minutes.value)<1||Number(f.minutes.value)>60)){invalid=f.minutes;message='Choose a time limit of 1–60 whole minutes.';}if(!invalid&&!f.request.value.trim()){if(f.mode.value==='workflow'){invalid=f.request;message='Describe the workflow and expected result.';}else f.request.value='Discover and test '+(f.mode.value==='page'?'this page':'this website')+'. Check visible requirements, normal workflows and applicable edge cases. Report what remains untested.';}if(invalid){errorBox.textContent=message;errorBox.hidden=false;invalid.setAttribute('aria-invalid','true');setTab('Setup');invalid.focus();return false;}errorBox.hidden=true;return true;};
  form.addEventListener('submit',async event=>{event.preventDefault();if(validate(true))await command('open',{url:f.url.value,request:f.request.value,roleId:f.role.value,viewport:f.viewport.value,navigationOrigins:f.origins.value,resourceOrigins:f.resources.value,includePaths:f.include.value,excludePaths:f.exclude.value,options:options()});});
  for(const name of tabs.filter(v=>v!=='Setup')){panes[name].append(el('h3',name==='Tests'?'Test cases':name));views[name]=el('div',undefined,'website-view');}const filterBar=name=>{const bar=el('div',undefined,'website-filters');panes[name].append(bar);return bar;};
  let bar=filterBar('Tests');field('caseSearch','Search tests','input',bar).type='search';select('caseFilter','Test status',[['all','All tests'],['attention','Needs attention'],['passed','Passed'],['queued','Waiting'],['not tested','Not tested'],['replanned','Plan corrected']],bar);for(const n of [f.caseSearch,f.caseFilter])n.addEventListener('input',renderCases);
  bar=filterBar('Findings');field('findingSearch','Search findings','input',bar).type='search';select('findingFilter','Finding type',[['all','All findings'],['functional','Functional'],['accessibility','Accessibility']],bar);for(const n of [f.findingSearch,f.findingFilter])n.addEventListener('input',renderFindings);
  field('featureSearch','Search discovered controls','input',panes.Explore).type='search';f.featureSearch.addEventListener('input',renderExplore);select('activity','Activity result',[['all','All activity'],['failed','Failed'],['blocked','Blocked'],['passed','Passed'],['ok','Interactions']],panes.Evidence).addEventListener('input',renderEvidence);
  panes.Teach.append(el('p','Sign in first. Selecting does not activate a control. Recording follows your real browser actions and can change live data. Private fields are excluded.','website-muted'));const teachingActions=el('div',undefined,'website-inline-actions');c.pick=btn('Select in browser',()=>command('teach',{mode:'pick'}));c.record=btn('Record workflow',()=>command('teach',{mode:'record'}));c.finish=btn('Finish recording',()=>command('finish-teaching'));c.focus=btn('Focus on selected control',()=>command('focus',{id:'selected'}));teachingActions.append(c.pick,c.record,c.finish,c.focus);panes.Teach.append(teachingActions);teachingPanel=views.Teach;panes.Teach.append(teachingPanel);field('expected','Demonstrated workflow expected outcome','textarea',panes.Teach);f.expected.rows=3;f.expected.maxLength=4000;f.expected.placeholder='What should happen when this workflow works correctly?';f.expected.addEventListener('input',draw);c.useTeaching=btn('Use this workflow',async()=>{const r=await command('use-teaching',{expected:f.expected.value});if(r?.request)f.request.value=r.request;},'website-primary');panes.Teach.append(c.useTeaching);
  const reportsActions=el('div',undefined,'website-inline-actions');c.reopen=btn('Reopen saved report',()=>command('reopen',{id:state.website.id}));reportsActions.append(c.reopen,btn('Refresh reports',async()=>{const list=await command('list');if(Array.isArray(list)){history=list;historyLoaded=true;renderHistory();}}));panes.Reports.append(reportsActions);const exportReport=async format=>{const r=await command('export',{id:state.website.id,format,includeEvidence:f.includeEvidence.checked});if(r?.saved)notice.textContent='Saved '+r.name;};c.exportHtml=btn('Export HTML',()=>exportReport('html'));c.exportJson=btn('Export JSON',()=>exportReport('json'));reportsActions.append(c.exportHtml,c.exportJson);field('includeEvidence','Include masked screenshots in export','input',panes.Reports).type='checkbox';field('historySearch','Search saved reports','input',panes.Reports).type='search';f.historySearch.addEventListener('input',renderHistory);for(const name of tabs.filter(v=>!['Setup','Teach'].includes(v)))panes[name].append(views[name]);
  permission=el('section',undefined,'website-permission');permission.hidden=true;permission.setAttribute('aria-label','Website action permission');permission.setAttribute('aria-live','polite');errorBox=el('p',undefined,'website-error');errorBox.hidden=true;errorBox.setAttribute('role','alert');errorBox.id='website-error';for(const input of Object.values(f))input.setAttribute('aria-describedby',errorBox.id);
  const footer=el('footer',undefined,'website-footer'),toolbar=el('div',undefined,'website-toolbar');c.start=btn('Start checking',()=>{if(validate())command('start',{request:f.request.value,options:options()});},'website-primary');c.steer=btn('Update testing focus',()=>{if(validate())command('steer',{request:f.request.value,options:options(),scope:{includePaths:f.include.value,excludePaths:f.exclude.value}});});c.pause=btn('Take over / sign in',()=>command('takeover'));c.stop=btn('Stop and close browser',()=>command('stop'),'website-stop');toolbar.append(c.open,c.start,c.steer,c.pause,c.stop);status=el('p',undefined,'website-status');status.setAttribute('role','status');notice=el('p',undefined,'website-muted');footer.append(status,toolbar,notice,el('small','Hiding this panel keeps the browser open. Stop closes the browser.'));
  dialog.append(header,errorBox,workspace,permission,footer);dialog.addEventListener('close',()=>{dialog.remove();dialog=null;signature=permissionSignature='';lastReport=undefined;images.clear();api.browserCommand?.('occlude',{hidden:false}).catch(()=>{});button.focus();});api.browserCommand?.('occlude',{hidden:true}).catch(()=>{});document.body.append(dialog);dialog.showModal();setTab('Setup');draw();if(tab==='Setup')f.url.focus();
 }
 button.addEventListener('click',()=>show());return next=>{state=next;button.disabled=!!state.loading||!!state.testerActive;if(state.websiteOpen?.id!==lastOpen){lastOpen=state.websiteOpen?.id;if(lastOpen)show(state.websiteOpen);}draw();};
}
