import {redactText} from './website-policy.js';
import {websiteCoverage} from './website-coverage.js';
export {websiteCoverage} from './website-coverage.js';

const text=value=>redactText(value??'').slice(0,16000);
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const evidenceName=value=>typeof value==='string'&&/^screen-[a-f0-9-]+\.png$/.test(value);
function publicStep(step,features) {
  const action=step.action&&typeof step.action==='object'?step.action:step,control=features.find(f=>f.key===action.target||f.key===action.targetKey);
  return {id:step.id,caseId:step.caseId,at:step.at,action:action.action,target:text(step.control||control?.name||action.target),value:text(action.value),check:action.check,expected:typeof action.expected==='string'?text(action.expected):action.expected,basis:text(action.basis),status:step.status==='uncertain'?'uncertain':step.result?.status||step.status||'planned',actual:typeof step.result?.actual==='string'?text(step.result.actual):step.result?.actual,reason:text(step.result?.reason),...(evidenceName(step.result?.screenshot?.name)?{screenshot:step.result.screenshot.name}:{})};
}
export function buildWebsiteExport(report,{format='html',evidence={}}={}) {
  if(!['html','json'].includes(format))throw Error('Choose HTML or JSON export format.');
  const images={};let bytes=0;
  const known=new Set([...(report.steps||[]).map(s=>s.result?.screenshot?.name),...(report.accessibility||[]).map(s=>s.screenshot?.name)].filter(evidenceName));
  for(const [name,data] of Object.entries(evidence)){
    if(!known.has(name)||!evidenceName(name)||typeof data!=='string'||!/^iVBORw0KGgo[A-Za-z0-9+/]*={0,2}$/.test(data)||data.length>14*1024*1024||(bytes+=data.length)>32*1024*1024)throw Error('Invalid or oversized export evidence.');
    images[name]=data;
  }
  const features=report.discovery?.features||[];
  const output={schemaVersion:1,kind:'website-test-export',id:report.id,createdAt:report.createdAt,exportedAt:new Date().toISOString(),url:text(report.scope?.entryUrl),role:text(report.scope?.roleId),request:text(report.request),status:report.status,message:text(report.message),coverage:websiteCoverage(report),limits:{mode:report.options?.mode,maxActions:report.options?.maxActions,maxDecisions:report.options?.maxDecisions,maxMs:report.options?.maxMs},scope:{navigationOrigins:report.scope?.navigationOrigins?.map(text),resourceOrigins:report.scope?.resourceOrigins?.map(text),includePaths:report.scope?.includePaths?.map(text),excludePaths:report.scope?.excludePaths?.map(text)},
    findings:(report.findings||[]).map(f=>({id:f.id,kind:f.kind,title:text(f.title),status:f.status,confidence:f.confidence,severity:f.severity,impact:text(f.impact),url:text(f.url),role:text(f.roleId),caseId:f.caseId,stepId:f.stepId,expected:text(f.expected),actual:text(f.actual),basis:text(f.basis),ruleId:text(f.ruleId),target:text(JSON.stringify(f.target)),replay:f.replay?{status:f.replay.status,stepIds:f.replay.stepIds}:null})),
    cases:(report.cases||[]).map(c=>({id:c.id,title:text(c.title),family:c.family,status:c.status,reason:text(c.reason),start:{url:text(c.start?.url),role:text(c.start?.roleId),stateId:c.start?.stateId,conditionId:c.start?.conditionId},startChecks:(c.startChecks||[]).map(s=>publicStep(s,features)),reset:(c.reset||[]).map(s=>publicStep(s,features)),precondition:text(c.precondition),basis:text(c.grounding?.quote),steps:(c.steps||[]).map(s=>publicStep(s,features)),executions:(c.executions||[]).map(e=>({id:e.id,replay:!!e.replay,startStateId:e.startStateId,startConditionId:e.startConditionId,steps:(e.steps||[]).map(s=>publicStep(s,features))}))})),
    steps:(report.steps||[]).map(s=>publicStep(s,features)),accessibility:(report.accessibility||[]).map(s=>({url:text(s.url),passedRules:s.passedRules,violations:(s.violations||[]).map(r=>({id:text(r.id),help:text(r.help),impact:r.impact,nodes:(r.nodes||[]).map(n=>({target:text(JSON.stringify(n.target)),summary:text(n.summary)}))})),incomplete:(s.incomplete||[]).map(r=>({id:text(r.id),help:text(r.help)})),...(evidenceName(s.screenshot?.name)?{screenshot:s.screenshot.name}:{})})),gaps:[...(report.gaps||[]).map(text),...(report.blockedOrigins||[]).map(v=>'Blocked origin: '+text(v))],evidence:images};
  if(format==='json')return JSON.stringify(output,null,2);
  const image=name=>images[name]?`<img alt="Masked website evidence" src="data:image/png;base64,${images[name]}">`:name?'<p>Evidence image was not included.</p>':'';
  const steps=list=>`<ol>${list.map(s=>`<li><strong>${escape(s.action)} ${escape(s.target)} — ${escape(s.status)}</strong>${s.action==='assert'?`<p>Expected: ${escape(s.expected)}<br>Observed: ${escape(s.actual)}<br>Basis: ${escape(s.basis)}</p>`:`<p>${escape(s.value)}</p>`}<p>${escape(s.reason)}</p>${image(s.screenshot)}</li>`).join('')}</ol>`;
  return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src data:; style-src 'unsafe-inline'"><title>Website test report</title><style>body{font:16px/1.5 system-ui,sans-serif;max-width:1000px;margin:32px auto;padding:0 24px;color:#20232a;background:#fff}h1,h2{line-height:1.2}article,details{border-top:1px solid #ccc;padding:16px 0}p,li{overflow-wrap:anywhere;white-space:pre-wrap}img{max-width:100%;border:1px solid #ddd}summary{cursor:pointer;font-weight:600}small{color:#555}</style><main>
<h1>Website test report</h1><p>${escape(output.url)} · ${escape(output.role)} · ${escape(output.status)}</p><p>${escape(output.request)}</p><small>Created ${escape(output.createdAt)} · Exported ${escape(output.exportedAt)}</small>
<h2>Coverage</h2><p>${output.coverage.states} observed states · ${output.coverage.controls} discovered controls · ${output.coverage.exercised} exercised controls · ${output.coverage.checked} controls with assertions · ${output.coverage.unchecked} without assertions</p><p>${escape(JSON.stringify(output.coverage.assertions))}</p><p>Coverage is limited to observed behavior. Automated accessibility checks do not establish conformance.</p>
<h2>Findings</h2>${output.findings.length?output.findings.map(f=>`<article><h3>${escape(f.title)}</h3><p>${escape(f.status)} · Confidence: ${escape(f.confidence)} · Severity: ${escape(f.severity)}</p><p>${escape(f.url)} · ${escape(f.role)}</p><p>${escape(f.impact)}</p><p>Expected: ${escape(f.expected)}<br>Observed: ${escape(f.actual)}<br>Basis: ${escape(f.basis)}</p><p>${escape(f.ruleId)} ${escape(f.target)}</p><p>Case: ${escape(f.caseId)} · Evidence step: ${escape(f.stepId)}</p></article>`).join(''):'<p>No findings recorded. This does not mean all behavior was tested.</p>'}
<h2>Cases</h2>${output.cases.map(c=>`<details><summary>${escape(c.title)} — ${escape(c.status)}</summary><p>${escape(c.reason)}<br>Start: ${escape(c.start.url)} · ${escape(c.start.role)}<br>Precondition: ${escape(c.precondition)}<br>Basis: ${escape(c.basis)}</p><h3>Required starting conditions</h3>${steps(c.startChecks)}<h3>Setup before retrying</h3>${steps(c.reset)}<h3>Planned steps</h3>${steps(c.steps)}${c.executions.map(e=>`<h3>${e.replay?'Reproduction':'Execution'}</h3>${steps(e.steps)}`).join('')}</details>`).join('')}
<h2>Action and evidence timeline</h2>${steps(output.steps)}<h2>Accessibility and manual review</h2>${output.accessibility.map(s=>`<article><p>${escape(s.url)} · ${s.passedRules||0} rules passed</p>${s.violations.map(r=>`<p>${escape(r.id)}: ${escape(r.help)} · ${escape(r.impact)}</p>${r.nodes.map(n=>`<p>${escape(n.target)} ${escape(n.summary)}</p>`).join('')}`).join('')}${s.incomplete.map(r=>`<p>Manual review: ${escape(r.id)} — ${escape(r.help)}</p>`).join('')}${image(s.screenshot)}</article>`).join('')}
<h2>Not tested and limitations</h2><ul>${output.gaps.map(g=>`<li>${escape(g)}</li>`).join('')}</ul><p>Scope and limits: ${escape(JSON.stringify({scope:output.scope,limits:output.limits}))}</p></main></html>`;
}
